/*
Airflow API

Testing XComAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package airflow

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/leonkiss2912/airflow3-client-go"
)

func Test_airflow_XComAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test XComAPIService CreateXcomEntry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dagId string
		var taskId string
		var dagRunId string

		resp, httpRes, err := apiClient.XComAPI.CreateXcomEntry(context.Background(), dagId, taskId, dagRunId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test XComAPIService DeleteXcomEntry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dagId string
		var taskId string
		var dagRunId string
		var xcomKey string

		httpRes, err := apiClient.XComAPI.DeleteXcomEntry(context.Background(), dagId, taskId, dagRunId, xcomKey).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test XComAPIService GetXcomEntries", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dagId string
		var dagRunId string
		var taskId string

		resp, httpRes, err := apiClient.XComAPI.GetXcomEntries(context.Background(), dagId, dagRunId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test XComAPIService GetXcomEntry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dagId string
		var taskId string
		var dagRunId string
		var xcomKey string

		resp, httpRes, err := apiClient.XComAPI.GetXcomEntry(context.Background(), dagId, taskId, dagRunId, xcomKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test XComAPIService UpdateXcomEntry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dagId string
		var taskId string
		var dagRunId string
		var xcomKey string

		resp, httpRes, err := apiClient.XComAPI.UpdateXcomEntry(context.Background(), dagId, taskId, dagRunId, xcomKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
