/*
Airflow API

Testing DagStatsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package airflow

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/leonkiss2912/airflow3-client-go"
)

func Test_airflow_DagStatsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DagStatsAPIService GetDagStats", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DagStatsAPI.GetDagStats(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
