/*
Airflow API

Testing TaskAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package airflow

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/airflow"
)

func Test_airflow_TaskAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TaskAPIService GetTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dagId string
		var taskId openapiclient.interface{}

		resp, httpRes, err := apiClient.TaskAPI.GetTask(context.Background(), dagId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskAPIService GetTasks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dagId string

		resp, httpRes, err := apiClient.TaskAPI.GetTasks(context.Background(), dagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
