/*
Airflow API

Testing AssetAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package airflow

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/leonkiss2912/airflow3-client-go"
)

func Test_airflow_AssetAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AssetAPIService CreateAssetEvent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AssetAPI.CreateAssetEvent(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetAPIService DeleteAssetQueuedEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var assetId int32

		httpRes, err := apiClient.AssetAPI.DeleteAssetQueuedEvents(context.Background(), assetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetAPIService DeleteDagAssetQueuedEvent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dagId string
		var assetId int32

		httpRes, err := apiClient.AssetAPI.DeleteDagAssetQueuedEvent(context.Background(), dagId, assetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetAPIService DeleteDagAssetQueuedEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dagId string

		httpRes, err := apiClient.AssetAPI.DeleteDagAssetQueuedEvents(context.Background(), dagId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetAPIService GetAsset", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var assetId int32

		resp, httpRes, err := apiClient.AssetAPI.GetAsset(context.Background(), assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetAPIService GetAssetAlias", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var assetAliasId int32

		resp, httpRes, err := apiClient.AssetAPI.GetAssetAlias(context.Background(), assetAliasId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetAPIService GetAssetAliases", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AssetAPI.GetAssetAliases(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetAPIService GetAssetEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AssetAPI.GetAssetEvents(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetAPIService GetAssetQueuedEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var assetId int32

		resp, httpRes, err := apiClient.AssetAPI.GetAssetQueuedEvents(context.Background(), assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetAPIService GetAssets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AssetAPI.GetAssets(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetAPIService GetDagAssetQueuedEvent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dagId string
		var assetId int32

		resp, httpRes, err := apiClient.AssetAPI.GetDagAssetQueuedEvent(context.Background(), dagId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetAPIService GetDagAssetQueuedEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dagId string

		resp, httpRes, err := apiClient.AssetAPI.GetDagAssetQueuedEvents(context.Background(), dagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetAPIService MaterializeAsset", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var assetId int32

		resp, httpRes, err := apiClient.AssetAPI.MaterializeAsset(context.Background(), assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
