/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobCollectionResponse{}

// JobCollectionResponse Job Collection Response.
type JobCollectionResponse struct {
	Jobs []JobResponse `json:"jobs"`
	TotalEntries int32 `json:"total_entries"`
}

type _JobCollectionResponse JobCollectionResponse

// NewJobCollectionResponse instantiates a new JobCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobCollectionResponse(jobs []JobResponse, totalEntries int32) *JobCollectionResponse {
	this := JobCollectionResponse{}
	this.Jobs = jobs
	this.TotalEntries = totalEntries
	return &this
}

// NewJobCollectionResponseWithDefaults instantiates a new JobCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobCollectionResponseWithDefaults() *JobCollectionResponse {
	this := JobCollectionResponse{}
	return &this
}

// GetJobs returns the Jobs field value
func (o *JobCollectionResponse) GetJobs() []JobResponse {
	if o == nil {
		var ret []JobResponse
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
func (o *JobCollectionResponse) GetJobsOk() ([]JobResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jobs, true
}

// SetJobs sets field value
func (o *JobCollectionResponse) SetJobs(v []JobResponse) {
	o.Jobs = v
}

// GetTotalEntries returns the TotalEntries field value
func (o *JobCollectionResponse) GetTotalEntries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalEntries
}

// GetTotalEntriesOk returns a tuple with the TotalEntries field value
// and a boolean to check if the value has been set.
func (o *JobCollectionResponse) GetTotalEntriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalEntries, true
}

// SetTotalEntries sets field value
func (o *JobCollectionResponse) SetTotalEntries(v int32) {
	o.TotalEntries = v
}

func (o JobCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobs"] = o.Jobs
	toSerialize["total_entries"] = o.TotalEntries
	return toSerialize, nil
}

func (o *JobCollectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobs",
		"total_entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobCollectionResponse := _JobCollectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobCollectionResponse)

	if err != nil {
		return err
	}

	*o = JobCollectionResponse(varJobCollectionResponse)

	return err
}

type NullableJobCollectionResponse struct {
	value *JobCollectionResponse
	isSet bool
}

func (v NullableJobCollectionResponse) Get() *JobCollectionResponse {
	return v.value
}

func (v *NullableJobCollectionResponse) Set(val *JobCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableJobCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableJobCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobCollectionResponse(val *JobCollectionResponse) *NullableJobCollectionResponse {
	return &NullableJobCollectionResponse{value: val, isSet: true}
}

func (v NullableJobCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


