/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkUpdateActionVariableBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkUpdateActionVariableBody{}

// BulkUpdateActionVariableBody struct for BulkUpdateActionVariableBody
type BulkUpdateActionVariableBody struct {
	// The action to be performed on the entities.
	Action string `json:"action"`
	// A list of entities to be updated.
	Entities []VariableBody `json:"entities"`
	// A list of field names to update for each entity.Only these fields will be applied from the request body to the database model.Any extra fields provided will be ignored.
	UpdateMask []string `json:"update_mask,omitempty"`
	ActionOnNonExistence *BulkActionNotOnExistence `json:"action_on_non_existence,omitempty"`
}

type _BulkUpdateActionVariableBody BulkUpdateActionVariableBody

// NewBulkUpdateActionVariableBody instantiates a new BulkUpdateActionVariableBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkUpdateActionVariableBody(action string, entities []VariableBody) *BulkUpdateActionVariableBody {
	this := BulkUpdateActionVariableBody{}
	this.Action = action
	this.Entities = entities
	var actionOnNonExistence BulkActionNotOnExistence = BULKACTIONNOTONEXISTENCE_FAIL
	this.ActionOnNonExistence = &actionOnNonExistence
	return &this
}

// NewBulkUpdateActionVariableBodyWithDefaults instantiates a new BulkUpdateActionVariableBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkUpdateActionVariableBodyWithDefaults() *BulkUpdateActionVariableBody {
	this := BulkUpdateActionVariableBody{}
	var actionOnNonExistence BulkActionNotOnExistence = BULKACTIONNOTONEXISTENCE_FAIL
	this.ActionOnNonExistence = &actionOnNonExistence
	return &this
}

// GetAction returns the Action field value
func (o *BulkUpdateActionVariableBody) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *BulkUpdateActionVariableBody) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *BulkUpdateActionVariableBody) SetAction(v string) {
	o.Action = v
}

// GetEntities returns the Entities field value
func (o *BulkUpdateActionVariableBody) GetEntities() []VariableBody {
	if o == nil {
		var ret []VariableBody
		return ret
	}

	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value
// and a boolean to check if the value has been set.
func (o *BulkUpdateActionVariableBody) GetEntitiesOk() ([]VariableBody, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entities, true
}

// SetEntities sets field value
func (o *BulkUpdateActionVariableBody) SetEntities(v []VariableBody) {
	o.Entities = v
}

// GetUpdateMask returns the UpdateMask field value if set, zero value otherwise.
func (o *BulkUpdateActionVariableBody) GetUpdateMask() []string {
	if o == nil || IsNil(o.UpdateMask) {
		var ret []string
		return ret
	}
	return o.UpdateMask
}

// GetUpdateMaskOk returns a tuple with the UpdateMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkUpdateActionVariableBody) GetUpdateMaskOk() ([]string, bool) {
	if o == nil || IsNil(o.UpdateMask) {
		return nil, false
	}
	return o.UpdateMask, true
}

// HasUpdateMask returns a boolean if a field has been set.
func (o *BulkUpdateActionVariableBody) HasUpdateMask() bool {
	if o != nil && !IsNil(o.UpdateMask) {
		return true
	}

	return false
}

// SetUpdateMask gets a reference to the given []string and assigns it to the UpdateMask field.
func (o *BulkUpdateActionVariableBody) SetUpdateMask(v []string) {
	o.UpdateMask = v
}

// GetActionOnNonExistence returns the ActionOnNonExistence field value if set, zero value otherwise.
func (o *BulkUpdateActionVariableBody) GetActionOnNonExistence() BulkActionNotOnExistence {
	if o == nil || IsNil(o.ActionOnNonExistence) {
		var ret BulkActionNotOnExistence
		return ret
	}
	return *o.ActionOnNonExistence
}

// GetActionOnNonExistenceOk returns a tuple with the ActionOnNonExistence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkUpdateActionVariableBody) GetActionOnNonExistenceOk() (*BulkActionNotOnExistence, bool) {
	if o == nil || IsNil(o.ActionOnNonExistence) {
		return nil, false
	}
	return o.ActionOnNonExistence, true
}

// HasActionOnNonExistence returns a boolean if a field has been set.
func (o *BulkUpdateActionVariableBody) HasActionOnNonExistence() bool {
	if o != nil && !IsNil(o.ActionOnNonExistence) {
		return true
	}

	return false
}

// SetActionOnNonExistence gets a reference to the given BulkActionNotOnExistence and assigns it to the ActionOnNonExistence field.
func (o *BulkUpdateActionVariableBody) SetActionOnNonExistence(v BulkActionNotOnExistence) {
	o.ActionOnNonExistence = &v
}

func (o BulkUpdateActionVariableBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkUpdateActionVariableBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["entities"] = o.Entities
	if !IsNil(o.UpdateMask) {
		toSerialize["update_mask"] = o.UpdateMask
	}
	if !IsNil(o.ActionOnNonExistence) {
		toSerialize["action_on_non_existence"] = o.ActionOnNonExistence
	}
	return toSerialize, nil
}

func (o *BulkUpdateActionVariableBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"entities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkUpdateActionVariableBody := _BulkUpdateActionVariableBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkUpdateActionVariableBody)

	if err != nil {
		return err
	}

	*o = BulkUpdateActionVariableBody(varBulkUpdateActionVariableBody)

	return err
}

type NullableBulkUpdateActionVariableBody struct {
	value *BulkUpdateActionVariableBody
	isSet bool
}

func (v NullableBulkUpdateActionVariableBody) Get() *BulkUpdateActionVariableBody {
	return v.value
}

func (v *NullableBulkUpdateActionVariableBody) Set(val *BulkUpdateActionVariableBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkUpdateActionVariableBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkUpdateActionVariableBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkUpdateActionVariableBody(val *BulkUpdateActionVariableBody) *NullableBulkUpdateActionVariableBody {
	return &NullableBulkUpdateActionVariableBody{value: val, isSet: true}
}

func (v NullableBulkUpdateActionVariableBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkUpdateActionVariableBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


