/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the EventLogResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventLogResponse{}

// EventLogResponse Event Log Response.
type EventLogResponse struct {
	EventLogId int32 `json:"event_log_id"`
	When time.Time `json:"when"`
	DagId string `json:"dag_id"`
	TaskId string `json:"task_id"`
	RunId string `json:"run_id"`
	MapIndex int32 `json:"map_index"`
	TryNumber int32 `json:"try_number"`
	Event string `json:"event"`
	LogicalDate time.Time `json:"logical_date"`
	Owner string `json:"owner"`
	Extra string `json:"extra"`
	DagDisplayName *string `json:"dag_display_name,omitempty"`
	TaskDisplayName *string `json:"task_display_name,omitempty"`
}

type _EventLogResponse EventLogResponse

// NewEventLogResponse instantiates a new EventLogResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventLogResponse(eventLogId int32, when time.Time, dagId string, taskId string, runId string, mapIndex int32, tryNumber int32, event string, logicalDate time.Time, owner string, extra string) *EventLogResponse {
	this := EventLogResponse{}
	this.EventLogId = eventLogId
	this.When = when
	this.DagId = dagId
	this.TaskId = taskId
	this.RunId = runId
	this.MapIndex = mapIndex
	this.TryNumber = tryNumber
	this.Event = event
	this.LogicalDate = logicalDate
	this.Owner = owner
	this.Extra = extra
	return &this
}

// NewEventLogResponseWithDefaults instantiates a new EventLogResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventLogResponseWithDefaults() *EventLogResponse {
	this := EventLogResponse{}
	return &this
}

// GetEventLogId returns the EventLogId field value
func (o *EventLogResponse) GetEventLogId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EventLogId
}

// GetEventLogIdOk returns a tuple with the EventLogId field value
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetEventLogIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventLogId, true
}

// SetEventLogId sets field value
func (o *EventLogResponse) SetEventLogId(v int32) {
	o.EventLogId = v
}

// GetWhen returns the When field value
func (o *EventLogResponse) GetWhen() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.When
}

// GetWhenOk returns a tuple with the When field value
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetWhenOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.When, true
}

// SetWhen sets field value
func (o *EventLogResponse) SetWhen(v time.Time) {
	o.When = v
}

// GetDagId returns the DagId field value
func (o *EventLogResponse) GetDagId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DagId
}

// GetDagIdOk returns a tuple with the DagId field value
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetDagIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DagId, true
}

// SetDagId sets field value
func (o *EventLogResponse) SetDagId(v string) {
	o.DagId = v
}

// GetTaskId returns the TaskId field value
func (o *EventLogResponse) GetTaskId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskId, true
}

// SetTaskId sets field value
func (o *EventLogResponse) SetTaskId(v string) {
	o.TaskId = v
}

// GetRunId returns the RunId field value
func (o *EventLogResponse) GetRunId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RunId
}

// GetRunIdOk returns a tuple with the RunId field value
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunId, true
}

// SetRunId sets field value
func (o *EventLogResponse) SetRunId(v string) {
	o.RunId = v
}

// GetMapIndex returns the MapIndex field value
func (o *EventLogResponse) GetMapIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MapIndex
}

// GetMapIndexOk returns a tuple with the MapIndex field value
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetMapIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MapIndex, true
}

// SetMapIndex sets field value
func (o *EventLogResponse) SetMapIndex(v int32) {
	o.MapIndex = v
}

// GetTryNumber returns the TryNumber field value
func (o *EventLogResponse) GetTryNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TryNumber
}

// GetTryNumberOk returns a tuple with the TryNumber field value
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetTryNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TryNumber, true
}

// SetTryNumber sets field value
func (o *EventLogResponse) SetTryNumber(v int32) {
	o.TryNumber = v
}

// GetEvent returns the Event field value
func (o *EventLogResponse) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *EventLogResponse) SetEvent(v string) {
	o.Event = v
}

// GetLogicalDate returns the LogicalDate field value
func (o *EventLogResponse) GetLogicalDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LogicalDate
}

// GetLogicalDateOk returns a tuple with the LogicalDate field value
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetLogicalDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogicalDate, true
}

// SetLogicalDate sets field value
func (o *EventLogResponse) SetLogicalDate(v time.Time) {
	o.LogicalDate = v
}

// GetOwner returns the Owner field value
func (o *EventLogResponse) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *EventLogResponse) SetOwner(v string) {
	o.Owner = v
}

// GetExtra returns the Extra field value
func (o *EventLogResponse) GetExtra() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Extra
}

// GetExtraOk returns a tuple with the Extra field value
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetExtraOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Extra, true
}

// SetExtra sets field value
func (o *EventLogResponse) SetExtra(v string) {
	o.Extra = v
}

// GetDagDisplayName returns the DagDisplayName field value if set, zero value otherwise.
func (o *EventLogResponse) GetDagDisplayName() string {
	if o == nil || IsNil(o.DagDisplayName) {
		var ret string
		return ret
	}
	return *o.DagDisplayName
}

// GetDagDisplayNameOk returns a tuple with the DagDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetDagDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DagDisplayName) {
		return nil, false
	}
	return o.DagDisplayName, true
}

// HasDagDisplayName returns a boolean if a field has been set.
func (o *EventLogResponse) HasDagDisplayName() bool {
	if o != nil && !IsNil(o.DagDisplayName) {
		return true
	}

	return false
}

// SetDagDisplayName gets a reference to the given string and assigns it to the DagDisplayName field.
func (o *EventLogResponse) SetDagDisplayName(v string) {
	o.DagDisplayName = &v
}

// GetTaskDisplayName returns the TaskDisplayName field value if set, zero value otherwise.
func (o *EventLogResponse) GetTaskDisplayName() string {
	if o == nil || IsNil(o.TaskDisplayName) {
		var ret string
		return ret
	}
	return *o.TaskDisplayName
}

// GetTaskDisplayNameOk returns a tuple with the TaskDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventLogResponse) GetTaskDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.TaskDisplayName) {
		return nil, false
	}
	return o.TaskDisplayName, true
}

// HasTaskDisplayName returns a boolean if a field has been set.
func (o *EventLogResponse) HasTaskDisplayName() bool {
	if o != nil && !IsNil(o.TaskDisplayName) {
		return true
	}

	return false
}

// SetTaskDisplayName gets a reference to the given string and assigns it to the TaskDisplayName field.
func (o *EventLogResponse) SetTaskDisplayName(v string) {
	o.TaskDisplayName = &v
}

func (o EventLogResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventLogResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_log_id"] = o.EventLogId
	toSerialize["when"] = o.When
	toSerialize["dag_id"] = o.DagId
	toSerialize["task_id"] = o.TaskId
	toSerialize["run_id"] = o.RunId
	toSerialize["map_index"] = o.MapIndex
	toSerialize["try_number"] = o.TryNumber
	toSerialize["event"] = o.Event
	toSerialize["logical_date"] = o.LogicalDate
	toSerialize["owner"] = o.Owner
	toSerialize["extra"] = o.Extra
	if !IsNil(o.DagDisplayName) {
		toSerialize["dag_display_name"] = o.DagDisplayName
	}
	if !IsNil(o.TaskDisplayName) {
		toSerialize["task_display_name"] = o.TaskDisplayName
	}
	return toSerialize, nil
}

func (o *EventLogResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_log_id",
		"when",
		"dag_id",
		"task_id",
		"run_id",
		"map_index",
		"try_number",
		"event",
		"logical_date",
		"owner",
		"extra",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventLogResponse := _EventLogResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventLogResponse)

	if err != nil {
		return err
	}

	*o = EventLogResponse(varEventLogResponse)

	return err
}

type NullableEventLogResponse struct {
	value *EventLogResponse
	isSet bool
}

func (v NullableEventLogResponse) Get() *EventLogResponse {
	return v.value
}

func (v *NullableEventLogResponse) Set(val *EventLogResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEventLogResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEventLogResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventLogResponse(val *EventLogResponse) *NullableEventLogResponse {
	return &NullableEventLogResponse{value: val, isSet: true}
}

func (v NullableEventLogResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventLogResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


