/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DAGWarningResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DAGWarningResponse{}

// DAGWarningResponse Dag Warning serializer for responses.
type DAGWarningResponse struct {
	DagId string `json:"dag_id"`
	WarningType DagWarningType `json:"warning_type"`
	Message string `json:"message"`
	Timestamp time.Time `json:"timestamp"`
	DagDisplayName string `json:"dag_display_name"`
}

type _DAGWarningResponse DAGWarningResponse

// NewDAGWarningResponse instantiates a new DAGWarningResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDAGWarningResponse(dagId string, warningType DagWarningType, message string, timestamp time.Time, dagDisplayName string) *DAGWarningResponse {
	this := DAGWarningResponse{}
	this.DagId = dagId
	this.WarningType = warningType
	this.Message = message
	this.Timestamp = timestamp
	this.DagDisplayName = dagDisplayName
	return &this
}

// NewDAGWarningResponseWithDefaults instantiates a new DAGWarningResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDAGWarningResponseWithDefaults() *DAGWarningResponse {
	this := DAGWarningResponse{}
	return &this
}

// GetDagId returns the DagId field value
func (o *DAGWarningResponse) GetDagId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DagId
}

// GetDagIdOk returns a tuple with the DagId field value
// and a boolean to check if the value has been set.
func (o *DAGWarningResponse) GetDagIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DagId, true
}

// SetDagId sets field value
func (o *DAGWarningResponse) SetDagId(v string) {
	o.DagId = v
}

// GetWarningType returns the WarningType field value
func (o *DAGWarningResponse) GetWarningType() DagWarningType {
	if o == nil {
		var ret DagWarningType
		return ret
	}

	return o.WarningType
}

// GetWarningTypeOk returns a tuple with the WarningType field value
// and a boolean to check if the value has been set.
func (o *DAGWarningResponse) GetWarningTypeOk() (*DagWarningType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WarningType, true
}

// SetWarningType sets field value
func (o *DAGWarningResponse) SetWarningType(v DagWarningType) {
	o.WarningType = v
}

// GetMessage returns the Message field value
func (o *DAGWarningResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *DAGWarningResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *DAGWarningResponse) SetMessage(v string) {
	o.Message = v
}

// GetTimestamp returns the Timestamp field value
func (o *DAGWarningResponse) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *DAGWarningResponse) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *DAGWarningResponse) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetDagDisplayName returns the DagDisplayName field value
func (o *DAGWarningResponse) GetDagDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DagDisplayName
}

// GetDagDisplayNameOk returns a tuple with the DagDisplayName field value
// and a boolean to check if the value has been set.
func (o *DAGWarningResponse) GetDagDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DagDisplayName, true
}

// SetDagDisplayName sets field value
func (o *DAGWarningResponse) SetDagDisplayName(v string) {
	o.DagDisplayName = v
}

func (o DAGWarningResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DAGWarningResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dag_id"] = o.DagId
	toSerialize["warning_type"] = o.WarningType
	toSerialize["message"] = o.Message
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["dag_display_name"] = o.DagDisplayName
	return toSerialize, nil
}

func (o *DAGWarningResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dag_id",
		"warning_type",
		"message",
		"timestamp",
		"dag_display_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDAGWarningResponse := _DAGWarningResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDAGWarningResponse)

	if err != nil {
		return err
	}

	*o = DAGWarningResponse(varDAGWarningResponse)

	return err
}

type NullableDAGWarningResponse struct {
	value *DAGWarningResponse
	isSet bool
}

func (v NullableDAGWarningResponse) Get() *DAGWarningResponse {
	return v.value
}

func (v *NullableDAGWarningResponse) Set(val *DAGWarningResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDAGWarningResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDAGWarningResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDAGWarningResponse(val *DAGWarningResponse) *NullableDAGWarningResponse {
	return &NullableDAGWarningResponse{value: val, isSet: true}
}

func (v NullableDAGWarningResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDAGWarningResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


