/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"fmt"
)


// Content struct for Content
type Content struct {
	ArrayOfStructuredLogMessage *[]StructuredLogMessage
	ArrayOfString *[]string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Content) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ArrayOfStructuredLogMessage
	err = json.Unmarshal(data, &dst.ArrayOfStructuredLogMessage);
	if err == nil {
		jsonArrayOfStructuredLogMessage, _ := json.Marshal(dst.ArrayOfStructuredLogMessage)
		if string(jsonArrayOfStructuredLogMessage) == "{}" { // empty struct
			dst.ArrayOfStructuredLogMessage = nil
		} else {
			return nil // data stored in dst.ArrayOfStructuredLogMessage, return on the first match
		}
	} else {
		dst.ArrayOfStructuredLogMessage = nil
	}

	// try to unmarshal JSON data into ArrayOfString
	err = json.Unmarshal(data, &dst.ArrayOfString);
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			return nil // data stored in dst.ArrayOfString, return on the first match
		}
	} else {
		dst.ArrayOfString = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Content)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Content) MarshalJSON() ([]byte, error) {
	if src.ArrayOfStructuredLogMessage != nil {
		return json.Marshal(&src.ArrayOfStructuredLogMessage)
	}

	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableContent struct {
	value *Content
	isSet bool
}

func (v NullableContent) Get() *Content {
	return v.value
}

func (v *NullableContent) Set(val *Content) {
	v.value = val
	v.isSet = true
}

func (v NullableContent) IsSet() bool {
	return v.isSet
}

func (v *NullableContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContent(val *Content) *NullableContent {
	return &NullableContent{value: val, isSet: true}
}

func (v NullableContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


