/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkDeleteActionConnectionBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkDeleteActionConnectionBody{}

// BulkDeleteActionConnectionBody struct for BulkDeleteActionConnectionBody
type BulkDeleteActionConnectionBody struct {
	// The action to be performed on the entities.
	Action string `json:"action"`
	// A list of entity id/key or entity objects to be deleted.
	Entities []EntitiesInner1 `json:"entities"`
	ActionOnNonExistence *BulkActionNotOnExistence `json:"action_on_non_existence,omitempty"`
}

type _BulkDeleteActionConnectionBody BulkDeleteActionConnectionBody

// NewBulkDeleteActionConnectionBody instantiates a new BulkDeleteActionConnectionBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkDeleteActionConnectionBody(action string, entities []EntitiesInner1) *BulkDeleteActionConnectionBody {
	this := BulkDeleteActionConnectionBody{}
	this.Action = action
	this.Entities = entities
	var actionOnNonExistence BulkActionNotOnExistence = BULKACTIONNOTONEXISTENCE_FAIL
	this.ActionOnNonExistence = &actionOnNonExistence
	return &this
}

// NewBulkDeleteActionConnectionBodyWithDefaults instantiates a new BulkDeleteActionConnectionBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkDeleteActionConnectionBodyWithDefaults() *BulkDeleteActionConnectionBody {
	this := BulkDeleteActionConnectionBody{}
	var actionOnNonExistence BulkActionNotOnExistence = BULKACTIONNOTONEXISTENCE_FAIL
	this.ActionOnNonExistence = &actionOnNonExistence
	return &this
}

// GetAction returns the Action field value
func (o *BulkDeleteActionConnectionBody) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *BulkDeleteActionConnectionBody) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *BulkDeleteActionConnectionBody) SetAction(v string) {
	o.Action = v
}

// GetEntities returns the Entities field value
func (o *BulkDeleteActionConnectionBody) GetEntities() []EntitiesInner1 {
	if o == nil {
		var ret []EntitiesInner1
		return ret
	}

	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value
// and a boolean to check if the value has been set.
func (o *BulkDeleteActionConnectionBody) GetEntitiesOk() ([]EntitiesInner1, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entities, true
}

// SetEntities sets field value
func (o *BulkDeleteActionConnectionBody) SetEntities(v []EntitiesInner1) {
	o.Entities = v
}

// GetActionOnNonExistence returns the ActionOnNonExistence field value if set, zero value otherwise.
func (o *BulkDeleteActionConnectionBody) GetActionOnNonExistence() BulkActionNotOnExistence {
	if o == nil || IsNil(o.ActionOnNonExistence) {
		var ret BulkActionNotOnExistence
		return ret
	}
	return *o.ActionOnNonExistence
}

// GetActionOnNonExistenceOk returns a tuple with the ActionOnNonExistence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeleteActionConnectionBody) GetActionOnNonExistenceOk() (*BulkActionNotOnExistence, bool) {
	if o == nil || IsNil(o.ActionOnNonExistence) {
		return nil, false
	}
	return o.ActionOnNonExistence, true
}

// HasActionOnNonExistence returns a boolean if a field has been set.
func (o *BulkDeleteActionConnectionBody) HasActionOnNonExistence() bool {
	if o != nil && !IsNil(o.ActionOnNonExistence) {
		return true
	}

	return false
}

// SetActionOnNonExistence gets a reference to the given BulkActionNotOnExistence and assigns it to the ActionOnNonExistence field.
func (o *BulkDeleteActionConnectionBody) SetActionOnNonExistence(v BulkActionNotOnExistence) {
	o.ActionOnNonExistence = &v
}

func (o BulkDeleteActionConnectionBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkDeleteActionConnectionBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["entities"] = o.Entities
	if !IsNil(o.ActionOnNonExistence) {
		toSerialize["action_on_non_existence"] = o.ActionOnNonExistence
	}
	return toSerialize, nil
}

func (o *BulkDeleteActionConnectionBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"entities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkDeleteActionConnectionBody := _BulkDeleteActionConnectionBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkDeleteActionConnectionBody)

	if err != nil {
		return err
	}

	*o = BulkDeleteActionConnectionBody(varBulkDeleteActionConnectionBody)

	return err
}

type NullableBulkDeleteActionConnectionBody struct {
	value *BulkDeleteActionConnectionBody
	isSet bool
}

func (v NullableBulkDeleteActionConnectionBody) Get() *BulkDeleteActionConnectionBody {
	return v.value
}

func (v *NullableBulkDeleteActionConnectionBody) Set(val *BulkDeleteActionConnectionBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeleteActionConnectionBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeleteActionConnectionBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeleteActionConnectionBody(val *BulkDeleteActionConnectionBody) *NullableBulkDeleteActionConnectionBody {
	return &NullableBulkDeleteActionConnectionBody{value: val, isSet: true}
}

func (v NullableBulkDeleteActionConnectionBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeleteActionConnectionBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


