/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigSection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigSection{}

// ConfigSection Config Section Schema.
type ConfigSection struct {
	Name string `json:"name"`
	Options []ConfigOption `json:"options"`
}

type _ConfigSection ConfigSection

// NewConfigSection instantiates a new ConfigSection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigSection(name string, options []ConfigOption) *ConfigSection {
	this := ConfigSection{}
	this.Name = name
	this.Options = options
	return &this
}

// NewConfigSectionWithDefaults instantiates a new ConfigSection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigSectionWithDefaults() *ConfigSection {
	this := ConfigSection{}
	return &this
}

// GetName returns the Name field value
func (o *ConfigSection) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConfigSection) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConfigSection) SetName(v string) {
	o.Name = v
}

// GetOptions returns the Options field value
func (o *ConfigSection) GetOptions() []ConfigOption {
	if o == nil {
		var ret []ConfigOption
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *ConfigSection) GetOptionsOk() ([]ConfigOption, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options, true
}

// SetOptions sets field value
func (o *ConfigSection) SetOptions(v []ConfigOption) {
	o.Options = v
}

func (o ConfigSection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigSection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["options"] = o.Options
	return toSerialize, nil
}

func (o *ConfigSection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"options",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigSection := _ConfigSection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigSection)

	if err != nil {
		return err
	}

	*o = ConfigSection(varConfigSection)

	return err
}

type NullableConfigSection struct {
	value *ConfigSection
	isSet bool
}

func (v NullableConfigSection) Get() *ConfigSection {
	return v.value
}

func (v *NullableConfigSection) Set(val *ConfigSection) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigSection) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigSection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigSection(val *ConfigSection) *NullableConfigSection {
	return &NullableConfigSection{value: val, isSet: true}
}

func (v NullableConfigSection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigSection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


