/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DagStatsStateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DagStatsStateResponse{}

// DagStatsStateResponse DagStatsState serializer for responses.
type DagStatsStateResponse struct {
	State DagRunState `json:"state"`
	Count int32 `json:"count"`
}

type _DagStatsStateResponse DagStatsStateResponse

// NewDagStatsStateResponse instantiates a new DagStatsStateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDagStatsStateResponse(state DagRunState, count int32) *DagStatsStateResponse {
	this := DagStatsStateResponse{}
	this.State = state
	this.Count = count
	return &this
}

// NewDagStatsStateResponseWithDefaults instantiates a new DagStatsStateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDagStatsStateResponseWithDefaults() *DagStatsStateResponse {
	this := DagStatsStateResponse{}
	return &this
}

// GetState returns the State field value
func (o *DagStatsStateResponse) GetState() DagRunState {
	if o == nil {
		var ret DagRunState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *DagStatsStateResponse) GetStateOk() (*DagRunState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *DagStatsStateResponse) SetState(v DagRunState) {
	o.State = v
}

// GetCount returns the Count field value
func (o *DagStatsStateResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *DagStatsStateResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *DagStatsStateResponse) SetCount(v int32) {
	o.Count = v
}

func (o DagStatsStateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DagStatsStateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *DagStatsStateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDagStatsStateResponse := _DagStatsStateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDagStatsStateResponse)

	if err != nil {
		return err
	}

	*o = DagStatsStateResponse(varDagStatsStateResponse)

	return err
}

type NullableDagStatsStateResponse struct {
	value *DagStatsStateResponse
	isSet bool
}

func (v NullableDagStatsStateResponse) Get() *DagStatsStateResponse {
	return v.value
}

func (v *NullableDagStatsStateResponse) Set(val *DagStatsStateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDagStatsStateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDagStatsStateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDagStatsStateResponse(val *DagStatsStateResponse) *NullableDagStatsStateResponse {
	return &NullableDagStatsStateResponse{value: val, isSet: true}
}

func (v NullableDagStatsStateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDagStatsStateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


