/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkBodyBulkTaskInstanceBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkBodyBulkTaskInstanceBody{}

// BulkBodyBulkTaskInstanceBody struct for BulkBodyBulkTaskInstanceBody
type BulkBodyBulkTaskInstanceBody struct {
	Actions []ActionsInner `json:"actions"`
}

type _BulkBodyBulkTaskInstanceBody BulkBodyBulkTaskInstanceBody

// NewBulkBodyBulkTaskInstanceBody instantiates a new BulkBodyBulkTaskInstanceBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkBodyBulkTaskInstanceBody(actions []ActionsInner) *BulkBodyBulkTaskInstanceBody {
	this := BulkBodyBulkTaskInstanceBody{}
	this.Actions = actions
	return &this
}

// NewBulkBodyBulkTaskInstanceBodyWithDefaults instantiates a new BulkBodyBulkTaskInstanceBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkBodyBulkTaskInstanceBodyWithDefaults() *BulkBodyBulkTaskInstanceBody {
	this := BulkBodyBulkTaskInstanceBody{}
	return &this
}

// GetActions returns the Actions field value
func (o *BulkBodyBulkTaskInstanceBody) GetActions() []ActionsInner {
	if o == nil {
		var ret []ActionsInner
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *BulkBodyBulkTaskInstanceBody) GetActionsOk() ([]ActionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actions, true
}

// SetActions sets field value
func (o *BulkBodyBulkTaskInstanceBody) SetActions(v []ActionsInner) {
	o.Actions = v
}

func (o BulkBodyBulkTaskInstanceBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkBodyBulkTaskInstanceBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["actions"] = o.Actions
	return toSerialize, nil
}

func (o *BulkBodyBulkTaskInstanceBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"actions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkBodyBulkTaskInstanceBody := _BulkBodyBulkTaskInstanceBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkBodyBulkTaskInstanceBody)

	if err != nil {
		return err
	}

	*o = BulkBodyBulkTaskInstanceBody(varBulkBodyBulkTaskInstanceBody)

	return err
}

type NullableBulkBodyBulkTaskInstanceBody struct {
	value *BulkBodyBulkTaskInstanceBody
	isSet bool
}

func (v NullableBulkBodyBulkTaskInstanceBody) Get() *BulkBodyBulkTaskInstanceBody {
	return v.value
}

func (v *NullableBulkBodyBulkTaskInstanceBody) Set(val *BulkBodyBulkTaskInstanceBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkBodyBulkTaskInstanceBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkBodyBulkTaskInstanceBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkBodyBulkTaskInstanceBody(val *BulkBodyBulkTaskInstanceBody) *NullableBulkBodyBulkTaskInstanceBody {
	return &NullableBulkBodyBulkTaskInstanceBody{value: val, isSet: true}
}

func (v NullableBulkBodyBulkTaskInstanceBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkBodyBulkTaskInstanceBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


