/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkCreateActionPoolBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkCreateActionPoolBody{}

// BulkCreateActionPoolBody struct for BulkCreateActionPoolBody
type BulkCreateActionPoolBody struct {
	// The action to be performed on the entities.
	Action string `json:"action"`
	// A list of entities to be created.
	Entities []PoolBody `json:"entities"`
	ActionOnExistence *BulkActionOnExistence `json:"action_on_existence,omitempty"`
}

type _BulkCreateActionPoolBody BulkCreateActionPoolBody

// NewBulkCreateActionPoolBody instantiates a new BulkCreateActionPoolBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkCreateActionPoolBody(action string, entities []PoolBody) *BulkCreateActionPoolBody {
	this := BulkCreateActionPoolBody{}
	this.Action = action
	this.Entities = entities
	var actionOnExistence BulkActionOnExistence = FAIL
	this.ActionOnExistence = &actionOnExistence
	return &this
}

// NewBulkCreateActionPoolBodyWithDefaults instantiates a new BulkCreateActionPoolBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkCreateActionPoolBodyWithDefaults() *BulkCreateActionPoolBody {
	this := BulkCreateActionPoolBody{}
	var actionOnExistence BulkActionOnExistence = FAIL
	this.ActionOnExistence = &actionOnExistence
	return &this
}

// GetAction returns the Action field value
func (o *BulkCreateActionPoolBody) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *BulkCreateActionPoolBody) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *BulkCreateActionPoolBody) SetAction(v string) {
	o.Action = v
}

// GetEntities returns the Entities field value
func (o *BulkCreateActionPoolBody) GetEntities() []PoolBody {
	if o == nil {
		var ret []PoolBody
		return ret
	}

	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value
// and a boolean to check if the value has been set.
func (o *BulkCreateActionPoolBody) GetEntitiesOk() ([]PoolBody, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entities, true
}

// SetEntities sets field value
func (o *BulkCreateActionPoolBody) SetEntities(v []PoolBody) {
	o.Entities = v
}

// GetActionOnExistence returns the ActionOnExistence field value if set, zero value otherwise.
func (o *BulkCreateActionPoolBody) GetActionOnExistence() BulkActionOnExistence {
	if o == nil || IsNil(o.ActionOnExistence) {
		var ret BulkActionOnExistence
		return ret
	}
	return *o.ActionOnExistence
}

// GetActionOnExistenceOk returns a tuple with the ActionOnExistence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreateActionPoolBody) GetActionOnExistenceOk() (*BulkActionOnExistence, bool) {
	if o == nil || IsNil(o.ActionOnExistence) {
		return nil, false
	}
	return o.ActionOnExistence, true
}

// HasActionOnExistence returns a boolean if a field has been set.
func (o *BulkCreateActionPoolBody) HasActionOnExistence() bool {
	if o != nil && !IsNil(o.ActionOnExistence) {
		return true
	}

	return false
}

// SetActionOnExistence gets a reference to the given BulkActionOnExistence and assigns it to the ActionOnExistence field.
func (o *BulkCreateActionPoolBody) SetActionOnExistence(v BulkActionOnExistence) {
	o.ActionOnExistence = &v
}

func (o BulkCreateActionPoolBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkCreateActionPoolBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["entities"] = o.Entities
	if !IsNil(o.ActionOnExistence) {
		toSerialize["action_on_existence"] = o.ActionOnExistence
	}
	return toSerialize, nil
}

func (o *BulkCreateActionPoolBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"entities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkCreateActionPoolBody := _BulkCreateActionPoolBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkCreateActionPoolBody)

	if err != nil {
		return err
	}

	*o = BulkCreateActionPoolBody(varBulkCreateActionPoolBody)

	return err
}

type NullableBulkCreateActionPoolBody struct {
	value *BulkCreateActionPoolBody
	isSet bool
}

func (v NullableBulkCreateActionPoolBody) Get() *BulkCreateActionPoolBody {
	return v.value
}

func (v *NullableBulkCreateActionPoolBody) Set(val *BulkCreateActionPoolBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCreateActionPoolBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCreateActionPoolBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCreateActionPoolBody(val *BulkCreateActionPoolBody) *NullableBulkCreateActionPoolBody {
	return &NullableBulkCreateActionPoolBody{value: val, isSet: true}
}

func (v NullableBulkCreateActionPoolBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCreateActionPoolBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


