/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"fmt"
)

// checks if the ReactAppResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReactAppResponse{}

// ReactAppResponse Serializer for React App Plugin responses.
type ReactAppResponse struct {
	Name string `json:"name"`
	Icon *string `json:"icon,omitempty"`
	IconDarkMode *string `json:"icon_dark_mode,omitempty"`
	UrlRoute *string `json:"url_route,omitempty"`
	Category *string `json:"category,omitempty"`
	BundleUrl string `json:"bundle_url"`
	Destination *string `json:"destination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReactAppResponse ReactAppResponse

// NewReactAppResponse instantiates a new ReactAppResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReactAppResponse(name string, bundleUrl string) *ReactAppResponse {
	this := ReactAppResponse{}
	this.Name = name
	this.BundleUrl = bundleUrl
	var destination string = "nav"
	this.Destination = &destination
	return &this
}

// NewReactAppResponseWithDefaults instantiates a new ReactAppResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReactAppResponseWithDefaults() *ReactAppResponse {
	this := ReactAppResponse{}
	var destination string = "nav"
	this.Destination = &destination
	return &this
}

// GetName returns the Name field value
func (o *ReactAppResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ReactAppResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ReactAppResponse) SetName(v string) {
	o.Name = v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *ReactAppResponse) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReactAppResponse) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *ReactAppResponse) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *ReactAppResponse) SetIcon(v string) {
	o.Icon = &v
}

// GetIconDarkMode returns the IconDarkMode field value if set, zero value otherwise.
func (o *ReactAppResponse) GetIconDarkMode() string {
	if o == nil || IsNil(o.IconDarkMode) {
		var ret string
		return ret
	}
	return *o.IconDarkMode
}

// GetIconDarkModeOk returns a tuple with the IconDarkMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReactAppResponse) GetIconDarkModeOk() (*string, bool) {
	if o == nil || IsNil(o.IconDarkMode) {
		return nil, false
	}
	return o.IconDarkMode, true
}

// HasIconDarkMode returns a boolean if a field has been set.
func (o *ReactAppResponse) HasIconDarkMode() bool {
	if o != nil && !IsNil(o.IconDarkMode) {
		return true
	}

	return false
}

// SetIconDarkMode gets a reference to the given string and assigns it to the IconDarkMode field.
func (o *ReactAppResponse) SetIconDarkMode(v string) {
	o.IconDarkMode = &v
}

// GetUrlRoute returns the UrlRoute field value if set, zero value otherwise.
func (o *ReactAppResponse) GetUrlRoute() string {
	if o == nil || IsNil(o.UrlRoute) {
		var ret string
		return ret
	}
	return *o.UrlRoute
}

// GetUrlRouteOk returns a tuple with the UrlRoute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReactAppResponse) GetUrlRouteOk() (*string, bool) {
	if o == nil || IsNil(o.UrlRoute) {
		return nil, false
	}
	return o.UrlRoute, true
}

// HasUrlRoute returns a boolean if a field has been set.
func (o *ReactAppResponse) HasUrlRoute() bool {
	if o != nil && !IsNil(o.UrlRoute) {
		return true
	}

	return false
}

// SetUrlRoute gets a reference to the given string and assigns it to the UrlRoute field.
func (o *ReactAppResponse) SetUrlRoute(v string) {
	o.UrlRoute = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *ReactAppResponse) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReactAppResponse) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *ReactAppResponse) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *ReactAppResponse) SetCategory(v string) {
	o.Category = &v
}

// GetBundleUrl returns the BundleUrl field value
func (o *ReactAppResponse) GetBundleUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BundleUrl
}

// GetBundleUrlOk returns a tuple with the BundleUrl field value
// and a boolean to check if the value has been set.
func (o *ReactAppResponse) GetBundleUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BundleUrl, true
}

// SetBundleUrl sets field value
func (o *ReactAppResponse) SetBundleUrl(v string) {
	o.BundleUrl = v
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *ReactAppResponse) GetDestination() string {
	if o == nil || IsNil(o.Destination) {
		var ret string
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReactAppResponse) GetDestinationOk() (*string, bool) {
	if o == nil || IsNil(o.Destination) {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *ReactAppResponse) HasDestination() bool {
	if o != nil && !IsNil(o.Destination) {
		return true
	}

	return false
}

// SetDestination gets a reference to the given string and assigns it to the Destination field.
func (o *ReactAppResponse) SetDestination(v string) {
	o.Destination = &v
}

func (o ReactAppResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReactAppResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.IconDarkMode) {
		toSerialize["icon_dark_mode"] = o.IconDarkMode
	}
	if !IsNil(o.UrlRoute) {
		toSerialize["url_route"] = o.UrlRoute
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	toSerialize["bundle_url"] = o.BundleUrl
	if !IsNil(o.Destination) {
		toSerialize["destination"] = o.Destination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReactAppResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"bundle_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReactAppResponse := _ReactAppResponse{}

	err = json.Unmarshal(data, &varReactAppResponse)

	if err != nil {
		return err
	}

	*o = ReactAppResponse(varReactAppResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "icon")
		delete(additionalProperties, "icon_dark_mode")
		delete(additionalProperties, "url_route")
		delete(additionalProperties, "category")
		delete(additionalProperties, "bundle_url")
		delete(additionalProperties, "destination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReactAppResponse struct {
	value *ReactAppResponse
	isSet bool
}

func (v NullableReactAppResponse) Get() *ReactAppResponse {
	return v.value
}

func (v *NullableReactAppResponse) Set(val *ReactAppResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReactAppResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReactAppResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReactAppResponse(val *ReactAppResponse) *NullableReactAppResponse {
	return &NullableReactAppResponse{value: val, isSet: true}
}

func (v NullableReactAppResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReactAppResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


