/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DryRunBackfillResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DryRunBackfillResponse{}

// DryRunBackfillResponse Backfill serializer for responses in dry-run mode.
type DryRunBackfillResponse struct {
	LogicalDate time.Time `json:"logical_date"`
	PartitionKey string `json:"partition_key"`
	PartitionDate time.Time `json:"partition_date"`
}

type _DryRunBackfillResponse DryRunBackfillResponse

// NewDryRunBackfillResponse instantiates a new DryRunBackfillResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDryRunBackfillResponse(logicalDate time.Time, partitionKey string, partitionDate time.Time) *DryRunBackfillResponse {
	this := DryRunBackfillResponse{}
	this.LogicalDate = logicalDate
	this.PartitionKey = partitionKey
	this.PartitionDate = partitionDate
	return &this
}

// NewDryRunBackfillResponseWithDefaults instantiates a new DryRunBackfillResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDryRunBackfillResponseWithDefaults() *DryRunBackfillResponse {
	this := DryRunBackfillResponse{}
	return &this
}

// GetLogicalDate returns the LogicalDate field value
func (o *DryRunBackfillResponse) GetLogicalDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LogicalDate
}

// GetLogicalDateOk returns a tuple with the LogicalDate field value
// and a boolean to check if the value has been set.
func (o *DryRunBackfillResponse) GetLogicalDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogicalDate, true
}

// SetLogicalDate sets field value
func (o *DryRunBackfillResponse) SetLogicalDate(v time.Time) {
	o.LogicalDate = v
}

// GetPartitionKey returns the PartitionKey field value
func (o *DryRunBackfillResponse) GetPartitionKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartitionKey
}

// GetPartitionKeyOk returns a tuple with the PartitionKey field value
// and a boolean to check if the value has been set.
func (o *DryRunBackfillResponse) GetPartitionKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartitionKey, true
}

// SetPartitionKey sets field value
func (o *DryRunBackfillResponse) SetPartitionKey(v string) {
	o.PartitionKey = v
}

// GetPartitionDate returns the PartitionDate field value
func (o *DryRunBackfillResponse) GetPartitionDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.PartitionDate
}

// GetPartitionDateOk returns a tuple with the PartitionDate field value
// and a boolean to check if the value has been set.
func (o *DryRunBackfillResponse) GetPartitionDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartitionDate, true
}

// SetPartitionDate sets field value
func (o *DryRunBackfillResponse) SetPartitionDate(v time.Time) {
	o.PartitionDate = v
}

func (o DryRunBackfillResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DryRunBackfillResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["logical_date"] = o.LogicalDate
	toSerialize["partition_key"] = o.PartitionKey
	toSerialize["partition_date"] = o.PartitionDate
	return toSerialize, nil
}

func (o *DryRunBackfillResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"logical_date",
		"partition_key",
		"partition_date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDryRunBackfillResponse := _DryRunBackfillResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDryRunBackfillResponse)

	if err != nil {
		return err
	}

	*o = DryRunBackfillResponse(varDryRunBackfillResponse)

	return err
}

type NullableDryRunBackfillResponse struct {
	value *DryRunBackfillResponse
	isSet bool
}

func (v NullableDryRunBackfillResponse) Get() *DryRunBackfillResponse {
	return v.value
}

func (v *NullableDryRunBackfillResponse) Set(val *DryRunBackfillResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDryRunBackfillResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDryRunBackfillResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDryRunBackfillResponse(val *DryRunBackfillResponse) *NullableDryRunBackfillResponse {
	return &NullableDryRunBackfillResponse{value: val, isSet: true}
}

func (v NullableDryRunBackfillResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDryRunBackfillResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


