/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TriggerDAGRunPostBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TriggerDAGRunPostBody{}

// TriggerDAGRunPostBody Trigger Dag Run Serializer for POST body.
type TriggerDAGRunPostBody struct {
	DagRunId NullableString `json:"dag_run_id,omitempty"`
	DataIntervalStart NullableTime `json:"data_interval_start,omitempty"`
	DataIntervalEnd NullableTime `json:"data_interval_end,omitempty"`
	LogicalDate NullableTime `json:"logical_date"`
	RunAfter NullableTime `json:"run_after,omitempty"`
	Conf map[string]interface{} `json:"conf,omitempty"`
	Note NullableString `json:"note,omitempty"`
	PartitionKey NullableString `json:"partition_key,omitempty"`
}

type _TriggerDAGRunPostBody TriggerDAGRunPostBody

// NewTriggerDAGRunPostBody instantiates a new TriggerDAGRunPostBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTriggerDAGRunPostBody(logicalDate NullableTime) *TriggerDAGRunPostBody {
	this := TriggerDAGRunPostBody{}
	this.LogicalDate = logicalDate
	return &this
}

// NewTriggerDAGRunPostBodyWithDefaults instantiates a new TriggerDAGRunPostBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTriggerDAGRunPostBodyWithDefaults() *TriggerDAGRunPostBody {
	this := TriggerDAGRunPostBody{}
	return &this
}

// GetDagRunId returns the DagRunId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TriggerDAGRunPostBody) GetDagRunId() string {
	if o == nil || IsNil(o.DagRunId.Get()) {
		var ret string
		return ret
	}
	return *o.DagRunId.Get()
}

// GetDagRunIdOk returns a tuple with the DagRunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TriggerDAGRunPostBody) GetDagRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DagRunId.Get(), o.DagRunId.IsSet()
}

// HasDagRunId returns a boolean if a field has been set.
func (o *TriggerDAGRunPostBody) HasDagRunId() bool {
	if o != nil && o.DagRunId.IsSet() {
		return true
	}

	return false
}

// SetDagRunId gets a reference to the given NullableString and assigns it to the DagRunId field.
func (o *TriggerDAGRunPostBody) SetDagRunId(v string) {
	o.DagRunId.Set(&v)
}
// SetDagRunIdNil sets the value for DagRunId to be an explicit nil
func (o *TriggerDAGRunPostBody) SetDagRunIdNil() {
	o.DagRunId.Set(nil)
}

// UnsetDagRunId ensures that no value is present for DagRunId, not even an explicit nil
func (o *TriggerDAGRunPostBody) UnsetDagRunId() {
	o.DagRunId.Unset()
}

// GetDataIntervalStart returns the DataIntervalStart field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TriggerDAGRunPostBody) GetDataIntervalStart() time.Time {
	if o == nil || IsNil(o.DataIntervalStart.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DataIntervalStart.Get()
}

// GetDataIntervalStartOk returns a tuple with the DataIntervalStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TriggerDAGRunPostBody) GetDataIntervalStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataIntervalStart.Get(), o.DataIntervalStart.IsSet()
}

// HasDataIntervalStart returns a boolean if a field has been set.
func (o *TriggerDAGRunPostBody) HasDataIntervalStart() bool {
	if o != nil && o.DataIntervalStart.IsSet() {
		return true
	}

	return false
}

// SetDataIntervalStart gets a reference to the given NullableTime and assigns it to the DataIntervalStart field.
func (o *TriggerDAGRunPostBody) SetDataIntervalStart(v time.Time) {
	o.DataIntervalStart.Set(&v)
}
// SetDataIntervalStartNil sets the value for DataIntervalStart to be an explicit nil
func (o *TriggerDAGRunPostBody) SetDataIntervalStartNil() {
	o.DataIntervalStart.Set(nil)
}

// UnsetDataIntervalStart ensures that no value is present for DataIntervalStart, not even an explicit nil
func (o *TriggerDAGRunPostBody) UnsetDataIntervalStart() {
	o.DataIntervalStart.Unset()
}

// GetDataIntervalEnd returns the DataIntervalEnd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TriggerDAGRunPostBody) GetDataIntervalEnd() time.Time {
	if o == nil || IsNil(o.DataIntervalEnd.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DataIntervalEnd.Get()
}

// GetDataIntervalEndOk returns a tuple with the DataIntervalEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TriggerDAGRunPostBody) GetDataIntervalEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataIntervalEnd.Get(), o.DataIntervalEnd.IsSet()
}

// HasDataIntervalEnd returns a boolean if a field has been set.
func (o *TriggerDAGRunPostBody) HasDataIntervalEnd() bool {
	if o != nil && o.DataIntervalEnd.IsSet() {
		return true
	}

	return false
}

// SetDataIntervalEnd gets a reference to the given NullableTime and assigns it to the DataIntervalEnd field.
func (o *TriggerDAGRunPostBody) SetDataIntervalEnd(v time.Time) {
	o.DataIntervalEnd.Set(&v)
}
// SetDataIntervalEndNil sets the value for DataIntervalEnd to be an explicit nil
func (o *TriggerDAGRunPostBody) SetDataIntervalEndNil() {
	o.DataIntervalEnd.Set(nil)
}

// UnsetDataIntervalEnd ensures that no value is present for DataIntervalEnd, not even an explicit nil
func (o *TriggerDAGRunPostBody) UnsetDataIntervalEnd() {
	o.DataIntervalEnd.Unset()
}

// GetLogicalDate returns the LogicalDate field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *TriggerDAGRunPostBody) GetLogicalDate() time.Time {
	if o == nil || o.LogicalDate.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LogicalDate.Get()
}

// GetLogicalDateOk returns a tuple with the LogicalDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TriggerDAGRunPostBody) GetLogicalDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogicalDate.Get(), o.LogicalDate.IsSet()
}

// SetLogicalDate sets field value
func (o *TriggerDAGRunPostBody) SetLogicalDate(v time.Time) {
	o.LogicalDate.Set(&v)
}

// GetRunAfter returns the RunAfter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TriggerDAGRunPostBody) GetRunAfter() time.Time {
	if o == nil || IsNil(o.RunAfter.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RunAfter.Get()
}

// GetRunAfterOk returns a tuple with the RunAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TriggerDAGRunPostBody) GetRunAfterOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RunAfter.Get(), o.RunAfter.IsSet()
}

// HasRunAfter returns a boolean if a field has been set.
func (o *TriggerDAGRunPostBody) HasRunAfter() bool {
	if o != nil && o.RunAfter.IsSet() {
		return true
	}

	return false
}

// SetRunAfter gets a reference to the given NullableTime and assigns it to the RunAfter field.
func (o *TriggerDAGRunPostBody) SetRunAfter(v time.Time) {
	o.RunAfter.Set(&v)
}
// SetRunAfterNil sets the value for RunAfter to be an explicit nil
func (o *TriggerDAGRunPostBody) SetRunAfterNil() {
	o.RunAfter.Set(nil)
}

// UnsetRunAfter ensures that no value is present for RunAfter, not even an explicit nil
func (o *TriggerDAGRunPostBody) UnsetRunAfter() {
	o.RunAfter.Unset()
}

// GetConf returns the Conf field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TriggerDAGRunPostBody) GetConf() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Conf
}

// GetConfOk returns a tuple with the Conf field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TriggerDAGRunPostBody) GetConfOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Conf) {
		return map[string]interface{}{}, false
	}
	return o.Conf, true
}

// HasConf returns a boolean if a field has been set.
func (o *TriggerDAGRunPostBody) HasConf() bool {
	if o != nil && !IsNil(o.Conf) {
		return true
	}

	return false
}

// SetConf gets a reference to the given map[string]interface{} and assigns it to the Conf field.
func (o *TriggerDAGRunPostBody) SetConf(v map[string]interface{}) {
	o.Conf = v
}

// GetNote returns the Note field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TriggerDAGRunPostBody) GetNote() string {
	if o == nil || IsNil(o.Note.Get()) {
		var ret string
		return ret
	}
	return *o.Note.Get()
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TriggerDAGRunPostBody) GetNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Note.Get(), o.Note.IsSet()
}

// HasNote returns a boolean if a field has been set.
func (o *TriggerDAGRunPostBody) HasNote() bool {
	if o != nil && o.Note.IsSet() {
		return true
	}

	return false
}

// SetNote gets a reference to the given NullableString and assigns it to the Note field.
func (o *TriggerDAGRunPostBody) SetNote(v string) {
	o.Note.Set(&v)
}
// SetNoteNil sets the value for Note to be an explicit nil
func (o *TriggerDAGRunPostBody) SetNoteNil() {
	o.Note.Set(nil)
}

// UnsetNote ensures that no value is present for Note, not even an explicit nil
func (o *TriggerDAGRunPostBody) UnsetNote() {
	o.Note.Unset()
}

// GetPartitionKey returns the PartitionKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TriggerDAGRunPostBody) GetPartitionKey() string {
	if o == nil || IsNil(o.PartitionKey.Get()) {
		var ret string
		return ret
	}
	return *o.PartitionKey.Get()
}

// GetPartitionKeyOk returns a tuple with the PartitionKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TriggerDAGRunPostBody) GetPartitionKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PartitionKey.Get(), o.PartitionKey.IsSet()
}

// HasPartitionKey returns a boolean if a field has been set.
func (o *TriggerDAGRunPostBody) HasPartitionKey() bool {
	if o != nil && o.PartitionKey.IsSet() {
		return true
	}

	return false
}

// SetPartitionKey gets a reference to the given NullableString and assigns it to the PartitionKey field.
func (o *TriggerDAGRunPostBody) SetPartitionKey(v string) {
	o.PartitionKey.Set(&v)
}
// SetPartitionKeyNil sets the value for PartitionKey to be an explicit nil
func (o *TriggerDAGRunPostBody) SetPartitionKeyNil() {
	o.PartitionKey.Set(nil)
}

// UnsetPartitionKey ensures that no value is present for PartitionKey, not even an explicit nil
func (o *TriggerDAGRunPostBody) UnsetPartitionKey() {
	o.PartitionKey.Unset()
}

func (o TriggerDAGRunPostBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TriggerDAGRunPostBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DagRunId.IsSet() {
		toSerialize["dag_run_id"] = o.DagRunId.Get()
	}
	if o.DataIntervalStart.IsSet() {
		toSerialize["data_interval_start"] = o.DataIntervalStart.Get()
	}
	if o.DataIntervalEnd.IsSet() {
		toSerialize["data_interval_end"] = o.DataIntervalEnd.Get()
	}
	toSerialize["logical_date"] = o.LogicalDate.Get()
	if o.RunAfter.IsSet() {
		toSerialize["run_after"] = o.RunAfter.Get()
	}
	if o.Conf != nil {
		toSerialize["conf"] = o.Conf
	}
	if o.Note.IsSet() {
		toSerialize["note"] = o.Note.Get()
	}
	if o.PartitionKey.IsSet() {
		toSerialize["partition_key"] = o.PartitionKey.Get()
	}
	return toSerialize, nil
}

func (o *TriggerDAGRunPostBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"logical_date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTriggerDAGRunPostBody := _TriggerDAGRunPostBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTriggerDAGRunPostBody)

	if err != nil {
		return err
	}

	*o = TriggerDAGRunPostBody(varTriggerDAGRunPostBody)

	return err
}

type NullableTriggerDAGRunPostBody struct {
	value *TriggerDAGRunPostBody
	isSet bool
}

func (v NullableTriggerDAGRunPostBody) Get() *TriggerDAGRunPostBody {
	return v.value
}

func (v *NullableTriggerDAGRunPostBody) Set(val *TriggerDAGRunPostBody) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerDAGRunPostBody) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerDAGRunPostBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTriggerDAGRunPostBody(val *TriggerDAGRunPostBody) *NullableTriggerDAGRunPostBody {
	return &NullableTriggerDAGRunPostBody{value: val, isSet: true}
}

func (v NullableTriggerDAGRunPostBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerDAGRunPostBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


