/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"time"
)

// checks if the DAGRunsBatchBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DAGRunsBatchBody{}

// DAGRunsBatchBody List Dag Runs body for batch endpoint.
type DAGRunsBatchBody struct {
	OrderBy NullableString `json:"order_by,omitempty"`
	PageOffset *int32 `json:"page_offset,omitempty"`
	PageLimit *int32 `json:"page_limit,omitempty"`
	DagIds []string `json:"dag_ids,omitempty"`
	States []*DagRunState `json:"states,omitempty"`
	RunAfterGte NullableTime `json:"run_after_gte,omitempty"`
	RunAfterGt NullableTime `json:"run_after_gt,omitempty"`
	RunAfterLte NullableTime `json:"run_after_lte,omitempty"`
	RunAfterLt NullableTime `json:"run_after_lt,omitempty"`
	LogicalDateGte NullableTime `json:"logical_date_gte,omitempty"`
	LogicalDateGt NullableTime `json:"logical_date_gt,omitempty"`
	LogicalDateLte NullableTime `json:"logical_date_lte,omitempty"`
	LogicalDateLt NullableTime `json:"logical_date_lt,omitempty"`
	StartDateGte NullableTime `json:"start_date_gte,omitempty"`
	StartDateGt NullableTime `json:"start_date_gt,omitempty"`
	StartDateLte NullableTime `json:"start_date_lte,omitempty"`
	StartDateLt NullableTime `json:"start_date_lt,omitempty"`
	EndDateGte NullableTime `json:"end_date_gte,omitempty"`
	EndDateGt NullableTime `json:"end_date_gt,omitempty"`
	EndDateLte NullableTime `json:"end_date_lte,omitempty"`
	EndDateLt NullableTime `json:"end_date_lt,omitempty"`
	DurationGte NullableFloat32 `json:"duration_gte,omitempty"`
	DurationGt NullableFloat32 `json:"duration_gt,omitempty"`
	DurationLte NullableFloat32 `json:"duration_lte,omitempty"`
	DurationLt NullableFloat32 `json:"duration_lt,omitempty"`
	ConfContains NullableString `json:"conf_contains,omitempty"`
}

// NewDAGRunsBatchBody instantiates a new DAGRunsBatchBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDAGRunsBatchBody() *DAGRunsBatchBody {
	this := DAGRunsBatchBody{}
	var pageOffset int32 = 0
	this.PageOffset = &pageOffset
	var pageLimit int32 = 100
	this.PageLimit = &pageLimit
	return &this
}

// NewDAGRunsBatchBodyWithDefaults instantiates a new DAGRunsBatchBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDAGRunsBatchBodyWithDefaults() *DAGRunsBatchBody {
	this := DAGRunsBatchBody{}
	var pageOffset int32 = 0
	this.PageOffset = &pageOffset
	var pageLimit int32 = 100
	this.PageLimit = &pageLimit
	return &this
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetOrderBy() string {
	if o == nil || IsNil(o.OrderBy.Get()) {
		var ret string
		return ret
	}
	return *o.OrderBy.Get()
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetOrderByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderBy.Get(), o.OrderBy.IsSet()
}

// HasOrderBy returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasOrderBy() bool {
	if o != nil && o.OrderBy.IsSet() {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given NullableString and assigns it to the OrderBy field.
func (o *DAGRunsBatchBody) SetOrderBy(v string) {
	o.OrderBy.Set(&v)
}
// SetOrderByNil sets the value for OrderBy to be an explicit nil
func (o *DAGRunsBatchBody) SetOrderByNil() {
	o.OrderBy.Set(nil)
}

// UnsetOrderBy ensures that no value is present for OrderBy, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetOrderBy() {
	o.OrderBy.Unset()
}

// GetPageOffset returns the PageOffset field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetPageOffset() int32 {
	if o == nil || IsNil(o.PageOffset) {
		var ret int32
		return ret
	}
	return *o.PageOffset
}

// GetPageOffsetOk returns a tuple with the PageOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetPageOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.PageOffset) {
		return nil, false
	}
	return o.PageOffset, true
}

// HasPageOffset returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasPageOffset() bool {
	if o != nil && !IsNil(o.PageOffset) {
		return true
	}

	return false
}

// SetPageOffset gets a reference to the given int32 and assigns it to the PageOffset field.
func (o *DAGRunsBatchBody) SetPageOffset(v int32) {
	o.PageOffset = &v
}

// GetPageLimit returns the PageLimit field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetPageLimit() int32 {
	if o == nil || IsNil(o.PageLimit) {
		var ret int32
		return ret
	}
	return *o.PageLimit
}

// GetPageLimitOk returns a tuple with the PageLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetPageLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.PageLimit) {
		return nil, false
	}
	return o.PageLimit, true
}

// HasPageLimit returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasPageLimit() bool {
	if o != nil && !IsNil(o.PageLimit) {
		return true
	}

	return false
}

// SetPageLimit gets a reference to the given int32 and assigns it to the PageLimit field.
func (o *DAGRunsBatchBody) SetPageLimit(v int32) {
	o.PageLimit = &v
}

// GetDagIds returns the DagIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetDagIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.DagIds
}

// GetDagIdsOk returns a tuple with the DagIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetDagIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DagIds) {
		return nil, false
	}
	return o.DagIds, true
}

// HasDagIds returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasDagIds() bool {
	if o != nil && !IsNil(o.DagIds) {
		return true
	}

	return false
}

// SetDagIds gets a reference to the given []string and assigns it to the DagIds field.
func (o *DAGRunsBatchBody) SetDagIds(v []string) {
	o.DagIds = v
}

// GetStates returns the States field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetStates() []*DagRunState {
	if o == nil {
		var ret []*DagRunState
		return ret
	}
	return o.States
}

// GetStatesOk returns a tuple with the States field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetStatesOk() ([]*DagRunState, bool) {
	if o == nil || IsNil(o.States) {
		return nil, false
	}
	return o.States, true
}

// HasStates returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStates() bool {
	if o != nil && !IsNil(o.States) {
		return true
	}

	return false
}

// SetStates gets a reference to the given []*DagRunState and assigns it to the States field.
func (o *DAGRunsBatchBody) SetStates(v []*DagRunState) {
	o.States = v
}

// GetRunAfterGte returns the RunAfterGte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetRunAfterGte() time.Time {
	if o == nil || IsNil(o.RunAfterGte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RunAfterGte.Get()
}

// GetRunAfterGteOk returns a tuple with the RunAfterGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetRunAfterGteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RunAfterGte.Get(), o.RunAfterGte.IsSet()
}

// HasRunAfterGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasRunAfterGte() bool {
	if o != nil && o.RunAfterGte.IsSet() {
		return true
	}

	return false
}

// SetRunAfterGte gets a reference to the given NullableTime and assigns it to the RunAfterGte field.
func (o *DAGRunsBatchBody) SetRunAfterGte(v time.Time) {
	o.RunAfterGte.Set(&v)
}
// SetRunAfterGteNil sets the value for RunAfterGte to be an explicit nil
func (o *DAGRunsBatchBody) SetRunAfterGteNil() {
	o.RunAfterGte.Set(nil)
}

// UnsetRunAfterGte ensures that no value is present for RunAfterGte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetRunAfterGte() {
	o.RunAfterGte.Unset()
}

// GetRunAfterGt returns the RunAfterGt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetRunAfterGt() time.Time {
	if o == nil || IsNil(o.RunAfterGt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RunAfterGt.Get()
}

// GetRunAfterGtOk returns a tuple with the RunAfterGt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetRunAfterGtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RunAfterGt.Get(), o.RunAfterGt.IsSet()
}

// HasRunAfterGt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasRunAfterGt() bool {
	if o != nil && o.RunAfterGt.IsSet() {
		return true
	}

	return false
}

// SetRunAfterGt gets a reference to the given NullableTime and assigns it to the RunAfterGt field.
func (o *DAGRunsBatchBody) SetRunAfterGt(v time.Time) {
	o.RunAfterGt.Set(&v)
}
// SetRunAfterGtNil sets the value for RunAfterGt to be an explicit nil
func (o *DAGRunsBatchBody) SetRunAfterGtNil() {
	o.RunAfterGt.Set(nil)
}

// UnsetRunAfterGt ensures that no value is present for RunAfterGt, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetRunAfterGt() {
	o.RunAfterGt.Unset()
}

// GetRunAfterLte returns the RunAfterLte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetRunAfterLte() time.Time {
	if o == nil || IsNil(o.RunAfterLte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RunAfterLte.Get()
}

// GetRunAfterLteOk returns a tuple with the RunAfterLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetRunAfterLteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RunAfterLte.Get(), o.RunAfterLte.IsSet()
}

// HasRunAfterLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasRunAfterLte() bool {
	if o != nil && o.RunAfterLte.IsSet() {
		return true
	}

	return false
}

// SetRunAfterLte gets a reference to the given NullableTime and assigns it to the RunAfterLte field.
func (o *DAGRunsBatchBody) SetRunAfterLte(v time.Time) {
	o.RunAfterLte.Set(&v)
}
// SetRunAfterLteNil sets the value for RunAfterLte to be an explicit nil
func (o *DAGRunsBatchBody) SetRunAfterLteNil() {
	o.RunAfterLte.Set(nil)
}

// UnsetRunAfterLte ensures that no value is present for RunAfterLte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetRunAfterLte() {
	o.RunAfterLte.Unset()
}

// GetRunAfterLt returns the RunAfterLt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetRunAfterLt() time.Time {
	if o == nil || IsNil(o.RunAfterLt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RunAfterLt.Get()
}

// GetRunAfterLtOk returns a tuple with the RunAfterLt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetRunAfterLtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RunAfterLt.Get(), o.RunAfterLt.IsSet()
}

// HasRunAfterLt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasRunAfterLt() bool {
	if o != nil && o.RunAfterLt.IsSet() {
		return true
	}

	return false
}

// SetRunAfterLt gets a reference to the given NullableTime and assigns it to the RunAfterLt field.
func (o *DAGRunsBatchBody) SetRunAfterLt(v time.Time) {
	o.RunAfterLt.Set(&v)
}
// SetRunAfterLtNil sets the value for RunAfterLt to be an explicit nil
func (o *DAGRunsBatchBody) SetRunAfterLtNil() {
	o.RunAfterLt.Set(nil)
}

// UnsetRunAfterLt ensures that no value is present for RunAfterLt, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetRunAfterLt() {
	o.RunAfterLt.Unset()
}

// GetLogicalDateGte returns the LogicalDateGte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetLogicalDateGte() time.Time {
	if o == nil || IsNil(o.LogicalDateGte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LogicalDateGte.Get()
}

// GetLogicalDateGteOk returns a tuple with the LogicalDateGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetLogicalDateGteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogicalDateGte.Get(), o.LogicalDateGte.IsSet()
}

// HasLogicalDateGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasLogicalDateGte() bool {
	if o != nil && o.LogicalDateGte.IsSet() {
		return true
	}

	return false
}

// SetLogicalDateGte gets a reference to the given NullableTime and assigns it to the LogicalDateGte field.
func (o *DAGRunsBatchBody) SetLogicalDateGte(v time.Time) {
	o.LogicalDateGte.Set(&v)
}
// SetLogicalDateGteNil sets the value for LogicalDateGte to be an explicit nil
func (o *DAGRunsBatchBody) SetLogicalDateGteNil() {
	o.LogicalDateGte.Set(nil)
}

// UnsetLogicalDateGte ensures that no value is present for LogicalDateGte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetLogicalDateGte() {
	o.LogicalDateGte.Unset()
}

// GetLogicalDateGt returns the LogicalDateGt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetLogicalDateGt() time.Time {
	if o == nil || IsNil(o.LogicalDateGt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LogicalDateGt.Get()
}

// GetLogicalDateGtOk returns a tuple with the LogicalDateGt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetLogicalDateGtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogicalDateGt.Get(), o.LogicalDateGt.IsSet()
}

// HasLogicalDateGt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasLogicalDateGt() bool {
	if o != nil && o.LogicalDateGt.IsSet() {
		return true
	}

	return false
}

// SetLogicalDateGt gets a reference to the given NullableTime and assigns it to the LogicalDateGt field.
func (o *DAGRunsBatchBody) SetLogicalDateGt(v time.Time) {
	o.LogicalDateGt.Set(&v)
}
// SetLogicalDateGtNil sets the value for LogicalDateGt to be an explicit nil
func (o *DAGRunsBatchBody) SetLogicalDateGtNil() {
	o.LogicalDateGt.Set(nil)
}

// UnsetLogicalDateGt ensures that no value is present for LogicalDateGt, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetLogicalDateGt() {
	o.LogicalDateGt.Unset()
}

// GetLogicalDateLte returns the LogicalDateLte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetLogicalDateLte() time.Time {
	if o == nil || IsNil(o.LogicalDateLte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LogicalDateLte.Get()
}

// GetLogicalDateLteOk returns a tuple with the LogicalDateLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetLogicalDateLteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogicalDateLte.Get(), o.LogicalDateLte.IsSet()
}

// HasLogicalDateLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasLogicalDateLte() bool {
	if o != nil && o.LogicalDateLte.IsSet() {
		return true
	}

	return false
}

// SetLogicalDateLte gets a reference to the given NullableTime and assigns it to the LogicalDateLte field.
func (o *DAGRunsBatchBody) SetLogicalDateLte(v time.Time) {
	o.LogicalDateLte.Set(&v)
}
// SetLogicalDateLteNil sets the value for LogicalDateLte to be an explicit nil
func (o *DAGRunsBatchBody) SetLogicalDateLteNil() {
	o.LogicalDateLte.Set(nil)
}

// UnsetLogicalDateLte ensures that no value is present for LogicalDateLte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetLogicalDateLte() {
	o.LogicalDateLte.Unset()
}

// GetLogicalDateLt returns the LogicalDateLt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetLogicalDateLt() time.Time {
	if o == nil || IsNil(o.LogicalDateLt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LogicalDateLt.Get()
}

// GetLogicalDateLtOk returns a tuple with the LogicalDateLt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetLogicalDateLtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogicalDateLt.Get(), o.LogicalDateLt.IsSet()
}

// HasLogicalDateLt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasLogicalDateLt() bool {
	if o != nil && o.LogicalDateLt.IsSet() {
		return true
	}

	return false
}

// SetLogicalDateLt gets a reference to the given NullableTime and assigns it to the LogicalDateLt field.
func (o *DAGRunsBatchBody) SetLogicalDateLt(v time.Time) {
	o.LogicalDateLt.Set(&v)
}
// SetLogicalDateLtNil sets the value for LogicalDateLt to be an explicit nil
func (o *DAGRunsBatchBody) SetLogicalDateLtNil() {
	o.LogicalDateLt.Set(nil)
}

// UnsetLogicalDateLt ensures that no value is present for LogicalDateLt, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetLogicalDateLt() {
	o.LogicalDateLt.Unset()
}

// GetStartDateGte returns the StartDateGte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetStartDateGte() time.Time {
	if o == nil || IsNil(o.StartDateGte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartDateGte.Get()
}

// GetStartDateGteOk returns a tuple with the StartDateGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetStartDateGteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDateGte.Get(), o.StartDateGte.IsSet()
}

// HasStartDateGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStartDateGte() bool {
	if o != nil && o.StartDateGte.IsSet() {
		return true
	}

	return false
}

// SetStartDateGte gets a reference to the given NullableTime and assigns it to the StartDateGte field.
func (o *DAGRunsBatchBody) SetStartDateGte(v time.Time) {
	o.StartDateGte.Set(&v)
}
// SetStartDateGteNil sets the value for StartDateGte to be an explicit nil
func (o *DAGRunsBatchBody) SetStartDateGteNil() {
	o.StartDateGte.Set(nil)
}

// UnsetStartDateGte ensures that no value is present for StartDateGte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetStartDateGte() {
	o.StartDateGte.Unset()
}

// GetStartDateGt returns the StartDateGt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetStartDateGt() time.Time {
	if o == nil || IsNil(o.StartDateGt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartDateGt.Get()
}

// GetStartDateGtOk returns a tuple with the StartDateGt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetStartDateGtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDateGt.Get(), o.StartDateGt.IsSet()
}

// HasStartDateGt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStartDateGt() bool {
	if o != nil && o.StartDateGt.IsSet() {
		return true
	}

	return false
}

// SetStartDateGt gets a reference to the given NullableTime and assigns it to the StartDateGt field.
func (o *DAGRunsBatchBody) SetStartDateGt(v time.Time) {
	o.StartDateGt.Set(&v)
}
// SetStartDateGtNil sets the value for StartDateGt to be an explicit nil
func (o *DAGRunsBatchBody) SetStartDateGtNil() {
	o.StartDateGt.Set(nil)
}

// UnsetStartDateGt ensures that no value is present for StartDateGt, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetStartDateGt() {
	o.StartDateGt.Unset()
}

// GetStartDateLte returns the StartDateLte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetStartDateLte() time.Time {
	if o == nil || IsNil(o.StartDateLte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartDateLte.Get()
}

// GetStartDateLteOk returns a tuple with the StartDateLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetStartDateLteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDateLte.Get(), o.StartDateLte.IsSet()
}

// HasStartDateLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStartDateLte() bool {
	if o != nil && o.StartDateLte.IsSet() {
		return true
	}

	return false
}

// SetStartDateLte gets a reference to the given NullableTime and assigns it to the StartDateLte field.
func (o *DAGRunsBatchBody) SetStartDateLte(v time.Time) {
	o.StartDateLte.Set(&v)
}
// SetStartDateLteNil sets the value for StartDateLte to be an explicit nil
func (o *DAGRunsBatchBody) SetStartDateLteNil() {
	o.StartDateLte.Set(nil)
}

// UnsetStartDateLte ensures that no value is present for StartDateLte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetStartDateLte() {
	o.StartDateLte.Unset()
}

// GetStartDateLt returns the StartDateLt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetStartDateLt() time.Time {
	if o == nil || IsNil(o.StartDateLt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartDateLt.Get()
}

// GetStartDateLtOk returns a tuple with the StartDateLt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetStartDateLtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDateLt.Get(), o.StartDateLt.IsSet()
}

// HasStartDateLt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStartDateLt() bool {
	if o != nil && o.StartDateLt.IsSet() {
		return true
	}

	return false
}

// SetStartDateLt gets a reference to the given NullableTime and assigns it to the StartDateLt field.
func (o *DAGRunsBatchBody) SetStartDateLt(v time.Time) {
	o.StartDateLt.Set(&v)
}
// SetStartDateLtNil sets the value for StartDateLt to be an explicit nil
func (o *DAGRunsBatchBody) SetStartDateLtNil() {
	o.StartDateLt.Set(nil)
}

// UnsetStartDateLt ensures that no value is present for StartDateLt, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetStartDateLt() {
	o.StartDateLt.Unset()
}

// GetEndDateGte returns the EndDateGte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetEndDateGte() time.Time {
	if o == nil || IsNil(o.EndDateGte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndDateGte.Get()
}

// GetEndDateGteOk returns a tuple with the EndDateGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetEndDateGteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDateGte.Get(), o.EndDateGte.IsSet()
}

// HasEndDateGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasEndDateGte() bool {
	if o != nil && o.EndDateGte.IsSet() {
		return true
	}

	return false
}

// SetEndDateGte gets a reference to the given NullableTime and assigns it to the EndDateGte field.
func (o *DAGRunsBatchBody) SetEndDateGte(v time.Time) {
	o.EndDateGte.Set(&v)
}
// SetEndDateGteNil sets the value for EndDateGte to be an explicit nil
func (o *DAGRunsBatchBody) SetEndDateGteNil() {
	o.EndDateGte.Set(nil)
}

// UnsetEndDateGte ensures that no value is present for EndDateGte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetEndDateGte() {
	o.EndDateGte.Unset()
}

// GetEndDateGt returns the EndDateGt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetEndDateGt() time.Time {
	if o == nil || IsNil(o.EndDateGt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndDateGt.Get()
}

// GetEndDateGtOk returns a tuple with the EndDateGt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetEndDateGtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDateGt.Get(), o.EndDateGt.IsSet()
}

// HasEndDateGt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasEndDateGt() bool {
	if o != nil && o.EndDateGt.IsSet() {
		return true
	}

	return false
}

// SetEndDateGt gets a reference to the given NullableTime and assigns it to the EndDateGt field.
func (o *DAGRunsBatchBody) SetEndDateGt(v time.Time) {
	o.EndDateGt.Set(&v)
}
// SetEndDateGtNil sets the value for EndDateGt to be an explicit nil
func (o *DAGRunsBatchBody) SetEndDateGtNil() {
	o.EndDateGt.Set(nil)
}

// UnsetEndDateGt ensures that no value is present for EndDateGt, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetEndDateGt() {
	o.EndDateGt.Unset()
}

// GetEndDateLte returns the EndDateLte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetEndDateLte() time.Time {
	if o == nil || IsNil(o.EndDateLte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndDateLte.Get()
}

// GetEndDateLteOk returns a tuple with the EndDateLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetEndDateLteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDateLte.Get(), o.EndDateLte.IsSet()
}

// HasEndDateLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasEndDateLte() bool {
	if o != nil && o.EndDateLte.IsSet() {
		return true
	}

	return false
}

// SetEndDateLte gets a reference to the given NullableTime and assigns it to the EndDateLte field.
func (o *DAGRunsBatchBody) SetEndDateLte(v time.Time) {
	o.EndDateLte.Set(&v)
}
// SetEndDateLteNil sets the value for EndDateLte to be an explicit nil
func (o *DAGRunsBatchBody) SetEndDateLteNil() {
	o.EndDateLte.Set(nil)
}

// UnsetEndDateLte ensures that no value is present for EndDateLte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetEndDateLte() {
	o.EndDateLte.Unset()
}

// GetEndDateLt returns the EndDateLt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetEndDateLt() time.Time {
	if o == nil || IsNil(o.EndDateLt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndDateLt.Get()
}

// GetEndDateLtOk returns a tuple with the EndDateLt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetEndDateLtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDateLt.Get(), o.EndDateLt.IsSet()
}

// HasEndDateLt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasEndDateLt() bool {
	if o != nil && o.EndDateLt.IsSet() {
		return true
	}

	return false
}

// SetEndDateLt gets a reference to the given NullableTime and assigns it to the EndDateLt field.
func (o *DAGRunsBatchBody) SetEndDateLt(v time.Time) {
	o.EndDateLt.Set(&v)
}
// SetEndDateLtNil sets the value for EndDateLt to be an explicit nil
func (o *DAGRunsBatchBody) SetEndDateLtNil() {
	o.EndDateLt.Set(nil)
}

// UnsetEndDateLt ensures that no value is present for EndDateLt, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetEndDateLt() {
	o.EndDateLt.Unset()
}

// GetDurationGte returns the DurationGte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetDurationGte() float32 {
	if o == nil || IsNil(o.DurationGte.Get()) {
		var ret float32
		return ret
	}
	return *o.DurationGte.Get()
}

// GetDurationGteOk returns a tuple with the DurationGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetDurationGteOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DurationGte.Get(), o.DurationGte.IsSet()
}

// HasDurationGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasDurationGte() bool {
	if o != nil && o.DurationGte.IsSet() {
		return true
	}

	return false
}

// SetDurationGte gets a reference to the given NullableFloat32 and assigns it to the DurationGte field.
func (o *DAGRunsBatchBody) SetDurationGte(v float32) {
	o.DurationGte.Set(&v)
}
// SetDurationGteNil sets the value for DurationGte to be an explicit nil
func (o *DAGRunsBatchBody) SetDurationGteNil() {
	o.DurationGte.Set(nil)
}

// UnsetDurationGte ensures that no value is present for DurationGte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetDurationGte() {
	o.DurationGte.Unset()
}

// GetDurationGt returns the DurationGt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetDurationGt() float32 {
	if o == nil || IsNil(o.DurationGt.Get()) {
		var ret float32
		return ret
	}
	return *o.DurationGt.Get()
}

// GetDurationGtOk returns a tuple with the DurationGt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetDurationGtOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DurationGt.Get(), o.DurationGt.IsSet()
}

// HasDurationGt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasDurationGt() bool {
	if o != nil && o.DurationGt.IsSet() {
		return true
	}

	return false
}

// SetDurationGt gets a reference to the given NullableFloat32 and assigns it to the DurationGt field.
func (o *DAGRunsBatchBody) SetDurationGt(v float32) {
	o.DurationGt.Set(&v)
}
// SetDurationGtNil sets the value for DurationGt to be an explicit nil
func (o *DAGRunsBatchBody) SetDurationGtNil() {
	o.DurationGt.Set(nil)
}

// UnsetDurationGt ensures that no value is present for DurationGt, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetDurationGt() {
	o.DurationGt.Unset()
}

// GetDurationLte returns the DurationLte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetDurationLte() float32 {
	if o == nil || IsNil(o.DurationLte.Get()) {
		var ret float32
		return ret
	}
	return *o.DurationLte.Get()
}

// GetDurationLteOk returns a tuple with the DurationLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetDurationLteOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DurationLte.Get(), o.DurationLte.IsSet()
}

// HasDurationLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasDurationLte() bool {
	if o != nil && o.DurationLte.IsSet() {
		return true
	}

	return false
}

// SetDurationLte gets a reference to the given NullableFloat32 and assigns it to the DurationLte field.
func (o *DAGRunsBatchBody) SetDurationLte(v float32) {
	o.DurationLte.Set(&v)
}
// SetDurationLteNil sets the value for DurationLte to be an explicit nil
func (o *DAGRunsBatchBody) SetDurationLteNil() {
	o.DurationLte.Set(nil)
}

// UnsetDurationLte ensures that no value is present for DurationLte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetDurationLte() {
	o.DurationLte.Unset()
}

// GetDurationLt returns the DurationLt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetDurationLt() float32 {
	if o == nil || IsNil(o.DurationLt.Get()) {
		var ret float32
		return ret
	}
	return *o.DurationLt.Get()
}

// GetDurationLtOk returns a tuple with the DurationLt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetDurationLtOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DurationLt.Get(), o.DurationLt.IsSet()
}

// HasDurationLt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasDurationLt() bool {
	if o != nil && o.DurationLt.IsSet() {
		return true
	}

	return false
}

// SetDurationLt gets a reference to the given NullableFloat32 and assigns it to the DurationLt field.
func (o *DAGRunsBatchBody) SetDurationLt(v float32) {
	o.DurationLt.Set(&v)
}
// SetDurationLtNil sets the value for DurationLt to be an explicit nil
func (o *DAGRunsBatchBody) SetDurationLtNil() {
	o.DurationLt.Set(nil)
}

// UnsetDurationLt ensures that no value is present for DurationLt, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetDurationLt() {
	o.DurationLt.Unset()
}

// GetConfContains returns the ConfContains field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetConfContains() string {
	if o == nil || IsNil(o.ConfContains.Get()) {
		var ret string
		return ret
	}
	return *o.ConfContains.Get()
}

// GetConfContainsOk returns a tuple with the ConfContains field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetConfContainsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfContains.Get(), o.ConfContains.IsSet()
}

// HasConfContains returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasConfContains() bool {
	if o != nil && o.ConfContains.IsSet() {
		return true
	}

	return false
}

// SetConfContains gets a reference to the given NullableString and assigns it to the ConfContains field.
func (o *DAGRunsBatchBody) SetConfContains(v string) {
	o.ConfContains.Set(&v)
}
// SetConfContainsNil sets the value for ConfContains to be an explicit nil
func (o *DAGRunsBatchBody) SetConfContainsNil() {
	o.ConfContains.Set(nil)
}

// UnsetConfContains ensures that no value is present for ConfContains, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetConfContains() {
	o.ConfContains.Unset()
}

func (o DAGRunsBatchBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DAGRunsBatchBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.OrderBy.IsSet() {
		toSerialize["order_by"] = o.OrderBy.Get()
	}
	if !IsNil(o.PageOffset) {
		toSerialize["page_offset"] = o.PageOffset
	}
	if !IsNil(o.PageLimit) {
		toSerialize["page_limit"] = o.PageLimit
	}
	if o.DagIds != nil {
		toSerialize["dag_ids"] = o.DagIds
	}
	if o.States != nil {
		toSerialize["states"] = o.States
	}
	if o.RunAfterGte.IsSet() {
		toSerialize["run_after_gte"] = o.RunAfterGte.Get()
	}
	if o.RunAfterGt.IsSet() {
		toSerialize["run_after_gt"] = o.RunAfterGt.Get()
	}
	if o.RunAfterLte.IsSet() {
		toSerialize["run_after_lte"] = o.RunAfterLte.Get()
	}
	if o.RunAfterLt.IsSet() {
		toSerialize["run_after_lt"] = o.RunAfterLt.Get()
	}
	if o.LogicalDateGte.IsSet() {
		toSerialize["logical_date_gte"] = o.LogicalDateGte.Get()
	}
	if o.LogicalDateGt.IsSet() {
		toSerialize["logical_date_gt"] = o.LogicalDateGt.Get()
	}
	if o.LogicalDateLte.IsSet() {
		toSerialize["logical_date_lte"] = o.LogicalDateLte.Get()
	}
	if o.LogicalDateLt.IsSet() {
		toSerialize["logical_date_lt"] = o.LogicalDateLt.Get()
	}
	if o.StartDateGte.IsSet() {
		toSerialize["start_date_gte"] = o.StartDateGte.Get()
	}
	if o.StartDateGt.IsSet() {
		toSerialize["start_date_gt"] = o.StartDateGt.Get()
	}
	if o.StartDateLte.IsSet() {
		toSerialize["start_date_lte"] = o.StartDateLte.Get()
	}
	if o.StartDateLt.IsSet() {
		toSerialize["start_date_lt"] = o.StartDateLt.Get()
	}
	if o.EndDateGte.IsSet() {
		toSerialize["end_date_gte"] = o.EndDateGte.Get()
	}
	if o.EndDateGt.IsSet() {
		toSerialize["end_date_gt"] = o.EndDateGt.Get()
	}
	if o.EndDateLte.IsSet() {
		toSerialize["end_date_lte"] = o.EndDateLte.Get()
	}
	if o.EndDateLt.IsSet() {
		toSerialize["end_date_lt"] = o.EndDateLt.Get()
	}
	if o.DurationGte.IsSet() {
		toSerialize["duration_gte"] = o.DurationGte.Get()
	}
	if o.DurationGt.IsSet() {
		toSerialize["duration_gt"] = o.DurationGt.Get()
	}
	if o.DurationLte.IsSet() {
		toSerialize["duration_lte"] = o.DurationLte.Get()
	}
	if o.DurationLt.IsSet() {
		toSerialize["duration_lt"] = o.DurationLt.Get()
	}
	if o.ConfContains.IsSet() {
		toSerialize["conf_contains"] = o.ConfContains.Get()
	}
	return toSerialize, nil
}

type NullableDAGRunsBatchBody struct {
	value *DAGRunsBatchBody
	isSet bool
}

func (v NullableDAGRunsBatchBody) Get() *DAGRunsBatchBody {
	return v.value
}

func (v *NullableDAGRunsBatchBody) Set(val *DAGRunsBatchBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDAGRunsBatchBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDAGRunsBatchBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDAGRunsBatchBody(val *DAGRunsBatchBody) *NullableDAGRunsBatchBody {
	return &NullableDAGRunsBatchBody{value: val, isSet: true}
}

func (v NullableDAGRunsBatchBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDAGRunsBatchBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


