/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TimeDelta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimeDelta{}

// TimeDelta TimeDelta can be used to interact with datetime.timedelta objects.
type TimeDelta struct {
	Type *string `json:"__type,omitempty"`
	Days int32 `json:"days"`
	Seconds int32 `json:"seconds"`
	Microseconds int32 `json:"microseconds"`
}

type _TimeDelta TimeDelta

// NewTimeDelta instantiates a new TimeDelta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeDelta(days int32, seconds int32, microseconds int32) *TimeDelta {
	this := TimeDelta{}
	var type_ string = "TimeDelta"
	this.Type = &type_
	this.Days = days
	this.Seconds = seconds
	this.Microseconds = microseconds
	return &this
}

// NewTimeDeltaWithDefaults instantiates a new TimeDelta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimeDeltaWithDefaults() *TimeDelta {
	this := TimeDelta{}
	var type_ string = "TimeDelta"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TimeDelta) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeDelta) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TimeDelta) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TimeDelta) SetType(v string) {
	o.Type = &v
}

// GetDays returns the Days field value
func (o *TimeDelta) GetDays() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Days
}

// GetDaysOk returns a tuple with the Days field value
// and a boolean to check if the value has been set.
func (o *TimeDelta) GetDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Days, true
}

// SetDays sets field value
func (o *TimeDelta) SetDays(v int32) {
	o.Days = v
}

// GetSeconds returns the Seconds field value
func (o *TimeDelta) GetSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value
// and a boolean to check if the value has been set.
func (o *TimeDelta) GetSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seconds, true
}

// SetSeconds sets field value
func (o *TimeDelta) SetSeconds(v int32) {
	o.Seconds = v
}

// GetMicroseconds returns the Microseconds field value
func (o *TimeDelta) GetMicroseconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Microseconds
}

// GetMicrosecondsOk returns a tuple with the Microseconds field value
// and a boolean to check if the value has been set.
func (o *TimeDelta) GetMicrosecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Microseconds, true
}

// SetMicroseconds sets field value
func (o *TimeDelta) SetMicroseconds(v int32) {
	o.Microseconds = v
}

func (o TimeDelta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimeDelta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["__type"] = o.Type
	}
	toSerialize["days"] = o.Days
	toSerialize["seconds"] = o.Seconds
	toSerialize["microseconds"] = o.Microseconds
	return toSerialize, nil
}

func (o *TimeDelta) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	if (string(data) == "null") {
		return err
	}
	requiredProperties := []string{
		"days",
		"seconds",
		"microseconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimeDelta := _TimeDelta{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimeDelta)

	if err != nil {
		return err
	}

	*o = TimeDelta(varTimeDelta)

	return err
}

type NullableTimeDelta struct {
	value *TimeDelta
	isSet bool
}

func (v NullableTimeDelta) Get() *TimeDelta {
	return v.value
}

func (v *NullableTimeDelta) Set(val *TimeDelta) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeDelta) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeDelta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeDelta(val *TimeDelta) *NullableTimeDelta {
	return &NullableTimeDelta{value: val, isSet: true}
}

func (v NullableTimeDelta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeDelta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


