/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TaskInstanceHistoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskInstanceHistoryResponse{}

// TaskInstanceHistoryResponse TaskInstanceHistory serializer for responses.
type TaskInstanceHistoryResponse struct {
	TaskId string `json:"task_id"`
	DagId string `json:"dag_id"`
	DagRunId string `json:"dag_run_id"`
	MapIndex int32 `json:"map_index"`
	StartDate NullableTime `json:"start_date"`
	EndDate NullableTime `json:"end_date"`
	Duration NullableFloat32 `json:"duration"`
	State NullableTaskInstanceState `json:"state"`
	TryNumber int32 `json:"try_number"`
	MaxTries int32 `json:"max_tries"`
	TaskDisplayName string `json:"task_display_name"`
	DagDisplayName string `json:"dag_display_name"`
	Hostname NullableString `json:"hostname"`
	Unixname NullableString `json:"unixname"`
	Pool string `json:"pool"`
	PoolSlots int32 `json:"pool_slots"`
	Queue NullableString `json:"queue"`
	PriorityWeight NullableInt32 `json:"priority_weight"`
	Operator NullableString `json:"operator"`
	OperatorName NullableString `json:"operator_name"`
	QueuedWhen NullableTime `json:"queued_when"`
	ScheduledWhen NullableTime `json:"scheduled_when"`
	Pid NullableInt32 `json:"pid"`
	Executor NullableString `json:"executor"`
	ExecutorConfig string `json:"executor_config"`
	DagVersion NullableDagVersionResponse `json:"dag_version"`
}

type _TaskInstanceHistoryResponse TaskInstanceHistoryResponse

// NewTaskInstanceHistoryResponse instantiates a new TaskInstanceHistoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskInstanceHistoryResponse(taskId string, dagId string, dagRunId string, mapIndex int32, startDate NullableTime, endDate NullableTime, duration NullableFloat32, state NullableTaskInstanceState, tryNumber int32, maxTries int32, taskDisplayName string, dagDisplayName string, hostname NullableString, unixname NullableString, pool string, poolSlots int32, queue NullableString, priorityWeight NullableInt32, operator NullableString, operatorName NullableString, queuedWhen NullableTime, scheduledWhen NullableTime, pid NullableInt32, executor NullableString, executorConfig string, dagVersion NullableDagVersionResponse) *TaskInstanceHistoryResponse {
	this := TaskInstanceHistoryResponse{}
	this.TaskId = taskId
	this.DagId = dagId
	this.DagRunId = dagRunId
	this.MapIndex = mapIndex
	this.StartDate = startDate
	this.EndDate = endDate
	this.Duration = duration
	this.State = state
	this.TryNumber = tryNumber
	this.MaxTries = maxTries
	this.TaskDisplayName = taskDisplayName
	this.DagDisplayName = dagDisplayName
	this.Hostname = hostname
	this.Unixname = unixname
	this.Pool = pool
	this.PoolSlots = poolSlots
	this.Queue = queue
	this.PriorityWeight = priorityWeight
	this.Operator = operator
	this.OperatorName = operatorName
	this.QueuedWhen = queuedWhen
	this.ScheduledWhen = scheduledWhen
	this.Pid = pid
	this.Executor = executor
	this.ExecutorConfig = executorConfig
	this.DagVersion = dagVersion
	return &this
}

// NewTaskInstanceHistoryResponseWithDefaults instantiates a new TaskInstanceHistoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskInstanceHistoryResponseWithDefaults() *TaskInstanceHistoryResponse {
	this := TaskInstanceHistoryResponse{}
	return &this
}

// GetTaskId returns the TaskId field value
func (o *TaskInstanceHistoryResponse) GetTaskId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceHistoryResponse) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskId, true
}

// SetTaskId sets field value
func (o *TaskInstanceHistoryResponse) SetTaskId(v string) {
	o.TaskId = v
}

// GetDagId returns the DagId field value
func (o *TaskInstanceHistoryResponse) GetDagId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DagId
}

// GetDagIdOk returns a tuple with the DagId field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceHistoryResponse) GetDagIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DagId, true
}

// SetDagId sets field value
func (o *TaskInstanceHistoryResponse) SetDagId(v string) {
	o.DagId = v
}

// GetDagRunId returns the DagRunId field value
func (o *TaskInstanceHistoryResponse) GetDagRunId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DagRunId
}

// GetDagRunIdOk returns a tuple with the DagRunId field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceHistoryResponse) GetDagRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DagRunId, true
}

// SetDagRunId sets field value
func (o *TaskInstanceHistoryResponse) SetDagRunId(v string) {
	o.DagRunId = v
}

// GetMapIndex returns the MapIndex field value
func (o *TaskInstanceHistoryResponse) GetMapIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MapIndex
}

// GetMapIndexOk returns a tuple with the MapIndex field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceHistoryResponse) GetMapIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MapIndex, true
}

// SetMapIndex sets field value
func (o *TaskInstanceHistoryResponse) SetMapIndex(v int32) {
	o.MapIndex = v
}

// GetStartDate returns the StartDate field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *TaskInstanceHistoryResponse) GetStartDate() time.Time {
	if o == nil || o.StartDate.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.StartDate.Get()
}

// GetStartDateOk returns a tuple with the StartDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetStartDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDate.Get(), o.StartDate.IsSet()
}

// SetStartDate sets field value
func (o *TaskInstanceHistoryResponse) SetStartDate(v time.Time) {
	o.StartDate.Set(&v)
}

// GetEndDate returns the EndDate field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *TaskInstanceHistoryResponse) GetEndDate() time.Time {
	if o == nil || o.EndDate.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.EndDate.Get()
}

// GetEndDateOk returns a tuple with the EndDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetEndDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDate.Get(), o.EndDate.IsSet()
}

// SetEndDate sets field value
func (o *TaskInstanceHistoryResponse) SetEndDate(v time.Time) {
	o.EndDate.Set(&v)
}

// GetDuration returns the Duration field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *TaskInstanceHistoryResponse) GetDuration() float32 {
	if o == nil || o.Duration.Get() == nil {
		var ret float32
		return ret
	}

	return *o.Duration.Get()
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetDurationOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Duration.Get(), o.Duration.IsSet()
}

// SetDuration sets field value
func (o *TaskInstanceHistoryResponse) SetDuration(v float32) {
	o.Duration.Set(&v)
}

// GetState returns the State field value
// If the value is explicit nil, the zero value for TaskInstanceState will be returned
func (o *TaskInstanceHistoryResponse) GetState() TaskInstanceState {
	if o == nil || o.State.Get() == nil {
		var ret TaskInstanceState
		return ret
	}

	return *o.State.Get()
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetStateOk() (*TaskInstanceState, bool) {
	if o == nil {
		return nil, false
	}
	return o.State.Get(), o.State.IsSet()
}

// SetState sets field value
func (o *TaskInstanceHistoryResponse) SetState(v TaskInstanceState) {
	o.State.Set(&v)
}

// GetTryNumber returns the TryNumber field value
func (o *TaskInstanceHistoryResponse) GetTryNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TryNumber
}

// GetTryNumberOk returns a tuple with the TryNumber field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceHistoryResponse) GetTryNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TryNumber, true
}

// SetTryNumber sets field value
func (o *TaskInstanceHistoryResponse) SetTryNumber(v int32) {
	o.TryNumber = v
}

// GetMaxTries returns the MaxTries field value
func (o *TaskInstanceHistoryResponse) GetMaxTries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxTries
}

// GetMaxTriesOk returns a tuple with the MaxTries field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceHistoryResponse) GetMaxTriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxTries, true
}

// SetMaxTries sets field value
func (o *TaskInstanceHistoryResponse) SetMaxTries(v int32) {
	o.MaxTries = v
}

// GetTaskDisplayName returns the TaskDisplayName field value
func (o *TaskInstanceHistoryResponse) GetTaskDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskDisplayName
}

// GetTaskDisplayNameOk returns a tuple with the TaskDisplayName field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceHistoryResponse) GetTaskDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskDisplayName, true
}

// SetTaskDisplayName sets field value
func (o *TaskInstanceHistoryResponse) SetTaskDisplayName(v string) {
	o.TaskDisplayName = v
}

// GetDagDisplayName returns the DagDisplayName field value
func (o *TaskInstanceHistoryResponse) GetDagDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DagDisplayName
}

// GetDagDisplayNameOk returns a tuple with the DagDisplayName field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceHistoryResponse) GetDagDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DagDisplayName, true
}

// SetDagDisplayName sets field value
func (o *TaskInstanceHistoryResponse) SetDagDisplayName(v string) {
	o.DagDisplayName = v
}

// GetHostname returns the Hostname field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TaskInstanceHistoryResponse) GetHostname() string {
	if o == nil || o.Hostname.Get() == nil {
		var ret string
		return ret
	}

	return *o.Hostname.Get()
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hostname.Get(), o.Hostname.IsSet()
}

// SetHostname sets field value
func (o *TaskInstanceHistoryResponse) SetHostname(v string) {
	o.Hostname.Set(&v)
}

// GetUnixname returns the Unixname field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TaskInstanceHistoryResponse) GetUnixname() string {
	if o == nil || o.Unixname.Get() == nil {
		var ret string
		return ret
	}

	return *o.Unixname.Get()
}

// GetUnixnameOk returns a tuple with the Unixname field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetUnixnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Unixname.Get(), o.Unixname.IsSet()
}

// SetUnixname sets field value
func (o *TaskInstanceHistoryResponse) SetUnixname(v string) {
	o.Unixname.Set(&v)
}

// GetPool returns the Pool field value
func (o *TaskInstanceHistoryResponse) GetPool() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pool
}

// GetPoolOk returns a tuple with the Pool field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceHistoryResponse) GetPoolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pool, true
}

// SetPool sets field value
func (o *TaskInstanceHistoryResponse) SetPool(v string) {
	o.Pool = v
}

// GetPoolSlots returns the PoolSlots field value
func (o *TaskInstanceHistoryResponse) GetPoolSlots() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PoolSlots
}

// GetPoolSlotsOk returns a tuple with the PoolSlots field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceHistoryResponse) GetPoolSlotsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolSlots, true
}

// SetPoolSlots sets field value
func (o *TaskInstanceHistoryResponse) SetPoolSlots(v int32) {
	o.PoolSlots = v
}

// GetQueue returns the Queue field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TaskInstanceHistoryResponse) GetQueue() string {
	if o == nil || o.Queue.Get() == nil {
		var ret string
		return ret
	}

	return *o.Queue.Get()
}

// GetQueueOk returns a tuple with the Queue field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetQueueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Queue.Get(), o.Queue.IsSet()
}

// SetQueue sets field value
func (o *TaskInstanceHistoryResponse) SetQueue(v string) {
	o.Queue.Set(&v)
}

// GetPriorityWeight returns the PriorityWeight field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *TaskInstanceHistoryResponse) GetPriorityWeight() int32 {
	if o == nil || o.PriorityWeight.Get() == nil {
		var ret int32
		return ret
	}

	return *o.PriorityWeight.Get()
}

// GetPriorityWeightOk returns a tuple with the PriorityWeight field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetPriorityWeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PriorityWeight.Get(), o.PriorityWeight.IsSet()
}

// SetPriorityWeight sets field value
func (o *TaskInstanceHistoryResponse) SetPriorityWeight(v int32) {
	o.PriorityWeight.Set(&v)
}

// GetOperator returns the Operator field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TaskInstanceHistoryResponse) GetOperator() string {
	if o == nil || o.Operator.Get() == nil {
		var ret string
		return ret
	}

	return *o.Operator.Get()
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetOperatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Operator.Get(), o.Operator.IsSet()
}

// SetOperator sets field value
func (o *TaskInstanceHistoryResponse) SetOperator(v string) {
	o.Operator.Set(&v)
}

// GetOperatorName returns the OperatorName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TaskInstanceHistoryResponse) GetOperatorName() string {
	if o == nil || o.OperatorName.Get() == nil {
		var ret string
		return ret
	}

	return *o.OperatorName.Get()
}

// GetOperatorNameOk returns a tuple with the OperatorName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetOperatorNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OperatorName.Get(), o.OperatorName.IsSet()
}

// SetOperatorName sets field value
func (o *TaskInstanceHistoryResponse) SetOperatorName(v string) {
	o.OperatorName.Set(&v)
}

// GetQueuedWhen returns the QueuedWhen field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *TaskInstanceHistoryResponse) GetQueuedWhen() time.Time {
	if o == nil || o.QueuedWhen.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.QueuedWhen.Get()
}

// GetQueuedWhenOk returns a tuple with the QueuedWhen field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetQueuedWhenOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.QueuedWhen.Get(), o.QueuedWhen.IsSet()
}

// SetQueuedWhen sets field value
func (o *TaskInstanceHistoryResponse) SetQueuedWhen(v time.Time) {
	o.QueuedWhen.Set(&v)
}

// GetScheduledWhen returns the ScheduledWhen field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *TaskInstanceHistoryResponse) GetScheduledWhen() time.Time {
	if o == nil || o.ScheduledWhen.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ScheduledWhen.Get()
}

// GetScheduledWhenOk returns a tuple with the ScheduledWhen field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetScheduledWhenOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScheduledWhen.Get(), o.ScheduledWhen.IsSet()
}

// SetScheduledWhen sets field value
func (o *TaskInstanceHistoryResponse) SetScheduledWhen(v time.Time) {
	o.ScheduledWhen.Set(&v)
}

// GetPid returns the Pid field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *TaskInstanceHistoryResponse) GetPid() int32 {
	if o == nil || o.Pid.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Pid.Get()
}

// GetPidOk returns a tuple with the Pid field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetPidOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pid.Get(), o.Pid.IsSet()
}

// SetPid sets field value
func (o *TaskInstanceHistoryResponse) SetPid(v int32) {
	o.Pid.Set(&v)
}

// GetExecutor returns the Executor field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TaskInstanceHistoryResponse) GetExecutor() string {
	if o == nil || o.Executor.Get() == nil {
		var ret string
		return ret
	}

	return *o.Executor.Get()
}

// GetExecutorOk returns a tuple with the Executor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetExecutorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Executor.Get(), o.Executor.IsSet()
}

// SetExecutor sets field value
func (o *TaskInstanceHistoryResponse) SetExecutor(v string) {
	o.Executor.Set(&v)
}

// GetExecutorConfig returns the ExecutorConfig field value
func (o *TaskInstanceHistoryResponse) GetExecutorConfig() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExecutorConfig
}

// GetExecutorConfigOk returns a tuple with the ExecutorConfig field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceHistoryResponse) GetExecutorConfigOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutorConfig, true
}

// SetExecutorConfig sets field value
func (o *TaskInstanceHistoryResponse) SetExecutorConfig(v string) {
	o.ExecutorConfig = v
}

// GetDagVersion returns the DagVersion field value
// If the value is explicit nil, the zero value for DagVersionResponse will be returned
func (o *TaskInstanceHistoryResponse) GetDagVersion() DagVersionResponse {
	if o == nil || o.DagVersion.Get() == nil {
		var ret DagVersionResponse
		return ret
	}

	return *o.DagVersion.Get()
}

// GetDagVersionOk returns a tuple with the DagVersion field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceHistoryResponse) GetDagVersionOk() (*DagVersionResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.DagVersion.Get(), o.DagVersion.IsSet()
}

// SetDagVersion sets field value
func (o *TaskInstanceHistoryResponse) SetDagVersion(v DagVersionResponse) {
	o.DagVersion.Set(&v)
}

func (o TaskInstanceHistoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskInstanceHistoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["task_id"] = o.TaskId
	toSerialize["dag_id"] = o.DagId
	toSerialize["dag_run_id"] = o.DagRunId
	toSerialize["map_index"] = o.MapIndex
	toSerialize["start_date"] = o.StartDate.Get()
	toSerialize["end_date"] = o.EndDate.Get()
	toSerialize["duration"] = o.Duration.Get()
	toSerialize["state"] = o.State.Get()
	toSerialize["try_number"] = o.TryNumber
	toSerialize["max_tries"] = o.MaxTries
	toSerialize["task_display_name"] = o.TaskDisplayName
	toSerialize["dag_display_name"] = o.DagDisplayName
	toSerialize["hostname"] = o.Hostname.Get()
	toSerialize["unixname"] = o.Unixname.Get()
	toSerialize["pool"] = o.Pool
	toSerialize["pool_slots"] = o.PoolSlots
	toSerialize["queue"] = o.Queue.Get()
	toSerialize["priority_weight"] = o.PriorityWeight.Get()
	toSerialize["operator"] = o.Operator.Get()
	toSerialize["operator_name"] = o.OperatorName.Get()
	toSerialize["queued_when"] = o.QueuedWhen.Get()
	toSerialize["scheduled_when"] = o.ScheduledWhen.Get()
	toSerialize["pid"] = o.Pid.Get()
	toSerialize["executor"] = o.Executor.Get()
	toSerialize["executor_config"] = o.ExecutorConfig
	toSerialize["dag_version"] = o.DagVersion.Get()
	return toSerialize, nil
}

func (o *TaskInstanceHistoryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"task_id",
		"dag_id",
		"dag_run_id",
		"map_index",
		"start_date",
		"end_date",
		"duration",
		"state",
		"try_number",
		"max_tries",
		"task_display_name",
		"dag_display_name",
		"hostname",
		"unixname",
		"pool",
		"pool_slots",
		"queue",
		"priority_weight",
		"operator",
		"operator_name",
		"queued_when",
		"scheduled_when",
		"pid",
		"executor",
		"executor_config",
		"dag_version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaskInstanceHistoryResponse := _TaskInstanceHistoryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaskInstanceHistoryResponse)

	if err != nil {
		return err
	}

	*o = TaskInstanceHistoryResponse(varTaskInstanceHistoryResponse)

	return err
}

type NullableTaskInstanceHistoryResponse struct {
	value *TaskInstanceHistoryResponse
	isSet bool
}

func (v NullableTaskInstanceHistoryResponse) Get() *TaskInstanceHistoryResponse {
	return v.value
}

func (v *NullableTaskInstanceHistoryResponse) Set(val *TaskInstanceHistoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskInstanceHistoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskInstanceHistoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskInstanceHistoryResponse(val *TaskInstanceHistoryResponse) *NullableTaskInstanceHistoryResponse {
	return &NullableTaskInstanceHistoryResponse{value: val, isSet: true}
}

func (v NullableTaskInstanceHistoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskInstanceHistoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


