/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"fmt"
)


// EntitiesInner3 struct for EntitiesInner3
type EntitiesInner3 struct {
	VariableBody *VariableBody
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *EntitiesInner3) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into VariableBody
	err = json.Unmarshal(data, &dst.VariableBody);
	if err == nil {
		jsonVariableBody, _ := json.Marshal(dst.VariableBody)
		if string(jsonVariableBody) == "{}" { // empty struct
			dst.VariableBody = nil
		} else {
			return nil // data stored in dst.VariableBody, return on the first match
		}
	} else {
		dst.VariableBody = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(EntitiesInner3)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src EntitiesInner3) MarshalJSON() ([]byte, error) {
	if src.VariableBody != nil {
		return json.Marshal(&src.VariableBody)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableEntitiesInner3 struct {
	value *EntitiesInner3
	isSet bool
}

func (v NullableEntitiesInner3) Get() *EntitiesInner3 {
	return v.value
}

func (v *NullableEntitiesInner3) Set(val *EntitiesInner3) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitiesInner3) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitiesInner3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitiesInner3(val *EntitiesInner3) *NullableEntitiesInner3 {
	return &NullableEntitiesInner3{value: val, isSet: true}
}

func (v NullableEntitiesInner3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitiesInner3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


