/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"fmt"
)

// BulkActionOnExistence Bulk Action to be taken if the entity already exists or not.
type BulkActionOnExistence string

// List of BulkActionOnExistence
const (
	FAIL BulkActionOnExistence = "fail"
	SKIP BulkActionOnExistence = "skip"
	OVERWRITE BulkActionOnExistence = "overwrite"
)

// All allowed values of BulkActionOnExistence enum
var AllowedBulkActionOnExistenceEnumValues = []BulkActionOnExistence{
	"fail",
	"skip",
	"overwrite",
}

func (v *BulkActionOnExistence) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkActionOnExistence(value)
	for _, existing := range AllowedBulkActionOnExistenceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkActionOnExistence", value)
}

// NewBulkActionOnExistenceFromValue returns a pointer to a valid BulkActionOnExistence
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkActionOnExistenceFromValue(v string) (*BulkActionOnExistence, error) {
	ev := BulkActionOnExistence(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkActionOnExistence: valid values are %v", v, AllowedBulkActionOnExistenceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkActionOnExistence) IsValid() bool {
	for _, existing := range AllowedBulkActionOnExistenceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkActionOnExistence value
func (v BulkActionOnExistence) Ptr() *BulkActionOnExistence {
	return &v
}

type NullableBulkActionOnExistence struct {
	value *BulkActionOnExistence
	isSet bool
}

func (v NullableBulkActionOnExistence) Get() *BulkActionOnExistence {
	return v.value
}

func (v *NullableBulkActionOnExistence) Set(val *BulkActionOnExistence) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkActionOnExistence) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkActionOnExistence) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkActionOnExistence(val *BulkActionOnExistence) *NullableBulkActionOnExistence {
	return &NullableBulkActionOnExistence{value: val, isSet: true}
}

func (v NullableBulkActionOnExistence) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkActionOnExistence) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

