/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DAGCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DAGCollectionResponse{}

// DAGCollectionResponse Dag Collection serializer for responses.
type DAGCollectionResponse struct {
	Dags []DAGResponse `json:"dags"`
	TotalEntries int32 `json:"total_entries"`
}

type _DAGCollectionResponse DAGCollectionResponse

// NewDAGCollectionResponse instantiates a new DAGCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDAGCollectionResponse(dags []DAGResponse, totalEntries int32) *DAGCollectionResponse {
	this := DAGCollectionResponse{}
	this.Dags = dags
	this.TotalEntries = totalEntries
	return &this
}

// NewDAGCollectionResponseWithDefaults instantiates a new DAGCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDAGCollectionResponseWithDefaults() *DAGCollectionResponse {
	this := DAGCollectionResponse{}
	return &this
}

// GetDags returns the Dags field value
func (o *DAGCollectionResponse) GetDags() []DAGResponse {
	if o == nil {
		var ret []DAGResponse
		return ret
	}

	return o.Dags
}

// GetDagsOk returns a tuple with the Dags field value
// and a boolean to check if the value has been set.
func (o *DAGCollectionResponse) GetDagsOk() ([]DAGResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dags, true
}

// SetDags sets field value
func (o *DAGCollectionResponse) SetDags(v []DAGResponse) {
	o.Dags = v
}

// GetTotalEntries returns the TotalEntries field value
func (o *DAGCollectionResponse) GetTotalEntries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalEntries
}

// GetTotalEntriesOk returns a tuple with the TotalEntries field value
// and a boolean to check if the value has been set.
func (o *DAGCollectionResponse) GetTotalEntriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalEntries, true
}

// SetTotalEntries sets field value
func (o *DAGCollectionResponse) SetTotalEntries(v int32) {
	o.TotalEntries = v
}

func (o DAGCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DAGCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dags"] = o.Dags
	toSerialize["total_entries"] = o.TotalEntries
	return toSerialize, nil
}

func (o *DAGCollectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dags",
		"total_entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDAGCollectionResponse := _DAGCollectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDAGCollectionResponse)

	if err != nil {
		return err
	}

	*o = DAGCollectionResponse(varDAGCollectionResponse)

	return err
}

type NullableDAGCollectionResponse struct {
	value *DAGCollectionResponse
	isSet bool
}

func (v NullableDAGCollectionResponse) Get() *DAGCollectionResponse {
	return v.value
}

func (v *NullableDAGCollectionResponse) Set(val *DAGCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDAGCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDAGCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDAGCollectionResponse(val *DAGCollectionResponse) *NullableDAGCollectionResponse {
	return &NullableDAGCollectionResponse{value: val, isSet: true}
}

func (v NullableDAGCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDAGCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


