/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DAGRunResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DAGRunResponse{}

// DAGRunResponse Dag Run serializer for responses.
type DAGRunResponse struct {
	DagRunId string `json:"dag_run_id"`
	DagId string `json:"dag_id"`
	LogicalDate NullableTime `json:"logical_date"`
	QueuedAt NullableTime `json:"queued_at"`
	StartDate NullableTime `json:"start_date"`
	EndDate NullableTime `json:"end_date"`
	Duration NullableFloat32 `json:"duration"`
	DataIntervalStart NullableTime `json:"data_interval_start"`
	DataIntervalEnd NullableTime `json:"data_interval_end"`
	RunAfter time.Time `json:"run_after"`
	LastSchedulingDecision NullableTime `json:"last_scheduling_decision"`
	RunType DagRunType `json:"run_type"`
	State DagRunState `json:"state"`
	TriggeredBy NullableDagRunTriggeredByType `json:"triggered_by"`
	TriggeringUserName NullableString `json:"triggering_user_name"`
	Conf map[string]interface{} `json:"conf"`
	Note NullableString `json:"note"`
	DagVersions []DagVersionResponse `json:"dag_versions"`
	BundleVersion NullableString `json:"bundle_version"`
	DagDisplayName string `json:"dag_display_name"`
	PartitionKey NullableString `json:"partition_key"`
}

type _DAGRunResponse DAGRunResponse

// NewDAGRunResponse instantiates a new DAGRunResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDAGRunResponse(dagRunId string, dagId string, logicalDate NullableTime, queuedAt NullableTime, startDate NullableTime, endDate NullableTime, duration NullableFloat32, dataIntervalStart NullableTime, dataIntervalEnd NullableTime, runAfter time.Time, lastSchedulingDecision NullableTime, runType DagRunType, state DagRunState, triggeredBy NullableDagRunTriggeredByType, triggeringUserName NullableString, conf map[string]interface{}, note NullableString, dagVersions []DagVersionResponse, bundleVersion NullableString, dagDisplayName string, partitionKey NullableString) *DAGRunResponse {
	this := DAGRunResponse{}
	this.DagRunId = dagRunId
	this.DagId = dagId
	this.LogicalDate = logicalDate
	this.QueuedAt = queuedAt
	this.StartDate = startDate
	this.EndDate = endDate
	this.Duration = duration
	this.DataIntervalStart = dataIntervalStart
	this.DataIntervalEnd = dataIntervalEnd
	this.RunAfter = runAfter
	this.LastSchedulingDecision = lastSchedulingDecision
	this.RunType = runType
	this.State = state
	this.TriggeredBy = triggeredBy
	this.TriggeringUserName = triggeringUserName
	this.Conf = conf
	this.Note = note
	this.DagVersions = dagVersions
	this.BundleVersion = bundleVersion
	this.DagDisplayName = dagDisplayName
	this.PartitionKey = partitionKey
	return &this
}

// NewDAGRunResponseWithDefaults instantiates a new DAGRunResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDAGRunResponseWithDefaults() *DAGRunResponse {
	this := DAGRunResponse{}
	return &this
}

// GetDagRunId returns the DagRunId field value
func (o *DAGRunResponse) GetDagRunId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DagRunId
}

// GetDagRunIdOk returns a tuple with the DagRunId field value
// and a boolean to check if the value has been set.
func (o *DAGRunResponse) GetDagRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DagRunId, true
}

// SetDagRunId sets field value
func (o *DAGRunResponse) SetDagRunId(v string) {
	o.DagRunId = v
}

// GetDagId returns the DagId field value
func (o *DAGRunResponse) GetDagId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DagId
}

// GetDagIdOk returns a tuple with the DagId field value
// and a boolean to check if the value has been set.
func (o *DAGRunResponse) GetDagIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DagId, true
}

// SetDagId sets field value
func (o *DAGRunResponse) SetDagId(v string) {
	o.DagId = v
}

// GetLogicalDate returns the LogicalDate field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGRunResponse) GetLogicalDate() time.Time {
	if o == nil || o.LogicalDate.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LogicalDate.Get()
}

// GetLogicalDateOk returns a tuple with the LogicalDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetLogicalDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogicalDate.Get(), o.LogicalDate.IsSet()
}

// SetLogicalDate sets field value
func (o *DAGRunResponse) SetLogicalDate(v time.Time) {
	o.LogicalDate.Set(&v)
}

// GetQueuedAt returns the QueuedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGRunResponse) GetQueuedAt() time.Time {
	if o == nil || o.QueuedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.QueuedAt.Get()
}

// GetQueuedAtOk returns a tuple with the QueuedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetQueuedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.QueuedAt.Get(), o.QueuedAt.IsSet()
}

// SetQueuedAt sets field value
func (o *DAGRunResponse) SetQueuedAt(v time.Time) {
	o.QueuedAt.Set(&v)
}

// GetStartDate returns the StartDate field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGRunResponse) GetStartDate() time.Time {
	if o == nil || o.StartDate.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.StartDate.Get()
}

// GetStartDateOk returns a tuple with the StartDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetStartDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDate.Get(), o.StartDate.IsSet()
}

// SetStartDate sets field value
func (o *DAGRunResponse) SetStartDate(v time.Time) {
	o.StartDate.Set(&v)
}

// GetEndDate returns the EndDate field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGRunResponse) GetEndDate() time.Time {
	if o == nil || o.EndDate.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.EndDate.Get()
}

// GetEndDateOk returns a tuple with the EndDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetEndDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDate.Get(), o.EndDate.IsSet()
}

// SetEndDate sets field value
func (o *DAGRunResponse) SetEndDate(v time.Time) {
	o.EndDate.Set(&v)
}

// GetDuration returns the Duration field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *DAGRunResponse) GetDuration() float32 {
	if o == nil || o.Duration.Get() == nil {
		var ret float32
		return ret
	}

	return *o.Duration.Get()
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetDurationOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Duration.Get(), o.Duration.IsSet()
}

// SetDuration sets field value
func (o *DAGRunResponse) SetDuration(v float32) {
	o.Duration.Set(&v)
}

// GetDataIntervalStart returns the DataIntervalStart field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGRunResponse) GetDataIntervalStart() time.Time {
	if o == nil || o.DataIntervalStart.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.DataIntervalStart.Get()
}

// GetDataIntervalStartOk returns a tuple with the DataIntervalStart field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetDataIntervalStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataIntervalStart.Get(), o.DataIntervalStart.IsSet()
}

// SetDataIntervalStart sets field value
func (o *DAGRunResponse) SetDataIntervalStart(v time.Time) {
	o.DataIntervalStart.Set(&v)
}

// GetDataIntervalEnd returns the DataIntervalEnd field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGRunResponse) GetDataIntervalEnd() time.Time {
	if o == nil || o.DataIntervalEnd.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.DataIntervalEnd.Get()
}

// GetDataIntervalEndOk returns a tuple with the DataIntervalEnd field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetDataIntervalEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataIntervalEnd.Get(), o.DataIntervalEnd.IsSet()
}

// SetDataIntervalEnd sets field value
func (o *DAGRunResponse) SetDataIntervalEnd(v time.Time) {
	o.DataIntervalEnd.Set(&v)
}

// GetRunAfter returns the RunAfter field value
func (o *DAGRunResponse) GetRunAfter() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RunAfter
}

// GetRunAfterOk returns a tuple with the RunAfter field value
// and a boolean to check if the value has been set.
func (o *DAGRunResponse) GetRunAfterOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunAfter, true
}

// SetRunAfter sets field value
func (o *DAGRunResponse) SetRunAfter(v time.Time) {
	o.RunAfter = v
}

// GetLastSchedulingDecision returns the LastSchedulingDecision field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGRunResponse) GetLastSchedulingDecision() time.Time {
	if o == nil || o.LastSchedulingDecision.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastSchedulingDecision.Get()
}

// GetLastSchedulingDecisionOk returns a tuple with the LastSchedulingDecision field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetLastSchedulingDecisionOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastSchedulingDecision.Get(), o.LastSchedulingDecision.IsSet()
}

// SetLastSchedulingDecision sets field value
func (o *DAGRunResponse) SetLastSchedulingDecision(v time.Time) {
	o.LastSchedulingDecision.Set(&v)
}

// GetRunType returns the RunType field value
func (o *DAGRunResponse) GetRunType() DagRunType {
	if o == nil {
		var ret DagRunType
		return ret
	}

	return o.RunType
}

// GetRunTypeOk returns a tuple with the RunType field value
// and a boolean to check if the value has been set.
func (o *DAGRunResponse) GetRunTypeOk() (*DagRunType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunType, true
}

// SetRunType sets field value
func (o *DAGRunResponse) SetRunType(v DagRunType) {
	o.RunType = v
}

// GetState returns the State field value
func (o *DAGRunResponse) GetState() DagRunState {
	if o == nil {
		var ret DagRunState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *DAGRunResponse) GetStateOk() (*DagRunState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *DAGRunResponse) SetState(v DagRunState) {
	o.State = v
}

// GetTriggeredBy returns the TriggeredBy field value
// If the value is explicit nil, the zero value for DagRunTriggeredByType will be returned
func (o *DAGRunResponse) GetTriggeredBy() DagRunTriggeredByType {
	if o == nil || o.TriggeredBy.Get() == nil {
		var ret DagRunTriggeredByType
		return ret
	}

	return *o.TriggeredBy.Get()
}

// GetTriggeredByOk returns a tuple with the TriggeredBy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetTriggeredByOk() (*DagRunTriggeredByType, bool) {
	if o == nil {
		return nil, false
	}
	return o.TriggeredBy.Get(), o.TriggeredBy.IsSet()
}

// SetTriggeredBy sets field value
func (o *DAGRunResponse) SetTriggeredBy(v DagRunTriggeredByType) {
	o.TriggeredBy.Set(&v)
}

// GetTriggeringUserName returns the TriggeringUserName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DAGRunResponse) GetTriggeringUserName() string {
	if o == nil || o.TriggeringUserName.Get() == nil {
		var ret string
		return ret
	}

	return *o.TriggeringUserName.Get()
}

// GetTriggeringUserNameOk returns a tuple with the TriggeringUserName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetTriggeringUserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TriggeringUserName.Get(), o.TriggeringUserName.IsSet()
}

// SetTriggeringUserName sets field value
func (o *DAGRunResponse) SetTriggeringUserName(v string) {
	o.TriggeringUserName.Set(&v)
}

// GetConf returns the Conf field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *DAGRunResponse) GetConf() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Conf
}

// GetConfOk returns a tuple with the Conf field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetConfOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Conf) {
		return map[string]interface{}{}, false
	}
	return o.Conf, true
}

// SetConf sets field value
func (o *DAGRunResponse) SetConf(v map[string]interface{}) {
	o.Conf = v
}

// GetNote returns the Note field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DAGRunResponse) GetNote() string {
	if o == nil || o.Note.Get() == nil {
		var ret string
		return ret
	}

	return *o.Note.Get()
}

// GetNoteOk returns a tuple with the Note field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Note.Get(), o.Note.IsSet()
}

// SetNote sets field value
func (o *DAGRunResponse) SetNote(v string) {
	o.Note.Set(&v)
}

// GetDagVersions returns the DagVersions field value
func (o *DAGRunResponse) GetDagVersions() []DagVersionResponse {
	if o == nil {
		var ret []DagVersionResponse
		return ret
	}

	return o.DagVersions
}

// GetDagVersionsOk returns a tuple with the DagVersions field value
// and a boolean to check if the value has been set.
func (o *DAGRunResponse) GetDagVersionsOk() ([]DagVersionResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.DagVersions, true
}

// SetDagVersions sets field value
func (o *DAGRunResponse) SetDagVersions(v []DagVersionResponse) {
	o.DagVersions = v
}

// GetBundleVersion returns the BundleVersion field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DAGRunResponse) GetBundleVersion() string {
	if o == nil || o.BundleVersion.Get() == nil {
		var ret string
		return ret
	}

	return *o.BundleVersion.Get()
}

// GetBundleVersionOk returns a tuple with the BundleVersion field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetBundleVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BundleVersion.Get(), o.BundleVersion.IsSet()
}

// SetBundleVersion sets field value
func (o *DAGRunResponse) SetBundleVersion(v string) {
	o.BundleVersion.Set(&v)
}

// GetDagDisplayName returns the DagDisplayName field value
func (o *DAGRunResponse) GetDagDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DagDisplayName
}

// GetDagDisplayNameOk returns a tuple with the DagDisplayName field value
// and a boolean to check if the value has been set.
func (o *DAGRunResponse) GetDagDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DagDisplayName, true
}

// SetDagDisplayName sets field value
func (o *DAGRunResponse) SetDagDisplayName(v string) {
	o.DagDisplayName = v
}

// GetPartitionKey returns the PartitionKey field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DAGRunResponse) GetPartitionKey() string {
	if o == nil || o.PartitionKey.Get() == nil {
		var ret string
		return ret
	}

	return *o.PartitionKey.Get()
}

// GetPartitionKeyOk returns a tuple with the PartitionKey field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunResponse) GetPartitionKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PartitionKey.Get(), o.PartitionKey.IsSet()
}

// SetPartitionKey sets field value
func (o *DAGRunResponse) SetPartitionKey(v string) {
	o.PartitionKey.Set(&v)
}

func (o DAGRunResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DAGRunResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dag_run_id"] = o.DagRunId
	toSerialize["dag_id"] = o.DagId
	toSerialize["logical_date"] = o.LogicalDate.Get()
	toSerialize["queued_at"] = o.QueuedAt.Get()
	toSerialize["start_date"] = o.StartDate.Get()
	toSerialize["end_date"] = o.EndDate.Get()
	toSerialize["duration"] = o.Duration.Get()
	toSerialize["data_interval_start"] = o.DataIntervalStart.Get()
	toSerialize["data_interval_end"] = o.DataIntervalEnd.Get()
	toSerialize["run_after"] = o.RunAfter
	toSerialize["last_scheduling_decision"] = o.LastSchedulingDecision.Get()
	toSerialize["run_type"] = o.RunType
	toSerialize["state"] = o.State
	toSerialize["triggered_by"] = o.TriggeredBy.Get()
	toSerialize["triggering_user_name"] = o.TriggeringUserName.Get()
	if o.Conf != nil {
		toSerialize["conf"] = o.Conf
	}
	toSerialize["note"] = o.Note.Get()
	toSerialize["dag_versions"] = o.DagVersions
	toSerialize["bundle_version"] = o.BundleVersion.Get()
	toSerialize["dag_display_name"] = o.DagDisplayName
	toSerialize["partition_key"] = o.PartitionKey.Get()
	return toSerialize, nil
}

func (o *DAGRunResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dag_run_id",
		"dag_id",
		"logical_date",
		"queued_at",
		"start_date",
		"end_date",
		"duration",
		"data_interval_start",
		"data_interval_end",
		"run_after",
		"last_scheduling_decision",
		"run_type",
		"state",
		"triggered_by",
		"triggering_user_name",
		"conf",
		"note",
		"dag_versions",
		"bundle_version",
		"dag_display_name",
		"partition_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDAGRunResponse := _DAGRunResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDAGRunResponse)

	if err != nil {
		return err
	}

	*o = DAGRunResponse(varDAGRunResponse)

	return err
}

type NullableDAGRunResponse struct {
	value *DAGRunResponse
	isSet bool
}

func (v NullableDAGRunResponse) Get() *DAGRunResponse {
	return v.value
}

func (v *NullableDAGRunResponse) Set(val *DAGRunResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDAGRunResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDAGRunResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDAGRunResponse(val *DAGRunResponse) *NullableDAGRunResponse {
	return &NullableDAGRunResponse{value: val, isSet: true}
}

func (v NullableDAGRunResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDAGRunResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


