/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BaseInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseInfoResponse{}

// BaseInfoResponse Base info serializer for responses.
type BaseInfoResponse struct {
	Status string `json:"status"`
}

type _BaseInfoResponse BaseInfoResponse

// NewBaseInfoResponse instantiates a new BaseInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseInfoResponse(status string) *BaseInfoResponse {
	this := BaseInfoResponse{}
	this.Status = status
	return &this
}

// NewBaseInfoResponseWithDefaults instantiates a new BaseInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseInfoResponseWithDefaults() *BaseInfoResponse {
	this := BaseInfoResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *BaseInfoResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *BaseInfoResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *BaseInfoResponse) SetStatus(v string) {
	o.Status = v
}

func (o BaseInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *BaseInfoResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBaseInfoResponse := _BaseInfoResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBaseInfoResponse)

	if err != nil {
		return err
	}

	*o = BaseInfoResponse(varBaseInfoResponse)

	return err
}

type NullableBaseInfoResponse struct {
	value *BaseInfoResponse
	isSet bool
}

func (v NullableBaseInfoResponse) Get() *BaseInfoResponse {
	return v.value
}

func (v *NullableBaseInfoResponse) Set(val *BaseInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseInfoResponse(val *BaseInfoResponse) *NullableBaseInfoResponse {
	return &NullableBaseInfoResponse{value: val, isSet: true}
}

func (v NullableBaseInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


