/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the HITLDetailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HITLDetailResponse{}

// HITLDetailResponse Response of updating a Human-in-the-loop detail.
type HITLDetailResponse struct {
	RespondedBy HITLUser `json:"responded_by"`
	RespondedAt time.Time `json:"responded_at"`
	ChosenOptions []string `json:"chosen_options"`
	ParamsInput map[string]interface{} `json:"params_input,omitempty"`
}

type _HITLDetailResponse HITLDetailResponse

// NewHITLDetailResponse instantiates a new HITLDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHITLDetailResponse(respondedBy HITLUser, respondedAt time.Time, chosenOptions []string) *HITLDetailResponse {
	this := HITLDetailResponse{}
	this.RespondedBy = respondedBy
	this.RespondedAt = respondedAt
	this.ChosenOptions = chosenOptions
	return &this
}

// NewHITLDetailResponseWithDefaults instantiates a new HITLDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHITLDetailResponseWithDefaults() *HITLDetailResponse {
	this := HITLDetailResponse{}
	return &this
}

// GetRespondedBy returns the RespondedBy field value
func (o *HITLDetailResponse) GetRespondedBy() HITLUser {
	if o == nil {
		var ret HITLUser
		return ret
	}

	return o.RespondedBy
}

// GetRespondedByOk returns a tuple with the RespondedBy field value
// and a boolean to check if the value has been set.
func (o *HITLDetailResponse) GetRespondedByOk() (*HITLUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RespondedBy, true
}

// SetRespondedBy sets field value
func (o *HITLDetailResponse) SetRespondedBy(v HITLUser) {
	o.RespondedBy = v
}

// GetRespondedAt returns the RespondedAt field value
func (o *HITLDetailResponse) GetRespondedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RespondedAt
}

// GetRespondedAtOk returns a tuple with the RespondedAt field value
// and a boolean to check if the value has been set.
func (o *HITLDetailResponse) GetRespondedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RespondedAt, true
}

// SetRespondedAt sets field value
func (o *HITLDetailResponse) SetRespondedAt(v time.Time) {
	o.RespondedAt = v
}

// GetChosenOptions returns the ChosenOptions field value
func (o *HITLDetailResponse) GetChosenOptions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ChosenOptions
}

// GetChosenOptionsOk returns a tuple with the ChosenOptions field value
// and a boolean to check if the value has been set.
func (o *HITLDetailResponse) GetChosenOptionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChosenOptions, true
}

// SetChosenOptions sets field value
func (o *HITLDetailResponse) SetChosenOptions(v []string) {
	o.ChosenOptions = v
}

// GetParamsInput returns the ParamsInput field value if set, zero value otherwise.
func (o *HITLDetailResponse) GetParamsInput() map[string]interface{} {
	if o == nil || IsNil(o.ParamsInput) {
		var ret map[string]interface{}
		return ret
	}
	return o.ParamsInput
}

// GetParamsInputOk returns a tuple with the ParamsInput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HITLDetailResponse) GetParamsInputOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ParamsInput) {
		return map[string]interface{}{}, false
	}
	return o.ParamsInput, true
}

// HasParamsInput returns a boolean if a field has been set.
func (o *HITLDetailResponse) HasParamsInput() bool {
	if o != nil && !IsNil(o.ParamsInput) {
		return true
	}

	return false
}

// SetParamsInput gets a reference to the given map[string]interface{} and assigns it to the ParamsInput field.
func (o *HITLDetailResponse) SetParamsInput(v map[string]interface{}) {
	o.ParamsInput = v
}

func (o HITLDetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HITLDetailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["responded_by"] = o.RespondedBy
	toSerialize["responded_at"] = o.RespondedAt
	toSerialize["chosen_options"] = o.ChosenOptions
	if !IsNil(o.ParamsInput) {
		toSerialize["params_input"] = o.ParamsInput
	}
	return toSerialize, nil
}

func (o *HITLDetailResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"responded_by",
		"responded_at",
		"chosen_options",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHITLDetailResponse := _HITLDetailResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHITLDetailResponse)

	if err != nil {
		return err
	}

	*o = HITLDetailResponse(varHITLDetailResponse)

	return err
}

type NullableHITLDetailResponse struct {
	value *HITLDetailResponse
	isSet bool
}

func (v NullableHITLDetailResponse) Get() *HITLDetailResponse {
	return v.value
}

func (v *NullableHITLDetailResponse) Set(val *HITLDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHITLDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHITLDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHITLDetailResponse(val *HITLDetailResponse) *NullableHITLDetailResponse {
	return &NullableHITLDetailResponse{value: val, isSet: true}
}

func (v NullableHITLDetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHITLDetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


