/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VariableBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VariableBody{}

// VariableBody Variable serializer for bodies.
type VariableBody struct {
	Key string `json:"key"`
	Value interface{} `json:"value"`
	Description NullableString `json:"description,omitempty"`
	TeamName NullableString `json:"team_name,omitempty"`
}

type _VariableBody VariableBody

// NewVariableBody instantiates a new VariableBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVariableBody(key string, value interface{}) *VariableBody {
	this := VariableBody{}
	this.Key = key
	this.Value = value
	return &this
}

// NewVariableBodyWithDefaults instantiates a new VariableBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVariableBodyWithDefaults() *VariableBody {
	this := VariableBody{}
	return &this
}

// GetKey returns the Key field value
func (o *VariableBody) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *VariableBody) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *VariableBody) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *VariableBody) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VariableBody) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *VariableBody) SetValue(v interface{}) {
	o.Value = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VariableBody) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VariableBody) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *VariableBody) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *VariableBody) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *VariableBody) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *VariableBody) UnsetDescription() {
	o.Description.Unset()
}

// GetTeamName returns the TeamName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VariableBody) GetTeamName() string {
	if o == nil || IsNil(o.TeamName.Get()) {
		var ret string
		return ret
	}
	return *o.TeamName.Get()
}

// GetTeamNameOk returns a tuple with the TeamName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VariableBody) GetTeamNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TeamName.Get(), o.TeamName.IsSet()
}

// HasTeamName returns a boolean if a field has been set.
func (o *VariableBody) HasTeamName() bool {
	if o != nil && o.TeamName.IsSet() {
		return true
	}

	return false
}

// SetTeamName gets a reference to the given NullableString and assigns it to the TeamName field.
func (o *VariableBody) SetTeamName(v string) {
	o.TeamName.Set(&v)
}
// SetTeamNameNil sets the value for TeamName to be an explicit nil
func (o *VariableBody) SetTeamNameNil() {
	o.TeamName.Set(nil)
}

// UnsetTeamName ensures that no value is present for TeamName, not even an explicit nil
func (o *VariableBody) UnsetTeamName() {
	o.TeamName.Unset()
}

func (o VariableBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VariableBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.TeamName.IsSet() {
		toSerialize["team_name"] = o.TeamName.Get()
	}
	return toSerialize, nil
}

func (o *VariableBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVariableBody := _VariableBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVariableBody)

	if err != nil {
		return err
	}

	*o = VariableBody(varVariableBody)

	return err
}

type NullableVariableBody struct {
	value *VariableBody
	isSet bool
}

func (v NullableVariableBody) Get() *VariableBody {
	return v.value
}

func (v *NullableVariableBody) Set(val *VariableBody) {
	v.value = val
	v.isSet = true
}

func (v NullableVariableBody) IsSet() bool {
	return v.isSet
}

func (v *NullableVariableBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVariableBody(val *VariableBody) *NullableVariableBody {
	return &NullableVariableBody{value: val, isSet: true}
}

func (v NullableVariableBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVariableBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


