/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TaskInstanceCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskInstanceCollectionResponse{}

// TaskInstanceCollectionResponse Task instance collection response supporting both offset and cursor pagination.  A single flat model is used instead of a discriminated union (``Annotated[Offset | Cursor, Field(discriminator=...)]``) because the OpenAPI ``oneOf`` + ``discriminator`` construct is not handled correctly by ``@hey-api/openapi-ts`` / ``@7nohe/openapi-react-query-codegen``: return types degrade to ``unknown`` in JSDoc and can produce incorrect TypeScript types (see hey-api/openapi-ts#1613, #3270).
type TaskInstanceCollectionResponse struct {
	TaskInstances []TaskInstanceResponse `json:"task_instances"`
	// Total number of matching items. Populated for offset pagination, ``null`` when using cursor pagination.
	TotalEntries NullableInt32 `json:"total_entries,omitempty"`
	// Token pointing to the next page. Populated for cursor pagination, ``null`` when using offset pagination or when there is no next page.
	NextCursor NullableString `json:"next_cursor,omitempty"`
	// Token pointing to the previous page. Populated for cursor pagination, ``null`` when using offset pagination or when on the first page.
	PreviousCursor NullableString `json:"previous_cursor,omitempty"`
}

type _TaskInstanceCollectionResponse TaskInstanceCollectionResponse

// NewTaskInstanceCollectionResponse instantiates a new TaskInstanceCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskInstanceCollectionResponse(taskInstances []TaskInstanceResponse) *TaskInstanceCollectionResponse {
	this := TaskInstanceCollectionResponse{}
	this.TaskInstances = taskInstances
	return &this
}

// NewTaskInstanceCollectionResponseWithDefaults instantiates a new TaskInstanceCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskInstanceCollectionResponseWithDefaults() *TaskInstanceCollectionResponse {
	this := TaskInstanceCollectionResponse{}
	return &this
}

// GetTaskInstances returns the TaskInstances field value
func (o *TaskInstanceCollectionResponse) GetTaskInstances() []TaskInstanceResponse {
	if o == nil {
		var ret []TaskInstanceResponse
		return ret
	}

	return o.TaskInstances
}

// GetTaskInstancesOk returns a tuple with the TaskInstances field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceCollectionResponse) GetTaskInstancesOk() ([]TaskInstanceResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaskInstances, true
}

// SetTaskInstances sets field value
func (o *TaskInstanceCollectionResponse) SetTaskInstances(v []TaskInstanceResponse) {
	o.TaskInstances = v
}

// GetTotalEntries returns the TotalEntries field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaskInstanceCollectionResponse) GetTotalEntries() int32 {
	if o == nil || IsNil(o.TotalEntries.Get()) {
		var ret int32
		return ret
	}
	return *o.TotalEntries.Get()
}

// GetTotalEntriesOk returns a tuple with the TotalEntries field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceCollectionResponse) GetTotalEntriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalEntries.Get(), o.TotalEntries.IsSet()
}

// HasTotalEntries returns a boolean if a field has been set.
func (o *TaskInstanceCollectionResponse) HasTotalEntries() bool {
	if o != nil && o.TotalEntries.IsSet() {
		return true
	}

	return false
}

// SetTotalEntries gets a reference to the given NullableInt32 and assigns it to the TotalEntries field.
func (o *TaskInstanceCollectionResponse) SetTotalEntries(v int32) {
	o.TotalEntries.Set(&v)
}
// SetTotalEntriesNil sets the value for TotalEntries to be an explicit nil
func (o *TaskInstanceCollectionResponse) SetTotalEntriesNil() {
	o.TotalEntries.Set(nil)
}

// UnsetTotalEntries ensures that no value is present for TotalEntries, not even an explicit nil
func (o *TaskInstanceCollectionResponse) UnsetTotalEntries() {
	o.TotalEntries.Unset()
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaskInstanceCollectionResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceCollectionResponse) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *TaskInstanceCollectionResponse) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *TaskInstanceCollectionResponse) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}
// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *TaskInstanceCollectionResponse) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *TaskInstanceCollectionResponse) UnsetNextCursor() {
	o.NextCursor.Unset()
}

// GetPreviousCursor returns the PreviousCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaskInstanceCollectionResponse) GetPreviousCursor() string {
	if o == nil || IsNil(o.PreviousCursor.Get()) {
		var ret string
		return ret
	}
	return *o.PreviousCursor.Get()
}

// GetPreviousCursorOk returns a tuple with the PreviousCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskInstanceCollectionResponse) GetPreviousCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviousCursor.Get(), o.PreviousCursor.IsSet()
}

// HasPreviousCursor returns a boolean if a field has been set.
func (o *TaskInstanceCollectionResponse) HasPreviousCursor() bool {
	if o != nil && o.PreviousCursor.IsSet() {
		return true
	}

	return false
}

// SetPreviousCursor gets a reference to the given NullableString and assigns it to the PreviousCursor field.
func (o *TaskInstanceCollectionResponse) SetPreviousCursor(v string) {
	o.PreviousCursor.Set(&v)
}
// SetPreviousCursorNil sets the value for PreviousCursor to be an explicit nil
func (o *TaskInstanceCollectionResponse) SetPreviousCursorNil() {
	o.PreviousCursor.Set(nil)
}

// UnsetPreviousCursor ensures that no value is present for PreviousCursor, not even an explicit nil
func (o *TaskInstanceCollectionResponse) UnsetPreviousCursor() {
	o.PreviousCursor.Unset()
}

func (o TaskInstanceCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskInstanceCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["task_instances"] = o.TaskInstances
	if o.TotalEntries.IsSet() {
		toSerialize["total_entries"] = o.TotalEntries.Get()
	}
	if o.NextCursor.IsSet() {
		toSerialize["next_cursor"] = o.NextCursor.Get()
	}
	if o.PreviousCursor.IsSet() {
		toSerialize["previous_cursor"] = o.PreviousCursor.Get()
	}
	return toSerialize, nil
}

func (o *TaskInstanceCollectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"task_instances",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaskInstanceCollectionResponse := _TaskInstanceCollectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaskInstanceCollectionResponse)

	if err != nil {
		return err
	}

	*o = TaskInstanceCollectionResponse(varTaskInstanceCollectionResponse)

	return err
}

type NullableTaskInstanceCollectionResponse struct {
	value *TaskInstanceCollectionResponse
	isSet bool
}

func (v NullableTaskInstanceCollectionResponse) Get() *TaskInstanceCollectionResponse {
	return v.value
}

func (v *NullableTaskInstanceCollectionResponse) Set(val *TaskInstanceCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskInstanceCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskInstanceCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskInstanceCollectionResponse(val *TaskInstanceCollectionResponse) *NullableTaskInstanceCollectionResponse {
	return &NullableTaskInstanceCollectionResponse{value: val, isSet: true}
}

func (v NullableTaskInstanceCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskInstanceCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


