/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClearTaskInstanceCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClearTaskInstanceCollectionResponse{}

// ClearTaskInstanceCollectionResponse Response for clear dag run dry run, which may contain new tasks without full TaskInstance data.
type ClearTaskInstanceCollectionResponse struct {
	TaskInstances []TaskInstancesInner `json:"task_instances"`
	TotalEntries int32 `json:"total_entries"`
}

type _ClearTaskInstanceCollectionResponse ClearTaskInstanceCollectionResponse

// NewClearTaskInstanceCollectionResponse instantiates a new ClearTaskInstanceCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClearTaskInstanceCollectionResponse(taskInstances []TaskInstancesInner, totalEntries int32) *ClearTaskInstanceCollectionResponse {
	this := ClearTaskInstanceCollectionResponse{}
	this.TaskInstances = taskInstances
	this.TotalEntries = totalEntries
	return &this
}

// NewClearTaskInstanceCollectionResponseWithDefaults instantiates a new ClearTaskInstanceCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClearTaskInstanceCollectionResponseWithDefaults() *ClearTaskInstanceCollectionResponse {
	this := ClearTaskInstanceCollectionResponse{}
	return &this
}

// GetTaskInstances returns the TaskInstances field value
func (o *ClearTaskInstanceCollectionResponse) GetTaskInstances() []TaskInstancesInner {
	if o == nil {
		var ret []TaskInstancesInner
		return ret
	}

	return o.TaskInstances
}

// GetTaskInstancesOk returns a tuple with the TaskInstances field value
// and a boolean to check if the value has been set.
func (o *ClearTaskInstanceCollectionResponse) GetTaskInstancesOk() ([]TaskInstancesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaskInstances, true
}

// SetTaskInstances sets field value
func (o *ClearTaskInstanceCollectionResponse) SetTaskInstances(v []TaskInstancesInner) {
	o.TaskInstances = v
}

// GetTotalEntries returns the TotalEntries field value
func (o *ClearTaskInstanceCollectionResponse) GetTotalEntries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalEntries
}

// GetTotalEntriesOk returns a tuple with the TotalEntries field value
// and a boolean to check if the value has been set.
func (o *ClearTaskInstanceCollectionResponse) GetTotalEntriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalEntries, true
}

// SetTotalEntries sets field value
func (o *ClearTaskInstanceCollectionResponse) SetTotalEntries(v int32) {
	o.TotalEntries = v
}

func (o ClearTaskInstanceCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClearTaskInstanceCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["task_instances"] = o.TaskInstances
	toSerialize["total_entries"] = o.TotalEntries
	return toSerialize, nil
}

func (o *ClearTaskInstanceCollectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"task_instances",
		"total_entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClearTaskInstanceCollectionResponse := _ClearTaskInstanceCollectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClearTaskInstanceCollectionResponse)

	if err != nil {
		return err
	}

	*o = ClearTaskInstanceCollectionResponse(varClearTaskInstanceCollectionResponse)

	return err
}

type NullableClearTaskInstanceCollectionResponse struct {
	value *ClearTaskInstanceCollectionResponse
	isSet bool
}

func (v NullableClearTaskInstanceCollectionResponse) Get() *ClearTaskInstanceCollectionResponse {
	return v.value
}

func (v *NullableClearTaskInstanceCollectionResponse) Set(val *ClearTaskInstanceCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClearTaskInstanceCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClearTaskInstanceCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClearTaskInstanceCollectionResponse(val *ClearTaskInstanceCollectionResponse) *NullableClearTaskInstanceCollectionResponse {
	return &NullableClearTaskInstanceCollectionResponse{value: val, isSet: true}
}

func (v NullableClearTaskInstanceCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClearTaskInstanceCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


