/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"time"
)

// checks if the DAGRunsBatchBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DAGRunsBatchBody{}

// DAGRunsBatchBody List Dag Runs body for batch endpoint.
type DAGRunsBatchBody struct {
	OrderBy *string `json:"order_by,omitempty"`
	PageOffset *int32 `json:"page_offset,omitempty"`
	PageLimit *int32 `json:"page_limit,omitempty"`
	DagIds []string `json:"dag_ids,omitempty"`
	States []DagRunState `json:"states,omitempty"`
	RunAfterGte *time.Time `json:"run_after_gte,omitempty"`
	RunAfterGt *time.Time `json:"run_after_gt,omitempty"`
	RunAfterLte *time.Time `json:"run_after_lte,omitempty"`
	RunAfterLt *time.Time `json:"run_after_lt,omitempty"`
	LogicalDateGte *time.Time `json:"logical_date_gte,omitempty"`
	LogicalDateGt *time.Time `json:"logical_date_gt,omitempty"`
	LogicalDateLte *time.Time `json:"logical_date_lte,omitempty"`
	LogicalDateLt *time.Time `json:"logical_date_lt,omitempty"`
	StartDateGte *time.Time `json:"start_date_gte,omitempty"`
	StartDateGt *time.Time `json:"start_date_gt,omitempty"`
	StartDateLte *time.Time `json:"start_date_lte,omitempty"`
	StartDateLt *time.Time `json:"start_date_lt,omitempty"`
	EndDateGte *time.Time `json:"end_date_gte,omitempty"`
	EndDateGt *time.Time `json:"end_date_gt,omitempty"`
	EndDateLte *time.Time `json:"end_date_lte,omitempty"`
	EndDateLt *time.Time `json:"end_date_lt,omitempty"`
	DurationGte *float32 `json:"duration_gte,omitempty"`
	DurationGt *float32 `json:"duration_gt,omitempty"`
	DurationLte *float32 `json:"duration_lte,omitempty"`
	DurationLt *float32 `json:"duration_lt,omitempty"`
	ConfContains *string `json:"conf_contains,omitempty"`
}

// NewDAGRunsBatchBody instantiates a new DAGRunsBatchBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDAGRunsBatchBody() *DAGRunsBatchBody {
	this := DAGRunsBatchBody{}
	var pageOffset int32 = 0
	this.PageOffset = &pageOffset
	var pageLimit int32 = 100
	this.PageLimit = &pageLimit
	return &this
}

// NewDAGRunsBatchBodyWithDefaults instantiates a new DAGRunsBatchBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDAGRunsBatchBodyWithDefaults() *DAGRunsBatchBody {
	this := DAGRunsBatchBody{}
	var pageOffset int32 = 0
	this.PageOffset = &pageOffset
	var pageLimit int32 = 100
	this.PageLimit = &pageLimit
	return &this
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetOrderBy() string {
	if o == nil || IsNil(o.OrderBy) {
		var ret string
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetOrderByOk() (*string, bool) {
	if o == nil || IsNil(o.OrderBy) {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasOrderBy() bool {
	if o != nil && !IsNil(o.OrderBy) {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given string and assigns it to the OrderBy field.
func (o *DAGRunsBatchBody) SetOrderBy(v string) {
	o.OrderBy = &v
}

// GetPageOffset returns the PageOffset field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetPageOffset() int32 {
	if o == nil || IsNil(o.PageOffset) {
		var ret int32
		return ret
	}
	return *o.PageOffset
}

// GetPageOffsetOk returns a tuple with the PageOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetPageOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.PageOffset) {
		return nil, false
	}
	return o.PageOffset, true
}

// HasPageOffset returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasPageOffset() bool {
	if o != nil && !IsNil(o.PageOffset) {
		return true
	}

	return false
}

// SetPageOffset gets a reference to the given int32 and assigns it to the PageOffset field.
func (o *DAGRunsBatchBody) SetPageOffset(v int32) {
	o.PageOffset = &v
}

// GetPageLimit returns the PageLimit field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetPageLimit() int32 {
	if o == nil || IsNil(o.PageLimit) {
		var ret int32
		return ret
	}
	return *o.PageLimit
}

// GetPageLimitOk returns a tuple with the PageLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetPageLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.PageLimit) {
		return nil, false
	}
	return o.PageLimit, true
}

// HasPageLimit returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasPageLimit() bool {
	if o != nil && !IsNil(o.PageLimit) {
		return true
	}

	return false
}

// SetPageLimit gets a reference to the given int32 and assigns it to the PageLimit field.
func (o *DAGRunsBatchBody) SetPageLimit(v int32) {
	o.PageLimit = &v
}

// GetDagIds returns the DagIds field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetDagIds() []string {
	if o == nil || IsNil(o.DagIds) {
		var ret []string
		return ret
	}
	return o.DagIds
}

// GetDagIdsOk returns a tuple with the DagIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetDagIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DagIds) {
		return nil, false
	}
	return o.DagIds, true
}

// HasDagIds returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasDagIds() bool {
	if o != nil && !IsNil(o.DagIds) {
		return true
	}

	return false
}

// SetDagIds gets a reference to the given []string and assigns it to the DagIds field.
func (o *DAGRunsBatchBody) SetDagIds(v []string) {
	o.DagIds = v
}

// GetStates returns the States field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetStates() []DagRunState {
	if o == nil || IsNil(o.States) {
		var ret []DagRunState
		return ret
	}
	return o.States
}

// GetStatesOk returns a tuple with the States field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetStatesOk() ([]DagRunState, bool) {
	if o == nil || IsNil(o.States) {
		return nil, false
	}
	return o.States, true
}

// HasStates returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStates() bool {
	if o != nil && !IsNil(o.States) {
		return true
	}

	return false
}

// SetStates gets a reference to the given []DagRunState and assigns it to the States field.
func (o *DAGRunsBatchBody) SetStates(v []DagRunState) {
	o.States = v
}

// GetRunAfterGte returns the RunAfterGte field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetRunAfterGte() time.Time {
	if o == nil || IsNil(o.RunAfterGte) {
		var ret time.Time
		return ret
	}
	return *o.RunAfterGte
}

// GetRunAfterGteOk returns a tuple with the RunAfterGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetRunAfterGteOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RunAfterGte) {
		return nil, false
	}
	return o.RunAfterGte, true
}

// HasRunAfterGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasRunAfterGte() bool {
	if o != nil && !IsNil(o.RunAfterGte) {
		return true
	}

	return false
}

// SetRunAfterGte gets a reference to the given time.Time and assigns it to the RunAfterGte field.
func (o *DAGRunsBatchBody) SetRunAfterGte(v time.Time) {
	o.RunAfterGte = &v
}

// GetRunAfterGt returns the RunAfterGt field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetRunAfterGt() time.Time {
	if o == nil || IsNil(o.RunAfterGt) {
		var ret time.Time
		return ret
	}
	return *o.RunAfterGt
}

// GetRunAfterGtOk returns a tuple with the RunAfterGt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetRunAfterGtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RunAfterGt) {
		return nil, false
	}
	return o.RunAfterGt, true
}

// HasRunAfterGt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasRunAfterGt() bool {
	if o != nil && !IsNil(o.RunAfterGt) {
		return true
	}

	return false
}

// SetRunAfterGt gets a reference to the given time.Time and assigns it to the RunAfterGt field.
func (o *DAGRunsBatchBody) SetRunAfterGt(v time.Time) {
	o.RunAfterGt = &v
}

// GetRunAfterLte returns the RunAfterLte field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetRunAfterLte() time.Time {
	if o == nil || IsNil(o.RunAfterLte) {
		var ret time.Time
		return ret
	}
	return *o.RunAfterLte
}

// GetRunAfterLteOk returns a tuple with the RunAfterLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetRunAfterLteOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RunAfterLte) {
		return nil, false
	}
	return o.RunAfterLte, true
}

// HasRunAfterLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasRunAfterLte() bool {
	if o != nil && !IsNil(o.RunAfterLte) {
		return true
	}

	return false
}

// SetRunAfterLte gets a reference to the given time.Time and assigns it to the RunAfterLte field.
func (o *DAGRunsBatchBody) SetRunAfterLte(v time.Time) {
	o.RunAfterLte = &v
}

// GetRunAfterLt returns the RunAfterLt field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetRunAfterLt() time.Time {
	if o == nil || IsNil(o.RunAfterLt) {
		var ret time.Time
		return ret
	}
	return *o.RunAfterLt
}

// GetRunAfterLtOk returns a tuple with the RunAfterLt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetRunAfterLtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RunAfterLt) {
		return nil, false
	}
	return o.RunAfterLt, true
}

// HasRunAfterLt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasRunAfterLt() bool {
	if o != nil && !IsNil(o.RunAfterLt) {
		return true
	}

	return false
}

// SetRunAfterLt gets a reference to the given time.Time and assigns it to the RunAfterLt field.
func (o *DAGRunsBatchBody) SetRunAfterLt(v time.Time) {
	o.RunAfterLt = &v
}

// GetLogicalDateGte returns the LogicalDateGte field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetLogicalDateGte() time.Time {
	if o == nil || IsNil(o.LogicalDateGte) {
		var ret time.Time
		return ret
	}
	return *o.LogicalDateGte
}

// GetLogicalDateGteOk returns a tuple with the LogicalDateGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetLogicalDateGteOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LogicalDateGte) {
		return nil, false
	}
	return o.LogicalDateGte, true
}

// HasLogicalDateGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasLogicalDateGte() bool {
	if o != nil && !IsNil(o.LogicalDateGte) {
		return true
	}

	return false
}

// SetLogicalDateGte gets a reference to the given time.Time and assigns it to the LogicalDateGte field.
func (o *DAGRunsBatchBody) SetLogicalDateGte(v time.Time) {
	o.LogicalDateGte = &v
}

// GetLogicalDateGt returns the LogicalDateGt field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetLogicalDateGt() time.Time {
	if o == nil || IsNil(o.LogicalDateGt) {
		var ret time.Time
		return ret
	}
	return *o.LogicalDateGt
}

// GetLogicalDateGtOk returns a tuple with the LogicalDateGt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetLogicalDateGtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LogicalDateGt) {
		return nil, false
	}
	return o.LogicalDateGt, true
}

// HasLogicalDateGt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasLogicalDateGt() bool {
	if o != nil && !IsNil(o.LogicalDateGt) {
		return true
	}

	return false
}

// SetLogicalDateGt gets a reference to the given time.Time and assigns it to the LogicalDateGt field.
func (o *DAGRunsBatchBody) SetLogicalDateGt(v time.Time) {
	o.LogicalDateGt = &v
}

// GetLogicalDateLte returns the LogicalDateLte field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetLogicalDateLte() time.Time {
	if o == nil || IsNil(o.LogicalDateLte) {
		var ret time.Time
		return ret
	}
	return *o.LogicalDateLte
}

// GetLogicalDateLteOk returns a tuple with the LogicalDateLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetLogicalDateLteOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LogicalDateLte) {
		return nil, false
	}
	return o.LogicalDateLte, true
}

// HasLogicalDateLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasLogicalDateLte() bool {
	if o != nil && !IsNil(o.LogicalDateLte) {
		return true
	}

	return false
}

// SetLogicalDateLte gets a reference to the given time.Time and assigns it to the LogicalDateLte field.
func (o *DAGRunsBatchBody) SetLogicalDateLte(v time.Time) {
	o.LogicalDateLte = &v
}

// GetLogicalDateLt returns the LogicalDateLt field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetLogicalDateLt() time.Time {
	if o == nil || IsNil(o.LogicalDateLt) {
		var ret time.Time
		return ret
	}
	return *o.LogicalDateLt
}

// GetLogicalDateLtOk returns a tuple with the LogicalDateLt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetLogicalDateLtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LogicalDateLt) {
		return nil, false
	}
	return o.LogicalDateLt, true
}

// HasLogicalDateLt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasLogicalDateLt() bool {
	if o != nil && !IsNil(o.LogicalDateLt) {
		return true
	}

	return false
}

// SetLogicalDateLt gets a reference to the given time.Time and assigns it to the LogicalDateLt field.
func (o *DAGRunsBatchBody) SetLogicalDateLt(v time.Time) {
	o.LogicalDateLt = &v
}

// GetStartDateGte returns the StartDateGte field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetStartDateGte() time.Time {
	if o == nil || IsNil(o.StartDateGte) {
		var ret time.Time
		return ret
	}
	return *o.StartDateGte
}

// GetStartDateGteOk returns a tuple with the StartDateGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetStartDateGteOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDateGte) {
		return nil, false
	}
	return o.StartDateGte, true
}

// HasStartDateGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStartDateGte() bool {
	if o != nil && !IsNil(o.StartDateGte) {
		return true
	}

	return false
}

// SetStartDateGte gets a reference to the given time.Time and assigns it to the StartDateGte field.
func (o *DAGRunsBatchBody) SetStartDateGte(v time.Time) {
	o.StartDateGte = &v
}

// GetStartDateGt returns the StartDateGt field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetStartDateGt() time.Time {
	if o == nil || IsNil(o.StartDateGt) {
		var ret time.Time
		return ret
	}
	return *o.StartDateGt
}

// GetStartDateGtOk returns a tuple with the StartDateGt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetStartDateGtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDateGt) {
		return nil, false
	}
	return o.StartDateGt, true
}

// HasStartDateGt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStartDateGt() bool {
	if o != nil && !IsNil(o.StartDateGt) {
		return true
	}

	return false
}

// SetStartDateGt gets a reference to the given time.Time and assigns it to the StartDateGt field.
func (o *DAGRunsBatchBody) SetStartDateGt(v time.Time) {
	o.StartDateGt = &v
}

// GetStartDateLte returns the StartDateLte field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetStartDateLte() time.Time {
	if o == nil || IsNil(o.StartDateLte) {
		var ret time.Time
		return ret
	}
	return *o.StartDateLte
}

// GetStartDateLteOk returns a tuple with the StartDateLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetStartDateLteOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDateLte) {
		return nil, false
	}
	return o.StartDateLte, true
}

// HasStartDateLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStartDateLte() bool {
	if o != nil && !IsNil(o.StartDateLte) {
		return true
	}

	return false
}

// SetStartDateLte gets a reference to the given time.Time and assigns it to the StartDateLte field.
func (o *DAGRunsBatchBody) SetStartDateLte(v time.Time) {
	o.StartDateLte = &v
}

// GetStartDateLt returns the StartDateLt field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetStartDateLt() time.Time {
	if o == nil || IsNil(o.StartDateLt) {
		var ret time.Time
		return ret
	}
	return *o.StartDateLt
}

// GetStartDateLtOk returns a tuple with the StartDateLt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetStartDateLtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDateLt) {
		return nil, false
	}
	return o.StartDateLt, true
}

// HasStartDateLt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStartDateLt() bool {
	if o != nil && !IsNil(o.StartDateLt) {
		return true
	}

	return false
}

// SetStartDateLt gets a reference to the given time.Time and assigns it to the StartDateLt field.
func (o *DAGRunsBatchBody) SetStartDateLt(v time.Time) {
	o.StartDateLt = &v
}

// GetEndDateGte returns the EndDateGte field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetEndDateGte() time.Time {
	if o == nil || IsNil(o.EndDateGte) {
		var ret time.Time
		return ret
	}
	return *o.EndDateGte
}

// GetEndDateGteOk returns a tuple with the EndDateGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetEndDateGteOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDateGte) {
		return nil, false
	}
	return o.EndDateGte, true
}

// HasEndDateGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasEndDateGte() bool {
	if o != nil && !IsNil(o.EndDateGte) {
		return true
	}

	return false
}

// SetEndDateGte gets a reference to the given time.Time and assigns it to the EndDateGte field.
func (o *DAGRunsBatchBody) SetEndDateGte(v time.Time) {
	o.EndDateGte = &v
}

// GetEndDateGt returns the EndDateGt field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetEndDateGt() time.Time {
	if o == nil || IsNil(o.EndDateGt) {
		var ret time.Time
		return ret
	}
	return *o.EndDateGt
}

// GetEndDateGtOk returns a tuple with the EndDateGt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetEndDateGtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDateGt) {
		return nil, false
	}
	return o.EndDateGt, true
}

// HasEndDateGt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasEndDateGt() bool {
	if o != nil && !IsNil(o.EndDateGt) {
		return true
	}

	return false
}

// SetEndDateGt gets a reference to the given time.Time and assigns it to the EndDateGt field.
func (o *DAGRunsBatchBody) SetEndDateGt(v time.Time) {
	o.EndDateGt = &v
}

// GetEndDateLte returns the EndDateLte field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetEndDateLte() time.Time {
	if o == nil || IsNil(o.EndDateLte) {
		var ret time.Time
		return ret
	}
	return *o.EndDateLte
}

// GetEndDateLteOk returns a tuple with the EndDateLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetEndDateLteOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDateLte) {
		return nil, false
	}
	return o.EndDateLte, true
}

// HasEndDateLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasEndDateLte() bool {
	if o != nil && !IsNil(o.EndDateLte) {
		return true
	}

	return false
}

// SetEndDateLte gets a reference to the given time.Time and assigns it to the EndDateLte field.
func (o *DAGRunsBatchBody) SetEndDateLte(v time.Time) {
	o.EndDateLte = &v
}

// GetEndDateLt returns the EndDateLt field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetEndDateLt() time.Time {
	if o == nil || IsNil(o.EndDateLt) {
		var ret time.Time
		return ret
	}
	return *o.EndDateLt
}

// GetEndDateLtOk returns a tuple with the EndDateLt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetEndDateLtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDateLt) {
		return nil, false
	}
	return o.EndDateLt, true
}

// HasEndDateLt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasEndDateLt() bool {
	if o != nil && !IsNil(o.EndDateLt) {
		return true
	}

	return false
}

// SetEndDateLt gets a reference to the given time.Time and assigns it to the EndDateLt field.
func (o *DAGRunsBatchBody) SetEndDateLt(v time.Time) {
	o.EndDateLt = &v
}

// GetDurationGte returns the DurationGte field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetDurationGte() float32 {
	if o == nil || IsNil(o.DurationGte) {
		var ret float32
		return ret
	}
	return *o.DurationGte
}

// GetDurationGteOk returns a tuple with the DurationGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetDurationGteOk() (*float32, bool) {
	if o == nil || IsNil(o.DurationGte) {
		return nil, false
	}
	return o.DurationGte, true
}

// HasDurationGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasDurationGte() bool {
	if o != nil && !IsNil(o.DurationGte) {
		return true
	}

	return false
}

// SetDurationGte gets a reference to the given float32 and assigns it to the DurationGte field.
func (o *DAGRunsBatchBody) SetDurationGte(v float32) {
	o.DurationGte = &v
}

// GetDurationGt returns the DurationGt field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetDurationGt() float32 {
	if o == nil || IsNil(o.DurationGt) {
		var ret float32
		return ret
	}
	return *o.DurationGt
}

// GetDurationGtOk returns a tuple with the DurationGt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetDurationGtOk() (*float32, bool) {
	if o == nil || IsNil(o.DurationGt) {
		return nil, false
	}
	return o.DurationGt, true
}

// HasDurationGt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasDurationGt() bool {
	if o != nil && !IsNil(o.DurationGt) {
		return true
	}

	return false
}

// SetDurationGt gets a reference to the given float32 and assigns it to the DurationGt field.
func (o *DAGRunsBatchBody) SetDurationGt(v float32) {
	o.DurationGt = &v
}

// GetDurationLte returns the DurationLte field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetDurationLte() float32 {
	if o == nil || IsNil(o.DurationLte) {
		var ret float32
		return ret
	}
	return *o.DurationLte
}

// GetDurationLteOk returns a tuple with the DurationLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetDurationLteOk() (*float32, bool) {
	if o == nil || IsNil(o.DurationLte) {
		return nil, false
	}
	return o.DurationLte, true
}

// HasDurationLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasDurationLte() bool {
	if o != nil && !IsNil(o.DurationLte) {
		return true
	}

	return false
}

// SetDurationLte gets a reference to the given float32 and assigns it to the DurationLte field.
func (o *DAGRunsBatchBody) SetDurationLte(v float32) {
	o.DurationLte = &v
}

// GetDurationLt returns the DurationLt field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetDurationLt() float32 {
	if o == nil || IsNil(o.DurationLt) {
		var ret float32
		return ret
	}
	return *o.DurationLt
}

// GetDurationLtOk returns a tuple with the DurationLt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetDurationLtOk() (*float32, bool) {
	if o == nil || IsNil(o.DurationLt) {
		return nil, false
	}
	return o.DurationLt, true
}

// HasDurationLt returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasDurationLt() bool {
	if o != nil && !IsNil(o.DurationLt) {
		return true
	}

	return false
}

// SetDurationLt gets a reference to the given float32 and assigns it to the DurationLt field.
func (o *DAGRunsBatchBody) SetDurationLt(v float32) {
	o.DurationLt = &v
}

// GetConfContains returns the ConfContains field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetConfContains() string {
	if o == nil || IsNil(o.ConfContains) {
		var ret string
		return ret
	}
	return *o.ConfContains
}

// GetConfContainsOk returns a tuple with the ConfContains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetConfContainsOk() (*string, bool) {
	if o == nil || IsNil(o.ConfContains) {
		return nil, false
	}
	return o.ConfContains, true
}

// HasConfContains returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasConfContains() bool {
	if o != nil && !IsNil(o.ConfContains) {
		return true
	}

	return false
}

// SetConfContains gets a reference to the given string and assigns it to the ConfContains field.
func (o *DAGRunsBatchBody) SetConfContains(v string) {
	o.ConfContains = &v
}

func (o DAGRunsBatchBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DAGRunsBatchBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrderBy) {
		toSerialize["order_by"] = o.OrderBy
	}
	if !IsNil(o.PageOffset) {
		toSerialize["page_offset"] = o.PageOffset
	}
	if !IsNil(o.PageLimit) {
		toSerialize["page_limit"] = o.PageLimit
	}
	if !IsNil(o.DagIds) {
		toSerialize["dag_ids"] = o.DagIds
	}
	if !IsNil(o.States) {
		toSerialize["states"] = o.States
	}
	if !IsNil(o.RunAfterGte) {
		toSerialize["run_after_gte"] = o.RunAfterGte
	}
	if !IsNil(o.RunAfterGt) {
		toSerialize["run_after_gt"] = o.RunAfterGt
	}
	if !IsNil(o.RunAfterLte) {
		toSerialize["run_after_lte"] = o.RunAfterLte
	}
	if !IsNil(o.RunAfterLt) {
		toSerialize["run_after_lt"] = o.RunAfterLt
	}
	if !IsNil(o.LogicalDateGte) {
		toSerialize["logical_date_gte"] = o.LogicalDateGte
	}
	if !IsNil(o.LogicalDateGt) {
		toSerialize["logical_date_gt"] = o.LogicalDateGt
	}
	if !IsNil(o.LogicalDateLte) {
		toSerialize["logical_date_lte"] = o.LogicalDateLte
	}
	if !IsNil(o.LogicalDateLt) {
		toSerialize["logical_date_lt"] = o.LogicalDateLt
	}
	if !IsNil(o.StartDateGte) {
		toSerialize["start_date_gte"] = o.StartDateGte
	}
	if !IsNil(o.StartDateGt) {
		toSerialize["start_date_gt"] = o.StartDateGt
	}
	if !IsNil(o.StartDateLte) {
		toSerialize["start_date_lte"] = o.StartDateLte
	}
	if !IsNil(o.StartDateLt) {
		toSerialize["start_date_lt"] = o.StartDateLt
	}
	if !IsNil(o.EndDateGte) {
		toSerialize["end_date_gte"] = o.EndDateGte
	}
	if !IsNil(o.EndDateGt) {
		toSerialize["end_date_gt"] = o.EndDateGt
	}
	if !IsNil(o.EndDateLte) {
		toSerialize["end_date_lte"] = o.EndDateLte
	}
	if !IsNil(o.EndDateLt) {
		toSerialize["end_date_lt"] = o.EndDateLt
	}
	if !IsNil(o.DurationGte) {
		toSerialize["duration_gte"] = o.DurationGte
	}
	if !IsNil(o.DurationGt) {
		toSerialize["duration_gt"] = o.DurationGt
	}
	if !IsNil(o.DurationLte) {
		toSerialize["duration_lte"] = o.DurationLte
	}
	if !IsNil(o.DurationLt) {
		toSerialize["duration_lt"] = o.DurationLt
	}
	if !IsNil(o.ConfContains) {
		toSerialize["conf_contains"] = o.ConfContains
	}
	return toSerialize, nil
}

type NullableDAGRunsBatchBody struct {
	value *DAGRunsBatchBody
	isSet bool
}

func (v NullableDAGRunsBatchBody) Get() *DAGRunsBatchBody {
	return v.value
}

func (v *NullableDAGRunsBatchBody) Set(val *DAGRunsBatchBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDAGRunsBatchBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDAGRunsBatchBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDAGRunsBatchBody(val *DAGRunsBatchBody) *NullableDAGRunsBatchBody {
	return &NullableDAGRunsBatchBody{value: val, isSet: true}
}

func (v NullableDAGRunsBatchBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDAGRunsBatchBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


