/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DAGResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DAGResponse{}

// DAGResponse Dag serializer for responses.
type DAGResponse struct {
	DagId string `json:"dag_id"`
	DagDisplayName string `json:"dag_display_name"`
	IsPaused bool `json:"is_paused"`
	IsStale bool `json:"is_stale"`
	LastParsedTime NullableTime `json:"last_parsed_time"`
	LastParseDuration NullableFloat32 `json:"last_parse_duration"`
	LastExpired NullableTime `json:"last_expired"`
	BundleName NullableString `json:"bundle_name"`
	BundleVersion NullableString `json:"bundle_version"`
	RelativeFileloc NullableString `json:"relative_fileloc"`
	Fileloc string `json:"fileloc"`
	Description NullableString `json:"description"`
	TimetableSummary NullableString `json:"timetable_summary"`
	TimetableDescription NullableString `json:"timetable_description"`
	TimetablePartitioned bool `json:"timetable_partitioned"`
	Tags []DagTagResponse `json:"tags"`
	MaxActiveTasks int32 `json:"max_active_tasks"`
	MaxActiveRuns NullableInt32 `json:"max_active_runs"`
	MaxConsecutiveFailedDagRuns int32 `json:"max_consecutive_failed_dag_runs"`
	HasTaskConcurrencyLimits bool `json:"has_task_concurrency_limits"`
	HasImportErrors bool `json:"has_import_errors"`
	NextDagrunLogicalDate NullableTime `json:"next_dagrun_logical_date"`
	NextDagrunDataIntervalStart NullableTime `json:"next_dagrun_data_interval_start"`
	NextDagrunDataIntervalEnd NullableTime `json:"next_dagrun_data_interval_end"`
	NextDagrunRunAfter NullableTime `json:"next_dagrun_run_after"`
	AllowedRunTypes []DagRunType `json:"allowed_run_types"`
	Owners []string `json:"owners"`
	// Return file token.
	FileToken string `json:"file_token"`
}

type _DAGResponse DAGResponse

// NewDAGResponse instantiates a new DAGResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDAGResponse(dagId string, dagDisplayName string, isPaused bool, isStale bool, lastParsedTime NullableTime, lastParseDuration NullableFloat32, lastExpired NullableTime, bundleName NullableString, bundleVersion NullableString, relativeFileloc NullableString, fileloc string, description NullableString, timetableSummary NullableString, timetableDescription NullableString, timetablePartitioned bool, tags []DagTagResponse, maxActiveTasks int32, maxActiveRuns NullableInt32, maxConsecutiveFailedDagRuns int32, hasTaskConcurrencyLimits bool, hasImportErrors bool, nextDagrunLogicalDate NullableTime, nextDagrunDataIntervalStart NullableTime, nextDagrunDataIntervalEnd NullableTime, nextDagrunRunAfter NullableTime, allowedRunTypes []DagRunType, owners []string, fileToken string) *DAGResponse {
	this := DAGResponse{}
	this.DagId = dagId
	this.DagDisplayName = dagDisplayName
	this.IsPaused = isPaused
	this.IsStale = isStale
	this.LastParsedTime = lastParsedTime
	this.LastParseDuration = lastParseDuration
	this.LastExpired = lastExpired
	this.BundleName = bundleName
	this.BundleVersion = bundleVersion
	this.RelativeFileloc = relativeFileloc
	this.Fileloc = fileloc
	this.Description = description
	this.TimetableSummary = timetableSummary
	this.TimetableDescription = timetableDescription
	this.TimetablePartitioned = timetablePartitioned
	this.Tags = tags
	this.MaxActiveTasks = maxActiveTasks
	this.MaxActiveRuns = maxActiveRuns
	this.MaxConsecutiveFailedDagRuns = maxConsecutiveFailedDagRuns
	this.HasTaskConcurrencyLimits = hasTaskConcurrencyLimits
	this.HasImportErrors = hasImportErrors
	this.NextDagrunLogicalDate = nextDagrunLogicalDate
	this.NextDagrunDataIntervalStart = nextDagrunDataIntervalStart
	this.NextDagrunDataIntervalEnd = nextDagrunDataIntervalEnd
	this.NextDagrunRunAfter = nextDagrunRunAfter
	this.AllowedRunTypes = allowedRunTypes
	this.Owners = owners
	this.FileToken = fileToken
	return &this
}

// NewDAGResponseWithDefaults instantiates a new DAGResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDAGResponseWithDefaults() *DAGResponse {
	this := DAGResponse{}
	return &this
}

// GetDagId returns the DagId field value
func (o *DAGResponse) GetDagId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DagId
}

// GetDagIdOk returns a tuple with the DagId field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetDagIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DagId, true
}

// SetDagId sets field value
func (o *DAGResponse) SetDagId(v string) {
	o.DagId = v
}

// GetDagDisplayName returns the DagDisplayName field value
func (o *DAGResponse) GetDagDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DagDisplayName
}

// GetDagDisplayNameOk returns a tuple with the DagDisplayName field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetDagDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DagDisplayName, true
}

// SetDagDisplayName sets field value
func (o *DAGResponse) SetDagDisplayName(v string) {
	o.DagDisplayName = v
}

// GetIsPaused returns the IsPaused field value
func (o *DAGResponse) GetIsPaused() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPaused
}

// GetIsPausedOk returns a tuple with the IsPaused field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetIsPausedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPaused, true
}

// SetIsPaused sets field value
func (o *DAGResponse) SetIsPaused(v bool) {
	o.IsPaused = v
}

// GetIsStale returns the IsStale field value
func (o *DAGResponse) GetIsStale() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsStale
}

// GetIsStaleOk returns a tuple with the IsStale field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetIsStaleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsStale, true
}

// SetIsStale sets field value
func (o *DAGResponse) SetIsStale(v bool) {
	o.IsStale = v
}

// GetLastParsedTime returns the LastParsedTime field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGResponse) GetLastParsedTime() time.Time {
	if o == nil || o.LastParsedTime.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastParsedTime.Get()
}

// GetLastParsedTimeOk returns a tuple with the LastParsedTime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetLastParsedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastParsedTime.Get(), o.LastParsedTime.IsSet()
}

// SetLastParsedTime sets field value
func (o *DAGResponse) SetLastParsedTime(v time.Time) {
	o.LastParsedTime.Set(&v)
}

// GetLastParseDuration returns the LastParseDuration field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *DAGResponse) GetLastParseDuration() float32 {
	if o == nil || o.LastParseDuration.Get() == nil {
		var ret float32
		return ret
	}

	return *o.LastParseDuration.Get()
}

// GetLastParseDurationOk returns a tuple with the LastParseDuration field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetLastParseDurationOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastParseDuration.Get(), o.LastParseDuration.IsSet()
}

// SetLastParseDuration sets field value
func (o *DAGResponse) SetLastParseDuration(v float32) {
	o.LastParseDuration.Set(&v)
}

// GetLastExpired returns the LastExpired field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGResponse) GetLastExpired() time.Time {
	if o == nil || o.LastExpired.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastExpired.Get()
}

// GetLastExpiredOk returns a tuple with the LastExpired field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetLastExpiredOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastExpired.Get(), o.LastExpired.IsSet()
}

// SetLastExpired sets field value
func (o *DAGResponse) SetLastExpired(v time.Time) {
	o.LastExpired.Set(&v)
}

// GetBundleName returns the BundleName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DAGResponse) GetBundleName() string {
	if o == nil || o.BundleName.Get() == nil {
		var ret string
		return ret
	}

	return *o.BundleName.Get()
}

// GetBundleNameOk returns a tuple with the BundleName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetBundleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BundleName.Get(), o.BundleName.IsSet()
}

// SetBundleName sets field value
func (o *DAGResponse) SetBundleName(v string) {
	o.BundleName.Set(&v)
}

// GetBundleVersion returns the BundleVersion field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DAGResponse) GetBundleVersion() string {
	if o == nil || o.BundleVersion.Get() == nil {
		var ret string
		return ret
	}

	return *o.BundleVersion.Get()
}

// GetBundleVersionOk returns a tuple with the BundleVersion field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetBundleVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BundleVersion.Get(), o.BundleVersion.IsSet()
}

// SetBundleVersion sets field value
func (o *DAGResponse) SetBundleVersion(v string) {
	o.BundleVersion.Set(&v)
}

// GetRelativeFileloc returns the RelativeFileloc field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DAGResponse) GetRelativeFileloc() string {
	if o == nil || o.RelativeFileloc.Get() == nil {
		var ret string
		return ret
	}

	return *o.RelativeFileloc.Get()
}

// GetRelativeFilelocOk returns a tuple with the RelativeFileloc field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetRelativeFilelocOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RelativeFileloc.Get(), o.RelativeFileloc.IsSet()
}

// SetRelativeFileloc sets field value
func (o *DAGResponse) SetRelativeFileloc(v string) {
	o.RelativeFileloc.Set(&v)
}

// GetFileloc returns the Fileloc field value
func (o *DAGResponse) GetFileloc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fileloc
}

// GetFilelocOk returns a tuple with the Fileloc field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetFilelocOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fileloc, true
}

// SetFileloc sets field value
func (o *DAGResponse) SetFileloc(v string) {
	o.Fileloc = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DAGResponse) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *DAGResponse) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetTimetableSummary returns the TimetableSummary field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DAGResponse) GetTimetableSummary() string {
	if o == nil || o.TimetableSummary.Get() == nil {
		var ret string
		return ret
	}

	return *o.TimetableSummary.Get()
}

// GetTimetableSummaryOk returns a tuple with the TimetableSummary field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetTimetableSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimetableSummary.Get(), o.TimetableSummary.IsSet()
}

// SetTimetableSummary sets field value
func (o *DAGResponse) SetTimetableSummary(v string) {
	o.TimetableSummary.Set(&v)
}

// GetTimetableDescription returns the TimetableDescription field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DAGResponse) GetTimetableDescription() string {
	if o == nil || o.TimetableDescription.Get() == nil {
		var ret string
		return ret
	}

	return *o.TimetableDescription.Get()
}

// GetTimetableDescriptionOk returns a tuple with the TimetableDescription field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetTimetableDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimetableDescription.Get(), o.TimetableDescription.IsSet()
}

// SetTimetableDescription sets field value
func (o *DAGResponse) SetTimetableDescription(v string) {
	o.TimetableDescription.Set(&v)
}

// GetTimetablePartitioned returns the TimetablePartitioned field value
func (o *DAGResponse) GetTimetablePartitioned() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TimetablePartitioned
}

// GetTimetablePartitionedOk returns a tuple with the TimetablePartitioned field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetTimetablePartitionedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimetablePartitioned, true
}

// SetTimetablePartitioned sets field value
func (o *DAGResponse) SetTimetablePartitioned(v bool) {
	o.TimetablePartitioned = v
}

// GetTags returns the Tags field value
func (o *DAGResponse) GetTags() []DagTagResponse {
	if o == nil {
		var ret []DagTagResponse
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetTagsOk() ([]DagTagResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *DAGResponse) SetTags(v []DagTagResponse) {
	o.Tags = v
}

// GetMaxActiveTasks returns the MaxActiveTasks field value
func (o *DAGResponse) GetMaxActiveTasks() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxActiveTasks
}

// GetMaxActiveTasksOk returns a tuple with the MaxActiveTasks field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetMaxActiveTasksOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxActiveTasks, true
}

// SetMaxActiveTasks sets field value
func (o *DAGResponse) SetMaxActiveTasks(v int32) {
	o.MaxActiveTasks = v
}

// GetMaxActiveRuns returns the MaxActiveRuns field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *DAGResponse) GetMaxActiveRuns() int32 {
	if o == nil || o.MaxActiveRuns.Get() == nil {
		var ret int32
		return ret
	}

	return *o.MaxActiveRuns.Get()
}

// GetMaxActiveRunsOk returns a tuple with the MaxActiveRuns field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetMaxActiveRunsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxActiveRuns.Get(), o.MaxActiveRuns.IsSet()
}

// SetMaxActiveRuns sets field value
func (o *DAGResponse) SetMaxActiveRuns(v int32) {
	o.MaxActiveRuns.Set(&v)
}

// GetMaxConsecutiveFailedDagRuns returns the MaxConsecutiveFailedDagRuns field value
func (o *DAGResponse) GetMaxConsecutiveFailedDagRuns() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxConsecutiveFailedDagRuns
}

// GetMaxConsecutiveFailedDagRunsOk returns a tuple with the MaxConsecutiveFailedDagRuns field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetMaxConsecutiveFailedDagRunsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxConsecutiveFailedDagRuns, true
}

// SetMaxConsecutiveFailedDagRuns sets field value
func (o *DAGResponse) SetMaxConsecutiveFailedDagRuns(v int32) {
	o.MaxConsecutiveFailedDagRuns = v
}

// GetHasTaskConcurrencyLimits returns the HasTaskConcurrencyLimits field value
func (o *DAGResponse) GetHasTaskConcurrencyLimits() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasTaskConcurrencyLimits
}

// GetHasTaskConcurrencyLimitsOk returns a tuple with the HasTaskConcurrencyLimits field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetHasTaskConcurrencyLimitsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasTaskConcurrencyLimits, true
}

// SetHasTaskConcurrencyLimits sets field value
func (o *DAGResponse) SetHasTaskConcurrencyLimits(v bool) {
	o.HasTaskConcurrencyLimits = v
}

// GetHasImportErrors returns the HasImportErrors field value
func (o *DAGResponse) GetHasImportErrors() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasImportErrors
}

// GetHasImportErrorsOk returns a tuple with the HasImportErrors field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetHasImportErrorsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasImportErrors, true
}

// SetHasImportErrors sets field value
func (o *DAGResponse) SetHasImportErrors(v bool) {
	o.HasImportErrors = v
}

// GetNextDagrunLogicalDate returns the NextDagrunLogicalDate field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGResponse) GetNextDagrunLogicalDate() time.Time {
	if o == nil || o.NextDagrunLogicalDate.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.NextDagrunLogicalDate.Get()
}

// GetNextDagrunLogicalDateOk returns a tuple with the NextDagrunLogicalDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetNextDagrunLogicalDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextDagrunLogicalDate.Get(), o.NextDagrunLogicalDate.IsSet()
}

// SetNextDagrunLogicalDate sets field value
func (o *DAGResponse) SetNextDagrunLogicalDate(v time.Time) {
	o.NextDagrunLogicalDate.Set(&v)
}

// GetNextDagrunDataIntervalStart returns the NextDagrunDataIntervalStart field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGResponse) GetNextDagrunDataIntervalStart() time.Time {
	if o == nil || o.NextDagrunDataIntervalStart.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.NextDagrunDataIntervalStart.Get()
}

// GetNextDagrunDataIntervalStartOk returns a tuple with the NextDagrunDataIntervalStart field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetNextDagrunDataIntervalStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextDagrunDataIntervalStart.Get(), o.NextDagrunDataIntervalStart.IsSet()
}

// SetNextDagrunDataIntervalStart sets field value
func (o *DAGResponse) SetNextDagrunDataIntervalStart(v time.Time) {
	o.NextDagrunDataIntervalStart.Set(&v)
}

// GetNextDagrunDataIntervalEnd returns the NextDagrunDataIntervalEnd field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGResponse) GetNextDagrunDataIntervalEnd() time.Time {
	if o == nil || o.NextDagrunDataIntervalEnd.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.NextDagrunDataIntervalEnd.Get()
}

// GetNextDagrunDataIntervalEndOk returns a tuple with the NextDagrunDataIntervalEnd field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetNextDagrunDataIntervalEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextDagrunDataIntervalEnd.Get(), o.NextDagrunDataIntervalEnd.IsSet()
}

// SetNextDagrunDataIntervalEnd sets field value
func (o *DAGResponse) SetNextDagrunDataIntervalEnd(v time.Time) {
	o.NextDagrunDataIntervalEnd.Set(&v)
}

// GetNextDagrunRunAfter returns the NextDagrunRunAfter field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *DAGResponse) GetNextDagrunRunAfter() time.Time {
	if o == nil || o.NextDagrunRunAfter.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.NextDagrunRunAfter.Get()
}

// GetNextDagrunRunAfterOk returns a tuple with the NextDagrunRunAfter field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetNextDagrunRunAfterOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextDagrunRunAfter.Get(), o.NextDagrunRunAfter.IsSet()
}

// SetNextDagrunRunAfter sets field value
func (o *DAGResponse) SetNextDagrunRunAfter(v time.Time) {
	o.NextDagrunRunAfter.Set(&v)
}

// GetAllowedRunTypes returns the AllowedRunTypes field value
// If the value is explicit nil, the zero value for []DagRunType will be returned
func (o *DAGResponse) GetAllowedRunTypes() []DagRunType {
	if o == nil {
		var ret []DagRunType
		return ret
	}

	return o.AllowedRunTypes
}

// GetAllowedRunTypesOk returns a tuple with the AllowedRunTypes field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGResponse) GetAllowedRunTypesOk() ([]DagRunType, bool) {
	if o == nil || IsNil(o.AllowedRunTypes) {
		return nil, false
	}
	return o.AllowedRunTypes, true
}

// SetAllowedRunTypes sets field value
func (o *DAGResponse) SetAllowedRunTypes(v []DagRunType) {
	o.AllowedRunTypes = v
}

// GetOwners returns the Owners field value
func (o *DAGResponse) GetOwners() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Owners
}

// GetOwnersOk returns a tuple with the Owners field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetOwnersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owners, true
}

// SetOwners sets field value
func (o *DAGResponse) SetOwners(v []string) {
	o.Owners = v
}

// GetFileToken returns the FileToken field value
func (o *DAGResponse) GetFileToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileToken
}

// GetFileTokenOk returns a tuple with the FileToken field value
// and a boolean to check if the value has been set.
func (o *DAGResponse) GetFileTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileToken, true
}

// SetFileToken sets field value
func (o *DAGResponse) SetFileToken(v string) {
	o.FileToken = v
}

func (o DAGResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DAGResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dag_id"] = o.DagId
	toSerialize["dag_display_name"] = o.DagDisplayName
	toSerialize["is_paused"] = o.IsPaused
	toSerialize["is_stale"] = o.IsStale
	toSerialize["last_parsed_time"] = o.LastParsedTime.Get()
	toSerialize["last_parse_duration"] = o.LastParseDuration.Get()
	toSerialize["last_expired"] = o.LastExpired.Get()
	toSerialize["bundle_name"] = o.BundleName.Get()
	toSerialize["bundle_version"] = o.BundleVersion.Get()
	toSerialize["relative_fileloc"] = o.RelativeFileloc.Get()
	toSerialize["fileloc"] = o.Fileloc
	toSerialize["description"] = o.Description.Get()
	toSerialize["timetable_summary"] = o.TimetableSummary.Get()
	toSerialize["timetable_description"] = o.TimetableDescription.Get()
	toSerialize["timetable_partitioned"] = o.TimetablePartitioned
	toSerialize["tags"] = o.Tags
	toSerialize["max_active_tasks"] = o.MaxActiveTasks
	toSerialize["max_active_runs"] = o.MaxActiveRuns.Get()
	toSerialize["max_consecutive_failed_dag_runs"] = o.MaxConsecutiveFailedDagRuns
	toSerialize["has_task_concurrency_limits"] = o.HasTaskConcurrencyLimits
	toSerialize["has_import_errors"] = o.HasImportErrors
	toSerialize["next_dagrun_logical_date"] = o.NextDagrunLogicalDate.Get()
	toSerialize["next_dagrun_data_interval_start"] = o.NextDagrunDataIntervalStart.Get()
	toSerialize["next_dagrun_data_interval_end"] = o.NextDagrunDataIntervalEnd.Get()
	toSerialize["next_dagrun_run_after"] = o.NextDagrunRunAfter.Get()
	if o.AllowedRunTypes != nil {
		toSerialize["allowed_run_types"] = o.AllowedRunTypes
	}
	toSerialize["owners"] = o.Owners
	toSerialize["file_token"] = o.FileToken
	return toSerialize, nil
}

func (o *DAGResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dag_id",
		"dag_display_name",
		"is_paused",
		"is_stale",
		"last_parsed_time",
		"last_parse_duration",
		"last_expired",
		"bundle_name",
		"bundle_version",
		"relative_fileloc",
		"fileloc",
		"description",
		"timetable_summary",
		"timetable_description",
		"timetable_partitioned",
		"tags",
		"max_active_tasks",
		"max_active_runs",
		"max_consecutive_failed_dag_runs",
		"has_task_concurrency_limits",
		"has_import_errors",
		"next_dagrun_logical_date",
		"next_dagrun_data_interval_start",
		"next_dagrun_data_interval_end",
		"next_dagrun_run_after",
		"allowed_run_types",
		"owners",
		"file_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDAGResponse := _DAGResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDAGResponse)

	if err != nil {
		return err
	}

	*o = DAGResponse(varDAGResponse)

	return err
}

type NullableDAGResponse struct {
	value *DAGResponse
	isSet bool
}

func (v NullableDAGResponse) Get() *DAGResponse {
	return v.value
}

func (v *NullableDAGResponse) Set(val *DAGResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDAGResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDAGResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDAGResponse(val *DAGResponse) *NullableDAGResponse {
	return &NullableDAGResponse{value: val, isSet: true}
}

func (v NullableDAGResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDAGResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


