/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventLogCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventLogCollectionResponse{}

// EventLogCollectionResponse Event Log Collection Response.
type EventLogCollectionResponse struct {
	EventLogs []EventLogResponse `json:"event_logs"`
	TotalEntries int32 `json:"total_entries"`
}

type _EventLogCollectionResponse EventLogCollectionResponse

// NewEventLogCollectionResponse instantiates a new EventLogCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventLogCollectionResponse(eventLogs []EventLogResponse, totalEntries int32) *EventLogCollectionResponse {
	this := EventLogCollectionResponse{}
	this.EventLogs = eventLogs
	this.TotalEntries = totalEntries
	return &this
}

// NewEventLogCollectionResponseWithDefaults instantiates a new EventLogCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventLogCollectionResponseWithDefaults() *EventLogCollectionResponse {
	this := EventLogCollectionResponse{}
	return &this
}

// GetEventLogs returns the EventLogs field value
func (o *EventLogCollectionResponse) GetEventLogs() []EventLogResponse {
	if o == nil {
		var ret []EventLogResponse
		return ret
	}

	return o.EventLogs
}

// GetEventLogsOk returns a tuple with the EventLogs field value
// and a boolean to check if the value has been set.
func (o *EventLogCollectionResponse) GetEventLogsOk() ([]EventLogResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventLogs, true
}

// SetEventLogs sets field value
func (o *EventLogCollectionResponse) SetEventLogs(v []EventLogResponse) {
	o.EventLogs = v
}

// GetTotalEntries returns the TotalEntries field value
func (o *EventLogCollectionResponse) GetTotalEntries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalEntries
}

// GetTotalEntriesOk returns a tuple with the TotalEntries field value
// and a boolean to check if the value has been set.
func (o *EventLogCollectionResponse) GetTotalEntriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalEntries, true
}

// SetTotalEntries sets field value
func (o *EventLogCollectionResponse) SetTotalEntries(v int32) {
	o.TotalEntries = v
}

func (o EventLogCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventLogCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_logs"] = o.EventLogs
	toSerialize["total_entries"] = o.TotalEntries
	return toSerialize, nil
}

func (o *EventLogCollectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_logs",
		"total_entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventLogCollectionResponse := _EventLogCollectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventLogCollectionResponse)

	if err != nil {
		return err
	}

	*o = EventLogCollectionResponse(varEventLogCollectionResponse)

	return err
}

type NullableEventLogCollectionResponse struct {
	value *EventLogCollectionResponse
	isSet bool
}

func (v NullableEventLogCollectionResponse) Get() *EventLogCollectionResponse {
	return v.value
}

func (v *NullableEventLogCollectionResponse) Set(val *EventLogCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEventLogCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEventLogCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventLogCollectionResponse(val *EventLogCollectionResponse) *NullableEventLogCollectionResponse {
	return &NullableEventLogCollectionResponse{value: val, isSet: true}
}

func (v NullableEventLogCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventLogCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


