/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConnectionCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionCollectionResponse{}

// ConnectionCollectionResponse Connection Collection serializer for responses.
type ConnectionCollectionResponse struct {
	Connections []ConnectionResponse `json:"connections"`
	TotalEntries int32 `json:"total_entries"`
}

type _ConnectionCollectionResponse ConnectionCollectionResponse

// NewConnectionCollectionResponse instantiates a new ConnectionCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionCollectionResponse(connections []ConnectionResponse, totalEntries int32) *ConnectionCollectionResponse {
	this := ConnectionCollectionResponse{}
	this.Connections = connections
	this.TotalEntries = totalEntries
	return &this
}

// NewConnectionCollectionResponseWithDefaults instantiates a new ConnectionCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionCollectionResponseWithDefaults() *ConnectionCollectionResponse {
	this := ConnectionCollectionResponse{}
	return &this
}

// GetConnections returns the Connections field value
func (o *ConnectionCollectionResponse) GetConnections() []ConnectionResponse {
	if o == nil {
		var ret []ConnectionResponse
		return ret
	}

	return o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value
// and a boolean to check if the value has been set.
func (o *ConnectionCollectionResponse) GetConnectionsOk() ([]ConnectionResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Connections, true
}

// SetConnections sets field value
func (o *ConnectionCollectionResponse) SetConnections(v []ConnectionResponse) {
	o.Connections = v
}

// GetTotalEntries returns the TotalEntries field value
func (o *ConnectionCollectionResponse) GetTotalEntries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalEntries
}

// GetTotalEntriesOk returns a tuple with the TotalEntries field value
// and a boolean to check if the value has been set.
func (o *ConnectionCollectionResponse) GetTotalEntriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalEntries, true
}

// SetTotalEntries sets field value
func (o *ConnectionCollectionResponse) SetTotalEntries(v int32) {
	o.TotalEntries = v
}

func (o ConnectionCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connections"] = o.Connections
	toSerialize["total_entries"] = o.TotalEntries
	return toSerialize, nil
}

func (o *ConnectionCollectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connections",
		"total_entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectionCollectionResponse := _ConnectionCollectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectionCollectionResponse)

	if err != nil {
		return err
	}

	*o = ConnectionCollectionResponse(varConnectionCollectionResponse)

	return err
}

type NullableConnectionCollectionResponse struct {
	value *ConnectionCollectionResponse
	isSet bool
}

func (v NullableConnectionCollectionResponse) Get() *ConnectionCollectionResponse {
	return v.value
}

func (v *NullableConnectionCollectionResponse) Set(val *ConnectionCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionCollectionResponse(val *ConnectionCollectionResponse) *NullableConnectionCollectionResponse {
	return &NullableConnectionCollectionResponse{value: val, isSet: true}
}

func (v NullableConnectionCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


